### ISSUE TITLE
Dark mode and reader mode 

### ISSUE THREAD

**Issue by trimechee** [Eloston/ungoogled-chromium#1943] opened 2022-05-04 15:18 UTC
Hello, it will be great to add a button to the worderful Ungoogled-Chromium Browser on the main bar to easily enable the Auto Dark Mode for Web Contents chrome flag and quickly disable it, enable reader mode flag recently deleted by chromium (may be integrate brave browser reader open source), thank you !

**Comment by PF4Public** [comment] 2022-05-04 15:52
Are you kidding?
Duplicate of #1939

**Comment by trimechee** [comment] 2022-05-04 16:41
No, you are you kidding ? you upset me, i decide afer an advice of developer to split my suggestions out into multiple issues, because he says to me that its not reasonable to manage multiple items under the umbrella of a single issue.

**Comment by trimechee** [comment] 2022-05-04 16:55
I decided to make it easier for you and I decided to split my great suggestions out into multiple issues, and a developer of web browser advise me its not reasonable to manage multiple items under the umbrella of a single issue, so I don't understand the problem ?!!! i forgot to delete my original post, don't dramatize, and no need to disrespect me as i gave full praise for ungoogled chromium and i follow you, I don't want to argue, delete your tweet, and I don't care if you make these suggestions, I already found a way to enable these options, I asked for this just for ordinary users, I contribute to improve ungoogled chromium and I am insulted !!! I talk just to Eleston the developer, the others do not have to comment on me

**Comment by PF4Public** [comment] 2022-05-08 12:39
> enable the Auto Dark Mode for Web Contents chrome flag and quickly disable it

Given that changing flags requires restart of a browser, I doubt it could be made "quicker" with the help of a button :(

**Comment by trimechee** [comment] 2022-05-08 13:48
lol it is quicker, and more simple for ordinary users, because we had to type chrome flags, type dark mode....with button in adresse bar , it is very quick

**Comment by PF4Public** [comment] 2022-05-08 14:00
You could add chrome://flags/#enable-force-dark into bookmarks.

**Comment by trimechee** [comment] 2022-05-08 14:31
Interesting !thank you very much :)

**Comment by PF4Public** [comment] 2022-05-08 21:44
Reader mode will return in 102 in the meanwhile one could unexpire flags, which were expired in 100.

W.r.t. dark mode, please continue the discussion in #1851

**Closed by PF4Public** 2022-05-08 21:44 UTC
Labels: enhancement, help wanted

**Comment by PF4Public** [comment] 2022-05-21 14:24
![image](https://user-images.githubusercontent.com/10319700/169655967-4de2bb32-a9fd-4e34-95e7-15fd8e274cd7.png)
