### ISSUE TITLE
Widevine CDM not working

### ISSUE THREAD

**Issue by stfnhrrs** [Eloston/ungoogled-chromium#73] opened 2016-10-01 16:52 UTC
Allow installation of WidevineCdm under chrome://components/ to allow viewing of videos on Amazon Video.

**Comment by Eloston** [comment] 2016-10-01 17:16
I already included a patch from Inox that should make the Widevine CDM module work. Is it not working?

**Comment by stfnhrrs** [comment] 2016-10-01 23:31
No, I'm not seeing it in chrome://components/ or chrome://plugins/ I'm running MacOS Sierra.  I've also tried downloading standalone Widevine but don't see any change, please see attached screenshots https://imgur.com/a/t1Msc

**Comment by stfnhrrs** [comment] 2016-10-01 23:32
No, I'm not seeing it in chrome://components/ or chrome://plugins/ I'm running MacOS Sierra. I've also tried downloading standalone Widevine but don't see any change, please see attached screenshots.

<img width="832" alt="screen shot 2016-10-01 at 19 25 55" src="https://cloud.githubusercontent.com/assets/1240279/19017603/c854124e-880d-11e6-840d-de48cd2d878e.png">
<img width="1437" alt="screen shot 2016-10-01 at 19 27 09" src="https://cloud.githubusercontent.com/assets/1240279/19017602/c853695c-880d-11e6-8250-4db6a46b96e6.png">
<img width="1438" alt="screen shot 2016-10-01 at 19 27 15" src="https://cloud.githubusercontent.com/assets/1240279/19017604/c8544322-880d-11e6-8796-30d58ebf37cd.png">

**Comment by Eloston** [comment] 2016-10-02 03:08
Huh, that is strange. I don't know if the Widevine patch works on macOS, but I heard it works on Linux.

@9Morello: Have you tried to get Widevine to work on macOS before?

**Comment by stfnhrrs** [comment] 2016-10-02 15:19
It works in regular chrome.

**Comment by 9Morello** [comment] 2016-10-02 15:59
@Eloston I haven't. I'll try it as soon as I can.

**Comment by Silencebound** [comment] 2016-10-10 02:05
Hello, i seem to have the same issue on the lastest Windows build. Netflix doesn't work.
Running Windows 7.
![ungoogled](https://cloud.githubusercontent.com/assets/22735373/19225527/95fbf40c-8e74-11e6-9140-9113151828fd.PNG)

**Comment by Eloston** [comment] 2016-10-10 07:39
Can anyone else confirm that this doesn't work on Windows? I haven't had time to test this on Linux, so if someone could try that too that would help.

**Comment by altblitz** [comment] 2016-10-10 22:30
[Shaka](http://shaka-player-demo.appspot.com/demo/) player provides platform independent tool to check Widevine plugin.

Chromium Version 53.0.2785.144 (64-bit) on Linux 4.7.5 x86_64 works partially.
On the video "Angel (Widevine)" audio/video channels work for 11 sec, then stop.

> Shaka Error DRM.LICENSE_REQUEST_FAILED (shaka.util.Error { "category": 1, "code": 1001, "data": [ "http://widevine-proxy.appspot.com/proxy", 400, "Empty Request" ], "message": "Shaka Error NETWORK.BAD_HTTP_STATUS (http://widevine-proxy.appspot.com/proxy,400,Empty Request)", "stack": "Error: Shaka Error NETWORK.BAD_HTTP_STATUS (http://widevine-proxy.appspot.com/proxy,400,Empty Request)\n at new shaka.util.Error (http://shaka-player-demo.appspot.com/lib/util/error.js:77:13)\n at XMLHttpRequest.xhr.onload (http://shaka-player-demo.appspot.com/lib/net/http_plugin.js:68:16)" })

**Comment by Eloston** [comment] 2016-10-10 23:40
Hmm. I wonder if domain substitution is breaking the Widevine DRM checking. I'm guessing that you don't see an infobar show up when you attempt to use widevine?

**Comment by altblitz** [comment] 2016-10-11 16:01
Infobar doesn't appear when loading videoplayer demo site while using widevine drm libraries:
libwinedivinecdm.so and libwinedivinecdmadapter.so.

On 10th october during the test I was using libwinedivinecdm.so from 10/03/2016 and libwinedivinecdmadapter.so from 10/06/2016.
10/06/2016, it's when chromium 53.0.2785.144 (64-bit) and libwinedivinecdmadapter.so were compiled from source with iridium/inox/ungoogled patches.
Apparently libwinedivinecdm.so in /usr/lib/chromium came from another version of chromium-based browser week ago and caused partial stream playback.

Now it's replaced with libwinedivinecdm.so distributing with https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_53.0.2785.144-1_amd64.deb and audio/video doesn't stop after 11 sec.

Chromium playing video
`Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode` 
`tcp6       0      0 inode:59240             arn09s11-in-x11.1e100.net:443 ESTABLISHED 1000       407657`
`tcp6       0      0 inode:51360             arn09s11-in-x03.1e100.net:443 ESTABLISHED 1000       407290`
`tcp6       0      0 inode:43820             lg-in-x5f.1e100.net:443 ESTABLISHED 1000       407703` 
`tcp6     342      0 inode:43824             lg-in-x5f.1e100.net:443 ESTABLISHED 1000       407705`
`tcp6     342      0 inode:51362             arn09s11-in-x03.1e100.net:443 ESTABLISHED 1000       403345`
`tcp6     342      0 inode:43822             lg-in-x5f.1e100.net:443 ESTABLISHED 1000       407704`

Chromium build produces only libwinedivinecdmadapter.so adapter for libwinedivinecdm.so widevine cryptographic module. Module itself provides official chrome browser.

**Comment by Eloston** [comment] 2016-10-11 17:39
So it works properly on Linux, but not Windows or macOS? That's weird. This is probably not be a domain substitution problem then.

@chrme: Would you mind telling us what did you do to get Widevine to work in your Windows builds? Do you know if it works on macOS?

**Comment by 9Morello** [comment] 2016-11-03 18:34
@henrypp Sorry to bother you, but can you help us with this?

**Comment by 9Morello** [comment] 2016-11-05 22:39
@Eloston does the Windows and OS X builds use the `enable_widevine = true` flag?

**Comment by Eloston** [comment] 2016-11-06 00:06
@9Morello Is that a GN flag? I'm still on GYP. Though I'm probably going to switch in ungoogled-chromium 54 or 55.

**Comment by 9Morello** [comment] 2016-11-06 00:10
I'm not sure, I saw it in [this comment](https://chromium.woolyss.com/#comment-1500).
According to [this other comment](https://bugs.chromium.org/p/chromium/issues/detail?id=429452#c34), its a GYP flag.

**Comment by Eloston** [comment] 2016-11-06 00:23
Huh. You know, it would probably be a good idea to enable that flag.

**Comment by 9Morello** [comment] 2016-11-06 00:31
I'll try building and testing with the tool from [this comment](https://github.com/Eloston/ungoogled-chromium/issues/73#issuecomment-252763361) and see if it works.

**Comment by Eloston** [comment] 2016-11-06 00:32
@9Morello Sounds good. Thanks.

**Comment by 9Morello** [comment] 2016-11-06 11:25
Compiled with it and saw no difference. The widevine plugin still doesn't appear on `chrome://components` or `chrome://plugins`. I cannot select the widevine videos on the site to test them.

**Comment by Eloston** [comment] 2016-11-06 20:35
@9Morello Well that sucks. I guess the investigation continues...

**Comment by 9Morello** [comment] 2016-11-07 16:31
Ok, I've found some clues.
Adding the `enable_widevine=1` flag actually made it compile the Widevine plugin components. They just weren't added to the `Chromium.app` package for some reason. The files `libwidevinecdm.dylib` and `widevinecdmadapter.plugin` are inside the `/out` folder. I tested them and they work, enabling playback on that test site as well on Netflix.

However, a `manifest.json` file is also required  for Widevine and, for some reason, it isn't being build. I discovered this by downloading Google Chrome and looking into their `.app` folder. There, I found the 2 Widevine files plus the `manifest.json`.

On OS X, you can get Widevine support on ungoogled-chromium by doing this:
1) Create a file with the name `manifest.json` and the following contents:

```
{
  "manifest_version": 2,
  "update_url": "https://clients2.google.com/service/update2/crx",
  "name": "WidevineCdm",
  "description": "Widevine Content Decryption Module",
  "offline_enabled": false,
  "version": "1.4.8.903",
  "minimum_chrome_version": "47.0.2526.0",
  "x-cdm-module-versions": "4",
  "x-cdm-interface-versions": "8",
  "x-cdm-host-versions": "8",
  "x-cdm-codecs": "vp8,vp9.0,avc1",
  "icons": {
    "16": "imgs/icon-128x128.png",
    "128": "imgs/icon-128x128.png"
  },
  "platforms": [
    {
      "os": "win",
      "arch": "x86",
      "sub_package_path": "_platform_specific/win_x86/"
    },
    {
      "os": "win",
      "arch": "x64",
      "sub_package_path": "_platform_specific/win_x64/"
    },
    {
      "os": "mac",
      "arch": "x86",
      "sub_package_path": "_platform_specific/mac_x86/"
    },
    {
      "os": "mac",
      "arch": "x64",
      "sub_package_path": "_platform_specific/mac_x64/"
    }
  ]
}
```


2) Get inside your `Chromium.app` package, and go to `Contents/Versions/your_chromium_version/Chromium Framework.framework/`
3) Create a `Libraries` folder there
4) Inside it, paste the `WidevineCdm `folder from the `/out` folder.
5) Put the `manifest.json` inside the `WidevineCdm` folder.

It should work now. Alternatively, you can just download Chrome and copy the Libraries folder from their package - it also works, even if the Chromium and Chrome versions don't match.
Putting these files inside a `Chromium.app` package that was built without the `enable_widevine=1` flag doesn't work.

The Windows/Linux builds might be getting similar behavior (`widevinecdm.dll`/`libwidevinecdm.so` files left in the out folder without being used). We probably can get Widevine support in a similar way with them.

**Comment by Eloston** [comment] 2016-11-07 19:11
You have `libwidevinecdm.dylib`? That's weird. We don't have the source code to that library, which means it must have downloaded while it's building. Only the widevinecdmadapter library is built.

BTW, I scanned the GYP file and it seems that the manifest.json file is also provided before the build starts. So it seems we're only supposed to have the widevinecdmadapter library.

**Comment by 9Morello** [comment] 2016-11-07 19:37
Yes, I have libwidevinecdm.dylib. Its probably as you said.
Its fine by me to wait. Are we going to get any other release before the switch to GN?

**Comment by Eloston** [comment] 2016-11-07 19:51
I'm still deciding how to do this transition. Windows and Mac are the only platforms where GYP is becoming a bit troublesome, with bugs #89 and #60, respectively. Linux will be a lot more work due to the use of multiple flags not available in GN and heavy modifications to build against system libraries. So I might switch Windows and Mac to GN before another release, and wait until later to switch Linux over.

Right now, inox-patchset is holding back the update to 54. Though I will try to squeeze in time this weekend to update the necessary patches to GN.

**Comment by 9Morello** [comment] 2016-11-07 22:56
Okay.
Any clues on why those 2 files are not being moved to the `Chromium.app` package?

**Comment by Eloston** [comment] 2016-11-07 23:30
Not entirely sure since the for packaging is unique for Mac, but it's more than likely related to the differences in behavior when using Chromium instead of Chrome for branding.

**Comment by lewdnasty** [comment] 2016-11-11 08:28
![chrome_2016-11-11_02-27-27](https://cloud.githubusercontent.com/assets/4476501/20208868/7c5cf5f4-a7b6-11e6-8b72-b5bdcc31f4eb.png)

Windows 7 user, latest release. Same error as OP.

**Comment by Eloston** [comment] 2016-12-01 03:49
@lewdnasty I didn't enable Widevine properly in the Windows build published on GitHub. Once I get version 54 to build on Windows, then we can start testing.

@9Morello Does the new version 54 build you made still miss those files?

**Comment by 9Morello** [comment] 2016-12-01 03:59
@Eloston Yes, the files are still missing. They weren't even downloaded, as they're also missing from the `/out/Release` folder.

**Comment by Eloston** [comment] 2016-12-01 04:16
@9Morello Alright. I have widevine files in my output directory, but they give me the same error [as in this comment](https://github.com/Eloston/ungoogled-chromium/issues/73#issuecomment-252763361). So it seems that switching to GN has no effect on this issue.

**Comment by gcarq** [comment] 2016-12-15 11:07
@9Morello, @Eloston: `enable_widevine=1` just enables the support for widevine. You need `libwidevinecdm.so` is in the browsers working directory (at least for linux). If you have a local chromium installation where widevine works you can symlink it. I created a section in the README for this: https://github.com/gcarq/inox-patchset#use-widevine. Tested with ArchLinux and Netflix.

**Comment by 9Morello** [comment] 2016-12-15 14:58
@gcarq Thanks for replying. In OS X's case, the `libwidevinecdm.dylib` file is created and placed in the correct folder inside the `Chromium.app` package, but for some reason its broken. Its smaller than the one Chrome provides (1.4MB vs 5.2MB)

Replacing it with Google Chrome's `libwidevinecdm.dylib` fixes the problem.

**Comment by Eloston** [comment] 2016-12-15 20:29
@gcarq Thanks for your input. [altblitz got Widevine to work just fine on Linux](https://github.com/Eloston/ungoogled-chromium/issues/73#issuecomment-252962092) doing exactly what you said.

@9Morello On Linux, a stub version of `libwidevinecdm.so` is built. I'm assuming Windows and macOS have the same behavior (but have their respective file names). It's not broken, it's just a dummy placeholder. You will always need to get the official library from Chrome, unless they miraculously release the source code. Also, I am fairly confident the dummy binary is not being downloaded from the web, because the source code's referenced from the GN configuration (and domain substitution would've broken it anyway)

**Comment by 9Morello** [comment] 2016-12-15 20:45
@Eloston Thanks for clarifying. I'm going to upload the new OS X binaries now.

**Comment by pjv** [comment] 2016-12-20 13:07
@9Morello If those OS X binaries that are widevine compatible are available somewhere, I can't find them. Only thing I see on the uploads page is version 55.0.2883.75-1, no 87-1.

**Comment by 9Morello** [comment] 2016-12-20 14:38
@pjv https://github.com/ungoogled-software/ungoogled-chromium-binaries/releases/tag/55.0.2883.95

**Comment by pjv** [comment] 2016-12-20 14:50
@9Morello  Thanks!

**Comment by Eloston** [comment] 2016-12-20 20:45
> Only thing I see on the uploads page is version 55.0.2883.75-1, no 87-1.

Looks like I need to make the link bigger.

**Comment by pjv** [comment] 2016-12-20 20:49
> Looks like I need to make the link bigger.

Actually, i think you are linking to the wrong 3rd page releases page from the main releases page. Or that 3rd party page needs to be updated to include @9Morello's newer builds here: https://github.com/ungoogled-software/ungoogled-chromium-binaries/releases/tag/55.0.2883.95

**Comment by Eloston** [comment] 2016-12-20 20:50
@pjv Ah. Yeah looks like @9Morello forgot to update all of the references. Going to fix it right now.

**Comment by 9Morello** [comment] 2016-12-21 00:45
@pjv @Eloston Whoops, my bad.

**Comment by Zegnat** [comment] 2016-12-25 17:16
> > Only thing I see on the uploads page is version 55.0.2883.75-1, no 87-1.
> 
> Looks like I need to make the link bigger.

@Eloston will you no longer be including any macOS builds from now on? Because then [the eloston-chromium formula](https://github.com/caskroom/homebrew-cask/blob/master/Casks/eloston-chromium.rb) for Homebrew Cask should be updated to point at @9Morello’s builds. I don’t mind doing that, but if the next version will be on this repo again, I don’t really see the point.

**Comment by Eloston** [comment] 2016-12-25 20:35
@Zegnat With the new download page design, you should be [reading files from here](https://github.com/ungoogled-software/ungoogled-chromium-binaries/tree/master/config/platforms/macos). There is no guarantee as to where macOS binary files will reside, but the downloads webpage should be using that configuration file format for a while.

**Comment by Eloston** [comment] 2016-12-30 07:51
Now that Widevine support builds on all of the platforms, we should probably add some instructions to the FAQ to let users know how to install the module. I will take care of the instructions for Linux.

**Comment by DeadSix27** [comment] 2016-12-30 08:45
@Eloston I saw he does. I like his idea. But if we offer that, we should also offer LKGR, if nojmp helps to keep the patches up to date.

**Comment by pjv** [comment] 2016-12-30 10:42
@Eloston @9Morello Instructions for widevine for macos would be appreciated. I think I have actually done what's needed -- copied the `WidevineCDM` directory from `~/Library/Application Support/Google/Chrome/WidevineCDM` to `~/Library/Application Support/Chromium/WidevineCDM` -- but it is not working for me, even though chromium is registering that it is there in `chrome://components/`. 

I tried clicking the "Check for update" button, and I get "Component not updated"
![2016-12-30 at 4 40 am](https://cloud.githubusercontent.com/assets/327716/21563702/4573ba2c-ce4a-11e6-87d7-204d7f5e0624.png)

**Comment by 9Morello** [comment] 2016-12-30 13:35
@pjv Put the latest `Google Chrome.app` and the `Chromium.app` in the same folder. Open than folder in the terminal and run this:

`cp -R Google\ Chrome.app/Contents/Versions/55.0.2883.95/Google\ Chrome\ Framework.framework/Libraries/WidevineCdm Chromium.app/Contents/Versions/55.0.2883.95/Chromium\ Framework.framework/Libraries/`

**Comment by pjv** [comment] 2016-12-30 13:50
@9Morello Finally. - Thanks!

**Comment by Eloston** [comment] 2017-01-26 01:02
Closing now, since this bug seems to be resolved.

**Closed by Eloston** 2017-01-26 01:02 UTC
Labels: bug, help wanted

**Comment by stfnhrrs** [comment] 2017-02-08 16:46
@Eloston Amazon Video still doesn't seem to work, please let me know if you'd like further help debugging this.

<img width="971" alt="screen shot 2017-02-08 at 11 46 02 am" src="https://cloud.githubusercontent.com/assets/1240279/22747168/408ea6ce-edf4-11e6-933f-b25dee5e159a.png">

**Comment by Eloston** [comment] 2017-02-10 19:24
@stfnhrrs I'm going to assume you're following the instructions in the FAQ.

What version of Google Chrome did you take the WidevineCdm files from?

**Comment by stfnhrrs** [comment] 2017-02-13 14:47
@Eloston I did follow the instructions, I'm using version 55.0.2883.95 of Google Chrome.

**Comment by Eloston** [comment] 2017-02-14 20:04
@stfnhrrs I'm not really sure what's going on. You're still on macOS, right?

**Comment by stfnhrrs** [comment] 2017-02-17 14:40
@Eloston yes MacOS 10.12.3 (16D32)

**Comment by Eloston** [comment] 2017-02-17 19:28
Any ideas @9Morello?

**Comment by 9Morello** [comment] 2017-02-18 16:43
@stfnhrrs could you please post a screenshot of your `about:plugins` page?

**Comment by stfnhrrs** [comment] 2017-02-28 15:23
@9Morello 
<img width="1142" alt="screen shot 2017-02-28 at 10 22 42 am" src="https://cloud.githubusercontent.com/assets/1240279/23411304/e306d34e-fd9f-11e6-918d-98c91acf698e.png">

**Comment by 9Morello** [comment] 2017-02-28 21:52
Did you follow [this post](https://github.com/Eloston/ungoogled-chromium/issues/73#issuecomment-269772331)'s instructions? It should be showing the correct version of Widevine.

**Comment by sbeh** [comment] 2019-02-18 13:45
I can confirm [this fix](https://github.com/Eloston/ungoogled-chromium/issues/73#issuecomment-269772331) just worked for me on Windows 10 and Chromium 72.0.3626.109

**Comment by wokawoka** [comment] 2019-02-18 14:10
@sbeh , thank you for contributing but I can't follow you, your links brings to a reply with a mac os fix, not a windows one. I'm trying to install widevine on 72.0.3626.109 under windows 10 and I would be very grateful if you can expand more. Many thanks

**Comment by sbeh** [comment] 2019-02-18 14:25
@wokawoka I installed Chrome into a VM and then copied `C:\Users\...\AppData\Local\Google\Chrome\Application\72.0.3626.109\WidevineCdm` into my ungoogled-chromium directory. Result was a previously not and now working Netflix ;)

**Comment by wokawoka** [comment] 2019-02-18 15:25
@sbeh, thanks, that's what I also previosly did but I forgot to close all the active windows in background (chromium needed a restart). Thank you very much again

**Comment by qkdreyer** [comment] 2019-10-01 09:55
This should be closed since the issue happen on each ungoogled-chromium update :(

**Comment by klauss194** [comment] 2021-11-12 18:04
Hey guys, What about linux ? Is there any guide for linux ?

**Comment by robigan** [comment] 2021-11-15 21:29
Hey, I seem to be having this issue on macOS Big Sur with the new M1, I am downloading it through homebrew so am using the builds @kramred provides. I am trying on Netflix and I do see the Widevine CDM module but apart from that I have no idea what to do and installing Chrome or Chromium to get the Widevine CDM binaries isn't good for me (if I am understanding from the above comments it's possible)

**Comment by arkoz** [comment] 2021-12-20 18:09
@klauss194 you can use `use-standalone-widevine.sh` from https://github.com/proprietary/chromium-widevine
works fine for me for months already, just need to re-run this from time to time to update module
