### ISSUE TITLE
[Windows] Crash when extensions access safebrowsing prefs 

### ISSUE THREAD

**Issue by squalus** [Eloston/ungoogled-chromium#395] opened 2018-04-20 07:22 UTC
Version: 65.0.3325.181-2

Either of these two lines cause the entire browser to crash when run by an extension:

```
chrome.privacy.services.safeBrowsingEnabled.get({}, function(x){})
chrome.privacy.services.safeBrowsingExtendedReportingEnabled.get({}, function(x){})
```

Maybe related to the changes in `windows-fix-building-without-safebrowsing.patch`

Issue was originally found by @ribatamu in https://github.com/Manvel/Privacy-Manager extension

**Comment by Eloston** [comment] 2018-04-20 08:11
I'm not getting this in my Debian v65 build, so it sounds more likely to be a Windows-only bug.

**Comment by intika** [comment] 2019-02-23 01:59
duplicate of https://github.com/Eloston/ungoogled-chromium/issues/619 ?
@Eloston

**Comment by Eloston** [comment] 2019-02-24 19:41
@intika No. This is a long-standing issue with the patches even in the latest Windows version available.

**Comment by Eloston** [comment] 2019-11-26 05:14
This should be fixed with 6cc874cfc8a250224811584f2c293dc61ec4faeb.

**Closed by Eloston** 2019-11-26 05:14 UTC
Labels: bug, help wanted
