### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by AlxMxlA** [Eloston/ungoogled-chromium#94] opened 2016-10-08 09:35 UTC
Can we expect a portable version ungoogled-chromium?

**Comment by wbedard** [comment] 2016-10-08 10:12
Please specify what OS you are looking for and/or what portable apps framework (i.e. portableapps.com) you are requesting.  In the case of Windows, the only release so far has been a ZIP file, which is generally regarding as very "portable."

**Comment by MichPCX** [comment] 2016-10-08 12:48
It would be good to have linux version of it too which would be portable. 
(GNU/Linux Debian 8 & Linux Arch)

**Comment by AlxMxlA** [comment] 2016-10-08 15:16
I'm looking for Windows.
By "portable"  I mean a program, which during operations does not extend beyond the directory where it was installed.

**Comment by the4anoni** [comment] 2016-10-08 15:34
Win32 version is portable :P

**Comment by AlxMxlA** [comment] 2016-10-08 21:44
No.
ungoogled-chromium_53.0.2785.116-1_win32.zip сreates a folder in the user profile.

**Comment by Eloston** [comment] 2016-10-08 22:10
You can use the `--user-data-dir` command-line switch to specify an alternate directory for the Chromium profile. You also probably don't want a disk cache since you want it to be portable, so you should set `--disk-cache-dir=nul` and `--disk-cache-size=0` and `--media-cache-size=0`.

**Comment by the4anoni** [comment] 2016-10-09 10:13
why you closed ?

**Comment by Eloston** [comment] 2016-10-09 19:54
@the4anoni Does my answer not answer @AlxMxlA's question?

**Comment by sergeevabc** [comment] 2017-06-14 10:17
Issue is not resolved, just a quick workaround was mentioned, which is not convinient.
We want a true portability right out the box without additional switches like other forks offer ([Cent][1], [Iron][2]).

[1]: https://www.centbrowser.com/history.html
[2]: http://www.srware.net/en/software_srware_iron_download.php

**Comment by Eloston** [comment] 2017-06-14 23:04
@sergeevabc 

So the Crashpad directory is created with ungoogled-chromium 55 on Windows?

For ease of launching in a portable mode, would a batch script suffice?

**Comment by sergeevabc** [comment] 2017-07-20 23:45
@Eloston, since you commit patches, I thought this behaviour could be changed internally as well.

**Comment by Eloston** [comment] 2017-07-21 00:02
@sergeevabc If there is some data that cannot be moved with command flags, then it will be worthwhile to add a patch to do so. I don't believe deviating from Chromium behavior just to make something more elegant is worth it; feel free to correct me otherwise.

**Comment by sergeevabc** [comment] 2017-07-21 00:46
Steps to reproduce:
1. Download and extract binary package for Windows ([this one][1], for example).
2. Launch ```chrome.exe --user-data-dir=profile --no-default-browser-check --disable-breakpad```.
Result: profile data is stored nearby, yet Chromium folder is created in %localappdata% as well.
Expected: everything is stored nearby.

The same question was [asked][1] once on Stackoverflow, with no resolution, alas.
So it seems there is no flag to use, so patch is the way to go.

[1]: https://superuser.com/questions/1140195/why-portable-chrome-creates-crashpad-directory-under-appdata

**Comment by Eloston** [comment] 2017-07-21 00:48
@sergeevabc The first link doesn't link to a download of Chrome or Chromium. I'm assuming that is a typo?

Also, does this happen with the v55 Windows build of ungoogled-chromium?

**Comment by sergeevabc** [comment] 2017-07-21 00:54
Yes.

**Comment by Eloston** [comment] 2017-11-25 17:45
This was fixed upstream, but the changes don't apply cleanly onto 62: https://bugs.chromium.org/p/chromium/issues/detail?id=565446

It's probably best to wait, so I'm closing this.

**Closed by Eloston** 2017-11-25 17:45 UTC
Labels: question

**Comment by t0ma5** [comment] 2023-01-17 19:46
Hi there, posting here 5+ years later about the same issue
Latest Windows portable version stores all profile info in %localappdata% and NOT in the same folder as the portable app, meaning it is not self contained. So if I move the portable win browser in an USB drive I lose my extensions, etc :(

**Comment by t0ma5** [comment] 2023-01-17 21:24
Sorry for reopening this 5 years later but the portable version (win) storing user data in a system folder is really annoying, the beauty of portable apps is to be self contained. Could someone please tell me what would be the right code to add to a shortcut launcher to fix this? --user-data-dir=/UserData
