### ISSUE TITLE
No option to style "reader mode"

### ISSUE THREAD

**Issue by methane4** [Eloston/ungoogled-chromium#1525] opened 2021-05-25 22:26 UTC
**Describe the bug**
There is no option to style on the "reader mode", change font, change colour.

**To Reproduce**
1. Enter Reader mode

**Expected behavior**
An icon to be displayed to then open a small menu

**Screenshots**
![Screenshot from 2021-05-25 23-24-38](https://user-images.githubusercontent.com/46012160/119576333-746b1280-bdb0-11eb-82d5-efb3c18ad04f.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Fedora 34
 - ungoogled-chromium version: 90.0.4430.212(stable) - flatpak

**Comment by wchen342** [comment] 2021-05-26 07:47
@rany2 Flatpak problem.

**Comment by rany2** [comment] 2021-05-26 09:08
@wchen342 Thanks!

@methane4 This is not a flatpak bug, I think it's an issue with ungoogled substitution/patches. There is an invisible option in the top right that you can't see. Click it and it will work:
![Screenshot_2021-05-26_12-07-20](https://user-images.githubusercontent.com/71077389/119634013-f98b1180-be1a-11eb-8708-e49ba28a7efe.png)
![Screenshot_2021-05-26_12-08-00](https://user-images.githubusercontent.com/71077389/119634068-06a80080-be1b-11eb-8ab2-cd817819bfd2.png)

**Comment by rany2** [comment] 2021-05-26 09:09
Duplicate of https://github.com/Eloston/ungoogled-chromium/issues/1221

**Comment by methane4** [comment] 2021-05-26 14:09
@rany2 yeah i confirm it works but its hidden, there is also other things missing like to configure the new tab.

**Comment by methane4** [comment] 2021-05-26 14:15
> Duplicate of #1221

however on #1221 it displays a character, maybe its missing a font?

**Comment by methane4** [comment] 2021-05-26 14:22
> there is also other things missing like to configure the new tab.
See #1515

**Comment by rany2** [comment] 2021-05-26 14:38
@methane4 Pretty sure #1515 applies to all Chromiums on Linux as well, regardless of flatpak

**Comment by rany2** [comment] 2021-05-26 14:39
oh wait, 
>  there is also other things missing like to configure the new tab.

what does that mean? like a new tab page?

**Comment by methane4** [comment] 2021-05-26 15:22
> oh wait,
> 
> > there is also other things missing like to configure the new tab.
> 
> what does that mean? like a new tab page?

theres a menu that you can change some things about the new tab, like the background, disable or change the icons. i wanted to disable the icons but i didnt find that menu. here is some photos i found online:
(there is also no encrypted dns options but its not related to this issue)


![](https://www.lifewire.com/thmb/K-gG9wA7-kpbwrUWGq963Veq3ZU=/1425x878/filters:no_upscale():max_bytes(150000):strip_icc()/2SelectCustomizeannotated-bcf7453d63734dc5bfacc5d5100344b4.jpg)


![](https://lisalouisecooke.com/wp-content/uploads/2019/10/upload-1.png)



![](https://mk0ghacksnety2pjrgh8.kinstacdn.com/wp-content/uploads/2019/05/google-chrome-new-tab-page-customize-2019.png)



![](https://www.cnet.com/a/img/qALfUh55dpeP9O4Jd3jEXq6x_ag=/940x0/2019/09/19/c1f819f9-aacf-4f49-ac80-8e6def7636e6/chrome-color-select-red.jpg)

**Comment by rany2** [comment] 2021-05-26 18:48
I think the customize thing is an issue with all UGCs not just the Flatpak distribution. I don't have a non-flatpak version at hand to check so maybe someone else can confirm?

**Comment by networkException** [comment] 2021-05-26 18:56
a newtab is just grey for me

**Comment by methane4** [comment] 2021-05-27 01:12
mine is just grey with icons on the middle, id like to disable them

**Comment by rany2** [comment] 2021-07-17 13:52
If you're on Linux you could run https://gist.github.com/rany2/1ca678ccb18b54391074f846bb7d222d to install Material Design Icons which fixes it:

![image](https://user-images.githubusercontent.com/71077389/126039192-c08f5485-d2dd-4262-ab8e-89a9249ef128.png)
![image](https://user-images.githubusercontent.com/71077389/126039198-f91e4a97-58bf-4fdf-816e-35f1959a1659.png)

**Comment by PF4Public** [comment] 2021-09-29 08:51
What is the status of this issue?

**Comment by rany2** [comment] 2021-09-29 13:36
@PF4Public I don't think I would consider this to be a bug. I think that the solution is to add the "Material Design Icons" font as a dependency for those that want to enable reader mode.

**Comment by PF4Public** [comment] 2021-10-02 09:22
@rany2 Thank you for summarizing it up!

I will close this issue then.

**Closed by PF4Public** 2021-10-02 09:22 UTC

**Comment by rany2** [comment] 2021-10-02 13:28
I've bundled Material Design Icons for Ungoogled Chromium users on Flatpak.  https://github.com/flathub/com.github.Eloston.UngoogledChromium/commit/f7ffa3579eb03e700ff7b0bb2dc210df7e56d87f
