### ISSUE TITLE
Problems with images on imdb.com

### ISSUE THREAD

**Issue by pmico** [Eloston/ungoogled-chromium#123] opened 2016-11-24 14:52 UTC
When I try to read something about any film on imdb.com images appear as broken links. I first thought perhaps adblock and ghostery extensions cause this error but I tried with firefox and google chrome with these extensions and there is no problems. Is it possible chromium ungoogled  be the cause ??
I'm using macOS Sierra and chromium ungoogled 53.0.2785.116 (64-bit).
Thanks for all.

**Comment by pmico** [comment] 2016-11-24 23:35
I found other sites with the same problems. It's always a problem with image links broken: amazon.es, images of phones like in http://www.htcmania.com/forumdisplay.php?f=1907, https://www.powerplanetonline.com/ ... 
In amazon and powerplanetonline, css seams do not work because html div are not shown, css fails too ...
It's very strange.

Right now in amazon there is an image about black friday that i can't see accessing directly to the web page, but if i copy the link to the image and try to open it in another tab, i can see this image.

Capture of web page:
![captura de pantalla 2016-11-25 a las 0 34 40](https://cloud.githubusercontent.com/assets/15140307/20611257/fa7c1b0e-b2a6-11e6-841f-adca968dec5c.png)


Capture of image in new tab:
![captura de pantalla 2016-11-25 a las 0 32 45](https://cloud.githubusercontent.com/assets/15140307/20611250/cdef5510-b2a6-11e6-863e-bce24c05531d.png)

**Comment by waqas** [comment] 2016-11-25 08:24
It's because of #119 . IMDb gets some images from https://images-na.ssl-images-amazon.com. I think it is already being worked on by releasing 54.

**Comment by pmico** [comment] 2016-11-25 09:08
Upss sorry ... I didn't read this entry ... I didn't think it is related to.
Thanks for the answer.
Eloston, you know you're doing a great job and we all really appreciate your efforts.

**Comment by Eloston** [comment] 2016-11-25 21:02
Thanks for the compliment @pmico :+1: 

Closing as duplicate of #119.

**Closed by Eloston** 2016-11-25 21:02 UTC
