### ISSUE TITLE
Spellcheck isn't working.

### ISSUE THREAD

**Issue by Innomen** [Eloston/ungoogled-chromium#793] opened 2019-07-11 18:41 UTC
Version 75.0.3770.90 (Official Build) (64-bit)

Nothing in the wiki about their either.

![Screenshot 2019-07-11 14_40_33-Search _ ungoogled-chromium Wiki - Chromium](https://user-images.githubusercontent.com/134324/61076338-ff73d700-a3e9-11e9-916d-0c878766c5b0.jpg)

**Comment by emanruse** [comment] 2019-07-13 10:04
It requires connection to Google.
If we could have myspell checking it would be possible to have spell check offline.

**Comment by Innomen** [comment] 2019-07-13 15:13
That disturbs me X) My old chromium offered a choice, and I told it no Google, I guess that means it tricked me and the choice was Google and Google lite XD

**Comment by Eloston** [comment] 2019-07-16 03:26
Duplicate of #188

**Closed by Eloston** 2019-07-16 03:26 UTC
