### ISSUE TITLE
Widevine does not work in ungoogled-chromium on linux even though it is installed

### ISSUE THREAD

**Issue by JimPix1** [Eloston/ungoogled-chromium#1827] opened 2022-02-04 17:35 UTC
I am using Arch Linux and I have downloaded Widevine (from Google Chrome and I have also tried chromium-widevine from the AUR) and placed it into /usr/lib/chromium but it doesn't work.
I have also made sure that libwidevinecdm.so had the correct permissions.
In Netflix I get this error
![image](https://user-images.githubusercontent.com/79943327/152575965-64a203ed-38e5-4019-bce4-7fa96c20c990.png)
Any idea on how to fix this?

Edit: I tried Firefox's Widevine which also doesn't work

**Comment by JimPix1** [comment] 2022-02-04 17:52
I get this when I try test-widevine.html
![image](https://user-images.githubusercontent.com/79943327/152578405-7831b3db-2a69-4b1f-abfa-14749120fb45.png)

**Comment by KHR3b** [comment] 2022-02-07 05:39
Same, also does not work on Firefox ESR

**Comment by PF4Public** [comment] 2022-04-10 11:13
Please see [this comment](https://github.com/Eloston/ungoogled-chromium/issues/1831#issuecomment-1076960806) it might be of help.

**Comment by JimPix1** [comment] 2022-04-10 11:29
Still doesn't work

**Comment by PF4Public** [comment] 2022-04-10 11:35
It must be a duplicate of #1566 then. Take note of [this comment](https://github.com/Eloston/ungoogled-chromium/issues/1566#issuecomment-879056903).

**Closed by PF4Public** 2022-04-10 11:35 UTC
Labels: need info
