### ISSUE TITLE
[ArchLinux] Provide "official" ungoogled-chromium-bin package

### ISSUE THREAD

**Issue by SuperITMan** [Eloston/ungoogled-chromium#1023] opened 2020-04-30 12:14 UTC
**Is your feature request related to a problem? Please describe.**

Yes, this feature relates to a problem.
Install of [ungoogled-chromium](https://aur.archlinux.org/packages/ungoogled-chromium/) via `yay` or `pamac` takes more than 4 hours because of build time on Manjaro.

The CPU usage is 100% (+- 80% used by `clang++`) during the build time.

**Describe the solution you'd like**

In the README, a link is provided to download binaries: https://ungoogled-software.github.io/ungoogled-chromium-binaries/ 

We should create a package supported by community based on this binary. It would save hours for lots of people :smiley: 

**Describe alternatives you've considered**

No real alternative except, maybe, buying a new and more powerful computer to build `ungoogled-chromium` ? :stuck_out_tongue: 

**Additional context**

A package `ungoogled-chromium-bin` exists already but has been removed yesterday by Arch Linux team. I contacted the person to ask him why he removed the package. I'm waiting for his answer :blush: 

Nevertheless, if the package is available again, I think it could be mentioned in the [README.md](https://github.com/Eloston/ungoogled-chromium/blob/master/README.md)

EDIT:

I re-enabled the package [ungoogled-chromium-bin](https://aur.archlinux.org/packages/ungoogled-chromium-bin/) but I guess it could be removed again since there is no apparent link between [Eloston/ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium) 
and [zocker-160/ungoogled-chromium-binaries](https://github.com/zocker-160/ungoogled-chromium-binaries)... Maybe it would be nice to provide the binaries in an "official" repo related to this one. What do you think ? :blush:

**Comment by mbakke** [comment] 2020-04-30 13:23
> No real alternative except, maybe, buying a new and more powerful computer to build `ungoogled-chromium` ?

You could install [GNU Guix](https://guix.gnu.org/) (I believe it's in AUR) and use that to install ungoogled-chromium.  It has the additional benefit of being verifiably reproducible, not needing root privileges to install/update, and the ability to roll back to any previous version.

Guix can be used on top of any GNU/Linux distribution and won't conflict with your native package manager.

**Comment by kevinlekiller** [comment] 2020-04-30 14:36
There's a few user repositories that provide buildes for ungoogled chromium, chaotic-aur for example:

https://wiki.archlinux.org/index.php/Unofficial_user_repositories#chaotic-aur

**Comment by SuperITMan** [comment] 2020-04-30 14:38
@mbakke I don't think using Guix besides pacman/yay is a good idea. 
I prefer to only use the package manager of my distro :blush: 

@kevinlekiller I didn't know those other unofficial user repositories. I'll have a look.
Thanks for sharing! :+1:

**Comment by kevinlekiller** [comment] 2020-04-30 14:41
No worries, see "How to use it?" on https://lonewolf.pedrohlc.com/chaotic-aur/

**Comment by braewoods** [comment] 2020-05-02 16:45
We are already planning some kind of solution that involves using OBS to build for Arch but we are currently stalled with some general build issues we are having. If anyone cares to help investigate them the official repository is here: https://github.com/ungoogled-software/ungoogled-chromium-archlinux.git

**Comment by Ph0rk0z** [comment] 2020-05-05 00:54
Chaoitc already builds this so why not just point it at them? I first downloaded a version from "binaries" on here and it failed because libraries in arch updated. There was no way to fix it.

**Comment by codiflow** [comment] 2020-07-27 10:36
The way using chaotic-aur's repo worked like a charm!

**Comment by PF4Public** [comment] 2021-09-25 12:47
Closing this issue in favour of ungoogled-software/ungoogled-chromium-archlinux#143

**Closed by PF4Public** 2021-09-25 12:47 UTC
Labels: enhancement
