### ISSUE TITLE
Alternative installation methods

### ISSUE THREAD

**Issue by FMR-R4** [Eloston/ungoogled-chromium#358] opened 2018-03-19 01:36 UTC
Hi,
Could you provide alternative installation methods in order to be compatible with more distributions like SolusOS?
-Appimage
-Snap
-Flatpak

One of the three would already be marvelous.
Thx.

**Comment by Eloston** [comment] 2018-03-19 06:19
Duplicate of #36

**Closed by Eloston** 2018-03-19 06:19 UTC
