### ISSUE TITLE
Provide an AppImage for Linux distributions

### ISSUE THREAD

**Issue by Serkan-devel** [Eloston/ungoogled-chromium#231] opened 2017-05-20 09:57 UTC
(Based off of https://github.com/MrAlex94/Waterfox/issues/127)

Providing an <a href="http://appimage.org/">AppImage</a> would have, among others, these advantages:

- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, <a href="http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80">make it executable</a>, and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

<a href="https://github.com/probonopd/AppImageKit/wiki/AppImages">Here is an overview</a> of projects that are already distributing upstream-provided, official AppImages.

It might be great if this project could make use of it.

**Comment by Eloston** [comment] 2017-05-21 19:46
Duplicate of #36.

**Closed by Eloston** 2017-05-21 19:47 UTC
