### ISSUE TITLE
Linux Portable version 67:  drag-and-dropping extensions fail

### ISSUE THREAD

**Issue by jlj2** [Eloston/ungoogled-chromium#423] opened 2018-06-14 23:21 UTC
Using Linux portable version 67 of **ungoogled-chromium** on an up-to-date Calculate Linux (gentoo) installation, once chrome extensions are downloaded into a folder to be installed as per the method suggested in the [FAQs](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-from-the-chrome-webstore), they could not then be dragged successfully into the _Extensions_ tab in ungoogled-chromium.

That version was downloaded from the https://github.com/Eloston/ungoogled-chromium/issues/414#issuecomment-393972620 to `/tmp`, untarred and moved to `/opt/bin` without changing permissions or ownership:
`tar -xvf ungoogled-chromium_67.0.3396.62-1_linux.tar.xz`
 
`sudo cp -r ungoogled-chromium_67.0.3396.62-1_linux /opt/bin/`

The directory was renamed (optional):

`sudo mv /opt/bin/ungoogled-chromium_67.0.3396.62-1_linux/ /opt/bin/ungoogled-chromium/`

Attempting to drag and drop into the Extensions tab produces error message in tab:  _'Apps, extensions, and user scripts cannot be added from this website'_.

Is this an unfortunate development with Chrome/Chromium upstream?  Are developers not appreciating ungoogled-chromium and like derivatives?

A workaround to install extensions was successful for **Dark Night Mode** extension but failed in part on first attempt and did not load during the following session with the only other extension tried - **HTTPS Everywhere**:
1. Rename the extension's extension (in other words, its suffix) from .crx to say .zip 
2. Unzip the file into another folder, say, `unpackedextensionNo1` to keep the zip file and its contents separate
3. Open Extensions tab in ungoogled-chromium
4. In ungoogled-chromium's Extensions tab, turn on _Developer mode_
5. Click on _LOAD UNPACKED_
6. Navigate to folder and select it (Click on _Open_) to install.

**Comment by Eloston** [comment] 2018-06-16 06:27
If you're still having this issue, please let me know so we can investigate further.

**Comment by jlj2** [comment] 2018-06-17 04:13
The steps described in your entry are correct. 

Employing those steps in this installation, dragging and dropping the Disable HTML5 Autoplay extension using the Extension ID from [this URL](https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai) also generates the error described above.

A 'Learn more' link is now noted across from the error message;  it opens a tab announcing:
_"support.9oo91e.qjz9zk is blocked
Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT"_


The only enabled extensions are **Chromium PDF Viewer** and **CryptoTokenExtension**, as supplied by default in ungoogled-chromium, and their 'enable' switch is greyed out.  The **Dark Night Mode** extension was installed but disabled.

For reference, ungoogled-chromium is launched from jwm window manager tray launcher using the following path:
`/opt/bin/ungoogled-chromium/chrome-wrapper`

The chrome://sandbox/ tab reports as follows:-
_Sandbox Status
SUID Sandbox	No
Namespace Sandbox	Yes
PID namespaces	Yes
Network namespaces	Yes
Seccomp-BPF sandbox	Yes
Seccomp-BPF sandbox supports TSYNC	Yes
Yama LSM Enforcing	No
You are adequately sandboxed._

When launched from a shell and with Dark Night Mode -- the only working added extension -- disabled beforehand, errors appear:
```
$ sh /opt/bin/ungoogled-chromium/chrome-wrapper
[12760:12760:0616/235536.824264:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
[12688:12738:0616/235540.216479:ERROR:url_request.cc(590)] Block URL in URLRequest: https://support.9oo91e.qjz9zk/chrome_webstore/?p=crx_warning
[12688:12738:0616/235540.216699:ERROR:trk_protocol_handler.cc(17)] Blocked URL in TrkProtocolHandler: trk:https://support.9oo91e.qjz9zk/chrome_webstore/?p=crx_warning
[12688:12738:0616/235540.670398:ERROR:url_request.cc(590)] Block URL in URLRequest: https://support.9oo91e.qjz9zk/chrome_webstore/?p=crx_warning
[12688:12738:0616/235540.670909:ERROR:trk_protocol_handler.cc(17)] Blocked URL in TrkProtocolHandler: trk:https://support.9oo91e.qjz9zk/chrome_webstore/?p=crx_warning
[12688:12738:0616/235540.800051:ERROR:url_request.cc(590)] Block URL in URLRequest: https://support.9oo91e.qjz9zk/chrome_webstore/?p=crx_warning
[12688:12738:0616/235540.800279:ERROR:trk_protocol_handler.cc(17)] Blocked URL in TrkProtocolHandler: trk:https://support.9oo91e.qjz9zk/chrome_webstore/?p=crx_warning
```

**Comment by Eloston** [comment] 2018-06-17 05:19
What happens if you call `chrome` directly without using `chrome-wrapper`?

**Comment by jlj2** [comment] 2018-06-17 07:06
Update 1:  The newer Linux Portable build of 67.0.3396.87-1 has now been installed (NB:  earlier version was left installed at `/opt/bin/ungoogled-chromium`).


Update 2:  The 'Block URL in URLRequest' error messages reported lately seem to have been due to the duplicate tabs (https://support.9oo91e.qjz9zk/chrome_webstore/?p=crx_warning) that were left opened after clicking on the 'Learn more' link mentioned above upon attempting to install various extensions.  After closing those tabs in the new build, there is just the following error at launch:
```
$ sh /opt/bin/ungoogled-chromium_67.0.3396.87-1_linux/chrome-wrapper 
[6356:6356:0617/025101.558665:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
```

However, the  Disable HTML5 Autoplay extension still generates the same error and 'Learn more' report.

Reply to question:  With a clean profile (renaming ~/chromium to ~/chromiumoriginal) in the new build it launches as follows:
```
$ sh /opt/bin/ungoogled-chromium_67.0.3396.87-1_linux/chrome-wrapper 
[7511:7511:0617/025544.604522:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
```

The same error occurs when trying to install the Disable HTML5 Autoplay extension in the new build with a new profile.

Reply to other question:  Attempting to launch (deleting new profile again) using chrome instead of chrome-wrapper: 
```
 $ sh /opt/bin/ungoogled-chromium_67.0.3396.87-1_linux/chrome
/opt/bin/ungoogled-chromium_67.0.3396.87-1_linux/chrome: /opt/bin/ungoogled-chromium_67.0.3396.87-1_linux/chrome: cannot execute binary file
```

**Comment by Eloston** [comment] 2018-06-17 11:03
A few things:
* `chrome` is an ELF binary, not a shell script. Also, you don't need to invoke either `chrome` or `chrome-wrapper` with sh since they should both have the execute bit set in the filesystem.
* The "Learn more" link is a constant URL from the browser. It is expected to break due to domain substitution. The page it leads to and the "Block URL in" are due to the patch `block-trk-and-subdomains.patch`, not due to any extension as the page suggests.
* The `InitializeSandbox()` error may be due to some incompatibility with your Linux kernel. I don't see anything abnormal in `chrome://sandbox` that could cause this. However, I don't know if this error will affect anything either; you could check and see what `chrome://gpu` says.

On second thought, I don't think `chrome-wrapper` is the cause of your problem. I don't see it setting any runtime flags remotely related (note `chrome-wrapper` is a shell script that invokes `chrome` at the end).

While you are dragging the `.crx` file from your file manager into the `chrome://extensions` page, do you see an overlay with a dark puzzle piece icon and the text `Drop to install`? The only reason I can think of that Chromium creates the error `Apps, extensions, and user scripts cannot be added from this website` the thing being dragged and drop from your file manager is a URL instead of a filesystem path for some reason.

**Comment by jlj2** [comment] 2018-06-17 21:56
ANSWER No. 1 -  Thank you for the pointers re no need to use `sh` here and about the 'Learn more' link, etc.  Thank you also for your suggestion to examine the `chrome://gpu` report in order to determine what possibly may be an incompatibility with the kernel.  I don't know how to interpret it however and don't know if it is advisable to paste it publicly e.g. in pastebin, but the following sections or lines with entries that mostly appear in red:

_**Graphics Feature Status**
[...]
CheckerImaging: Disabled
[...]
Video Decode: Unavailable
Viz Service Display Compositor: Disabled
[...]_

_**Problems Detected**_
_- Accelerated video decode is unavailable on Linux: 137247_
_- Disabled Features: accelerated_video_decode_
[NB:  Other entries appear here including, for example, the following two first lines, but no entries have any red, and 'Applied Workarounds' are mentioned in all those cases:]
_* Clear uniforms before first program use on all platforms: 124764, 349137
   Applied Workarounds: clear_uniforms_before_first_program_use_
_[...]_

_* Don't expose disjoint_timer_query extensions to WebGL: 808744_
_* Native GpuMemoryBuffers have been disabled, either via about:flags or command line._
   _Disabled Features: native_gpu_memory_buffers_
_* Viz service display compositor is not enabled by default._
   _Disabled Features: viz_display_compositor_
_* Checker-imaging has been disabled via finch trial or the command line._
   _Disabled Features: checker_imaging_

ANSWER No. 2 - There is no 'dark puzzle piece icon' nor the text 'Drop to install' when drag-and-dropping the .crx extension.  When drag-and-dropping the extension from within the Thunar file manager, the pointer becomes an icon resembling a hand grabbing a white 'file' with a 'plus' sign .  The system had XFCE  installed as the default desktop environment.  I then installed jwm window manager, and that is the chosen window manager at login, so technically, I don't know what the desktop environment is.
Notes: 
* The suspicion that Chromium considers .crx to be an URL to download when dragged-and-dropped, and not a file, could be spot on!   When drag-and-dropping it, a 'Downloads status bar' appears (peculiarly?) at the bottom, including a 'Show all' button on the right, typical of when Chromium downloads items from URLs, and the .crx extension appears to be 'downloading' with a spinning circle and flashing when finished 'downloading' from a local folder.  
* When drag-and-dropping from SpaceFM file manager within jwm:  often, the drag-and-dropping fails as the SpaceFM mysteriously vanishes from screen and Chromium doesn't even report any .crx file 'downloading' (an issue for SpaceFM?).  However, even when the drag-and-drop engages correctly, the same error message, 'Downloads' status bar and the same 'hand, file and plus sign' icon appear.
* When drag-and-dropping from Thunar file manager during an XFCE window manager session (instead of choosing JWM window manager at the display manager login):  the same error message, 'Downloads' status bar and rather an icon resembling a file with a plus sign and two 'image-cropping' edges appear.
* When drag-and-dropping from SpaceFM file manager during an XFCE window manager session (not JWM):   sometimes the drag-and-dropping fails because, as in JWM sometimes, the SpaceFM vanishes from screen and Chromium doesn't even report any .crx file 'downloading', as has happened in JWM.  When the drag-and-dropping engages correctly, the same error message, 'Downloads' status bar and an icon resembling a file with a plus sign and two 'image-cropping' edges appear.

If Chromium should be set not to 'download' .crx from an URL, maybe a MIME setting was changed or could be changed?

**Comment by xsmile** [comment] 2018-06-17 22:50
@jlj2 To clarify - in hope that my suspicion is true - as I use XFCE with Thunar and the results should be the same. Do you drag the extension to the address bar or to the page?

> When drag-and-dropping the extension from within the Thunar file manager, the pointer becomes an icon resembling a hand grabbing a white 'file' with a 'plus' sign .

That pointer appears when dragging a .crx file to the address bar or to any page except chrome://extensions. When dragging it to the chrome://extensions page, you should see an arrow pointing upwards instead of the plus sign and a grey overlay covering the whole page as mentioned by Eloston.

Does an unmodified Chromium version show the same behavior or it is specific to Ungoogled Chromium?

**Comment by jlj2** [comment] 2018-06-19 02:50
@xsmile, I have been drag-and-dropping onto the page, not to the address bar.  

Further to your proposal, "Chromium Version 67.0.3396.62 (Developer Build) (64-bit)" was installed from the repositories on my system.  The Extensions page does not 'grey out' when drag-and-dropping an extension there.  Unlike all Portable build versions of ungoogled-chromium (v66 and v67) on this installation, a bar appears at the bottom announcing instead, "Extensions, apps and themes can damage your computer.  Are you sure you want to continue?"  If "Continue" is clicked, the bar doubles as the 'Downloads' bar mentioned earlier, and the extension seems to 'download', but does not install, which is odd because I have succeeded in previous Calculate Linux installations, and with **ungoogle-chromium** v55 from its repositories.

Here is a screenshot in Chromium v67 having dragged-and-dropped an extension earlier (to display the bar that appeared), and while repeating the action (to show no greyed-out area):
![drag-and-dropping extensions fail - 14 6 2018 - screenshot1b with chromiumv67](https://user-images.githubusercontent.com/17560937/41573225-a3c72bb8-7349-11e8-8591-b88710bc6dca.png)

Here is a screenshot in ungoogled-chromium_67.0.3396.87-1_linux Portable Build (disregard the .crx55 file in the file manager, it is an old .crx file for v55):
![drag-and-dropping extensions fail - 14 6 2018 - screenshot2b with v67](https://user-images.githubusercontent.com/17560937/41573237-b0d2ce48-7349-11e8-90fe-1507f93b28c8.png)

Here is a screenshot in ungoogled-chromium_66.0.3359.139-1_linux Portable Build;  it greys out ok and extensions would load fine:
![drag-and-dropping extensions fail - 14 6 2018 - screenshot3b with v66](https://user-images.githubusercontent.com/17560937/41573243-ba4ba062-7349-11e8-9733-1e62b41020f4.png)


@xsmile, have you installed Linux Portable build of ungoogled-chromium v67 in your XFCE environment?  If so, does drag-and-dropping extensions work ok in that Portable build?   Would you kindly indicate why you have a fork of ungoogled-chromium in your repositories?  Thank you, all.

**Comment by ribatamu** [comment] 2018-06-19 08:30
@jlj2 tried to disabled the flag at chrome://flags/#enable-md-extensions

I think that will solved your problem.

**Comment by xsmile** [comment] 2018-06-19 10:30
@jlj2 Dragging extensions in the portable build of 67.0.3396.87-1 does not work for me either. It behaves exactly the way that you described.

Following ribatamu's suggestion works. The old extension page allows extensions to be installed.

I believe I figured out the issue. Try enabling _Developer Mode_ in the top right corner of the extensions page. Afterwards dragging .crx files should work with the Chromium version of your distribution as well as with the portable version of Ungoogled Chromium.

The fork is used to submit pull requests to the original repository, usually for updating patches when a new Chromium version is released.

**Comment by Eloston** [comment] 2018-06-19 13:54
> I believe I figured out the issue. Try enabling Developer Mode in the top right corner of the extensions page. Afterwards dragging .crx files should work with the Chromium version of your distribution as well as with the portable version of Ungoogled Chromium. Most probably this change was introduced with version 67.

Ah, I forgot about the Developer Mode switch. I've always had it enabled. Good catch.

I'm wondering what the rationale is for the removal; if it's for some security reasons, there's already a confirmation box to install the extension. Also, it's frustrating and odd that there wasn't any error added in place of the decision to disable drag-and-dropping when not in Developer Mode; optimistically this could be a bug, but I feel like the use cases for drag-and-dropping CRX files is small enough that Google didn't bother to write any sort of notification.

Marking as invalid since this isn't an issue with ungoogled-chromium. I'll modify the Wiki to include a notice about this.

**Closed by Eloston** 2018-06-19 13:54 UTC
Labels: bug

**Comment by jlj2** [comment] 2018-06-21 00:42
@ribatamu, setting "Enable Material Design extensions" flag to 'Disabled' works indeed, thank you very much!

@xsmile, setting Extensions tab to 'Developer mode' also works when drag-and-dropping, thank you!

Thanks for all the other information!
