### ISSUE TITLE
building fails on windows10 

### ISSUE THREAD

**Issue by luckysunfd** [Eloston/ungoogled-chromium#713] opened 2019-03-21 16:52 UTC
### Description

env:
windows 10 x64 10GB memory

python -> python2.7.16  x64
py -> [python3.5.x | python3.7.x | python3.6.x ]  x64

### Console output and logs

run py build.py  

2019-03-21 22:39:01,639 - INFO: * Applying chromium-exclude_unwind_tables.patch (1/123)
2019-03-21 22:39:01,639 - DEBUG: C:\depot_tools\patch.PY -p1 --ignore-whitespace -i E:\ungoogled-chromium-72.0.3626.122-2\build\src\ungoogled_packaging\patches\inox-patchset\chromium-exclude_unwind_tables.patch -d E:\ungoogled-chromium-72.0.3626.122-2\build\src --no-backup-if-mismatch --forward
Traceback (most recent call last):
  File "ungoogled_packaging\build.py", line 187, in <module>
    main()
  File "ungoogled_packaging\build.py", line 164, in main
    buildkit.patches.patch_paths_by_bundle(bundle), source_tree, patch_bin_path=None)
  File "E:\ungoogled-chromium-72.0.3626.122-2\build\src\ungoogled_packaging\buildkit\patches.py", line 95, in apply_patches
    subprocess.run(cmd, check=True)
  File "C:\Python35\lib\subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by TCB13** [comment] 2019-03-21 18:16
Duplicate of https://github.com/Eloston/ungoogled-chromium/issues/675 , please close. `71.0.3578.98-2` is the last one for Windows that builds.

**Closed** 2019-03-21 19:18 UTC
