### ISSUE TITLE
Ungoogled Chromium trying to update automatically

### ISSUE THREAD

**Issue by scaledteam** [Eloston/ungoogled-chromium#863] opened 2019-11-17 18:35 UTC
![scr27375](https://user-images.githubusercontent.com/43995399/69012015-a406b680-0992-11ea-917e-02cc872378a9.png)
![scr31637](https://user-images.githubusercontent.com/43995399/69012030-bda7fe00-0992-11ea-92f1-a68ac0ec82f7.png)

Package was taken from this site:
https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/debian/buster_amd64/76.0.3809.132-1.buster1

**Comment by scaledteam** [comment] 2019-11-17 18:43
First picture says: "Failed to update chromium." 
Second picture says: "To complete the update, restart Chromium."

**Comment by Eloston** [comment] 2019-11-19 04:26
Duplicate of #721. Try upgrading to 78 and let us know if you still have the issue.

**Closed by Eloston** 2019-11-19 04:26 UTC
