### ISSUE TITLE
Link to clear browser data page when max redirects error page suggests to do so

### ISSUE THREAD

**Issue by haykam821** [Eloston/ungoogled-chromium#653] opened 2018-12-31 23:47 UTC
## The Problem

In the max redirects error page, there is [an ungoogled link](https://support.9oo91e.qjz9zk/chrome?p=rl_error&hl=en-US), with the text, "Try clearing your cookies."

![Max redirects error page](https://user-images.githubusercontent.com/24855774/50569104-11ced300-0d2c-11e9-80a3-54fe01d99a78.png)

## Proposed Solution

I would prefer this link to actually work (although it's not necessary). There is definitely an alternative link to put here, which is directly to the cookie-clearing internal page (`chrome://settings/clearBrowserData`).

## Related Issue

Issue #605 is related to this one, as it deals with links to Google support pages in these types of errors and info pages, specifically the incognito page.

## Additional Context

* `eloston-chromium@70.0.3538.77-1` (installed via Homebrew)
* macOS Mojave 10.14.1

**Comment by Eloston** [comment] 2019-01-01 01:18
Thanks for reporting. Going to close this as a duplicate of #605 and make that issue cover this one.

**Closed by Eloston** 2019-01-01 01:18 UTC
