### ISSUE TITLE
ungoogled chromium (flatpak) wont save passwords at all

### ISSUE THREAD

**Issue by fareszr** [Eloston/ungoogled-chromium#1373] opened 2021-02-02 23:25 UTC
**Describe the bug**
ungoogled chromium (flatpak) wont save passwords at all.
press save and nothing happens, the list of saved passwords in passwords tab in settings remains empty

**To Reproduce**
1. go to any website
2. log in
3. click save on the password manger pop up
4. check saved password list in settings

**Expected behavior**
it should save passwords normally like normal chromium.

**Environment (please complete the following information):**
 - OS/Platform and version: pop! os 20.10(gnome 3.38)
 - ungoogled-chromium version: 88.0.4324.104
 
**Additional context**
i tested it on normal flatpak chromium 88.0.4324.96 and it worked flawlessly 
2 devices have the issue

**Comment by 22-all** [comment] 2021-02-27 10:55
I can confirm this for the flatpak version 88.0.4324.182 (Official Build, ungoogled-chromium) (64-bit). Just to make sure, I have double-checked that "Clear cookies and site data when you quit Chromium" is definitely off.

**Comment by mikniche** [comment] 2021-03-07 17:00
Same issue here.

**Comment by 22-all** [comment] 2021-03-13 12:37
This now works in Version 89.0.4389.82.

**Comment by Eloston** [comment] 2021-03-14 03:01
Closing since new version resolves the issue. Let us know if this is not the case.

**Closed by Eloston** 2021-03-14 03:01 UTC
