### ISSUE TITLE
Add Flatpak, AppImage, or Snap support

### ISSUE THREAD

**Issue by nyancat18** [Eloston/ungoogled-chromium#36] opened 2016-09-05 16:14 UTC
Could you add a flatpak o appimage format  
http://flatpak.org/
http://appimage.org/

**Comment by probonopd** [comment] 2016-09-05 17:04
I am already converting Chromium snapshots from https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots to AppImages in a [fully automated way](https://github.com/probonopd/AppImages/blob/master/recipes/chromium/Recipe) using Travis CI. It would be easy to do for ungoogled-chromium if there are deb packages, too.

**Comment by triceratops1** [comment] 2016-09-05 20:09
@probonopd 


https://github.com/Eloston/ungoogled-chromium/releases/tag/51.0.2704.106-1

**Comment by probonopd** [comment] 2016-09-05 20:17
Can you provide ones for debian oldstable or trusty? That way the resulting AppImage could run on more but the very newest distros.

**Comment by Eloston** [comment] 2016-09-05 23:59
@probonopd Can Chromium even build on those platforms? Do your Chromium AppImages run on those systems? Are there enough people that use distributions that old?

This is a good idea, but it will take quite a bit of work. The Debian and Ubuntu package building process is based off of Debian's build of Chromium, so it has more system dependencies than Google's build of Chromium. This includes building with the system's Ninja builder, clang compiler, and linking against the system's FFmpeg libraries (which are all sensitive to the versions, except maybe Ninja).

If we are to get this work by modifying the Debian build process, there are several things that will have to be done. The meta-build configuration flags and patches to work with system libraries will have to be removed/disabled, the `buildtype` might need to be switched to `Official`, and some tools or scripts that have broken as a result of domain substitution or source cleaning will have to be provided or fixed in some way. If we are going to get this to work on Debian Wheezy or Ubuntu Trusty, some things might break beause the tools on those systems are pretty old.

Unfortunately, I don't have enough time to execute what I've just stated. I am planning on upgrading these patches to the latest version of Chromium, and I have priorities outside of this project that are taking up my time. However, I will have some time to provide help and implement a process into buildlib. So if anyone wants to take up the task, go right ahead.

**Comment by probonopd** [comment] 2016-09-06 00:02
"Are there enough people that use distributions that old?" - I cannot answer that but I do know that projects like Firefox and LibreOffice put a lot of care to build on old systems to maximize compatibility.

**Comment by Eloston** [comment] 2016-09-06 00:16
@probonopd Well [those seem to be the earliest versions that Chrome supports](https://support.google.com/chrome/answer/95346), so I guess it can be done somehow.

**Comment by Eloston** [comment] 2016-09-17 05:46
#41 made me realize that my approach to this problem was wrong. I was too narrowly focused on modifying the Debian build process to realize the approach described in #41 would be better.

Once #41 is done, adding support for AppImage should be relatively easy.

**Comment by sahal2080** [comment] 2016-10-23 01:22
Since [AppImage](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/README.md) can handle updating the package as well, this approach might be suited to be the "official" way to provide the app. In addition to less work building for different distros, this also minimizes the bugs related to dependencies hell (e.g. #107). I'm suggesting this especially since you're not able to support the project as much as you used to. 

I personally use Ubuntu so having this application on APT (#37) would be nice. Imho though, focusing more on _unGoogling_ chromium should be the highest priority and where the majority of the fine work be. If someone sees the convenience of installation/updating as a higher priority, they can always install chromium/chrome.

**Comment by Eloston** [comment] 2016-10-23 01:30
@sahal2080 You have some solid reasoning. That may not be a bad idea.

**Comment by probonopd** [comment] 2016-12-05 21:53
Can you get it to build on [Travis CI](https://travis-ci.org/)?

**Comment by Eloston** [comment] 2016-12-05 23:34
@probonopd I haven't tried it yet, but [I've had this concern in the past](https://github.com/Eloston/ungoogled-chromium/issues/37#issuecomment-247234282).

**Comment by Swiftpaw** [comment] 2017-05-10 13:49
Would be great to see flatpak or appimage replace all the existing builds.  Now that the stand-alone build is possible this should be easy I think.  I always thought flatpak had better integration features than appimage but not sure.  FP has sandboxing which I don't think AI has (by default?).  Sandboxing would probably be a good idea for an additional layer of security.

**Comment by probonopd** [comment] 2017-05-10 15:28
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be used with different sandboxes of the users' choice (e.g., Firejail, Bubblewrap)

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

FP has sandboxing built in but FB needs to be installed on the target system first.

**Comment by Swiftpaw** [comment] 2017-05-12 16:30
Works for most Linux distributions - so does Flatpak
One app = one file = super simple for users - so is Flatpak
No unpacking or installation necessary - if by "installing" you mean have launcher icons created for the easy launching of games and apps then this is a feature that users want so both formats need to create those.  Also, if you mean AI keeps running from the same downloaded file and doesn't make a copy into a hidden location, that's annoying because the user would lose the app if they cleared out their downloaded files.  I'd rather it was "installed" so I could save the installation package if I so chose to do so but that had no impact on me continuing to run the app.
No root needed - same for flatpak, plus sandboxing
No system libraries changed - same with flatpak.
Works out of the box, no installation of runtimes needed - runtimes, if they are used, are automatically downloaded and installed.  Having shared libraries is a good thing and means FP packages are going to be smaller than AI packages since AI has no library sharing.
Optional desktop integration - FP's integration is default AFAIK
Optional binary delta updates - FP's default
GPG2-signing - FP has it
Works on Live ISOs - FP can be installed on liveISOs just like any program can be, and if FP was included by default if it takes off and becomes a good standard, then obviously installation wouldn't be needed.
Can use the same AppImages when dual-booting multiple distributions - I'd think you wouldn't need to duplicate the app data with either system.
Can be used with different sandboxes of the users' choice (e.g., Firejail, Bubblewrap) - I'm not sure if FP can work with alternate sandboxing, but as long as FP uses the best one and there's no big reason to use a different one, that wouldn't matter much.

**Comment by probonopd** [comment] 2017-05-13 08:25
Sorry @Swiftpaw but some of your claims are simply not correct (e.g., FP needs to be installed first, scatters files into the filesystem, and does not work on Live systems, just to name 3). In order not to further spam this thread, let's close this here though.

**Comment by Swiftpaw** [comment] 2017-05-13 13:24
Uh what?  Did you even read (and comprehend) anything I wrote?  Or do you try to shut down anyone whom you think is biased even though I was simply listing the features of each package system that I know about?  lol

FP needs to be installed first while AI doesn't.  This wasn't a bullet point mentioned, though.  If you're referring to "works for most Linux distros", both FP and AI are compatible with most Linux distributions, but FP isn't _available_ out-of-the-box, not until it comes standard.  It's easy to install on all those distros, though.  So yeah, AI is a little better in this regard, so what's your problem here?  Explain yourself.

"Scatters files into the filesystem", I was arguing that FP probably does this while AI might not?  Given that FP needs to be installed first, and that FP "installs programs", I assume AI doesn't need to copy files elsewhere while FP does.  My point was that this isn't necessarily a bad thing.  I like installing packages and not having to keep the package file around on my desktop if I want to run the same app again in the future.  So, what are you trying to say about this part?

"Does not work on Live systems", the only thing you mentioned was "FP", so I assume you're talking about FP here?  Regardless, I was saying that FP _does_ work in Linux environments, and that _both_ will do so.  You can run anything in a live environment because it's just a RAM disk.  There is nothing particularly special about putting program data into a RAM disk instead of a HDD.  You can even download, install, and run games in a live environment as long as that live environment enabled sufficient graphics drivers to do so.  So, explain yourself here again too, what about this do you disagree with?  Since that's the defensive attitude you're showing.

Both FP and AI have some features that the other doesn't have, but overall they are fairly comparable and they are both step ups above the old static binary method and either solution would be better than trying to make repos for every distro out there.  I'm in favor of both, but you, probonopd, acted like the things you listed are exclusive features of AI over FP, and that's definitely wrong, hence my original response.

**Comment by Eloston** [comment] 2017-05-13 20:29
@Swiftpaw @probonopd Hey guys, please stay to the original topic of adding Flatpak or AppImage support. (Adding support for both will be fine too).

**Comment by Eloston** [comment] 2017-05-21 19:57
I will accept a pull request to add Flatpak or AppImage support (or both) into `utilikit`. Chances are you'll need a configuration type like `linux_conservative` and new build types for the build files generator.

**Comment by Eloston** [comment] 2018-02-22 19:11
Things have changed for version 64. One can use the `linux_portable` base bundle to build, and then add new packaging types for Flatpak and AppImage.

The existing packaging types are pretty simple and should work as a good reference for these ones. If anyone is interested in this, feel free to submit a PR.

**Comment by rugk** [comment] 2018-08-15 16:11
Flatpak support would be great, as it runs this here in a sandbox then.

**Comment by probonopd** [comment] 2018-08-15 16:53
How does one use the linux_portable base bundle to build?

**Comment by Eloston** [comment] 2018-08-16 05:06
@probonopd I have implemented a new packaging system (in the `redesign` branch) that is simpler and more straightforward. In the next few days, I will be working to merge it into `master` and then begin updating to version 68. If you are willing to wait, it should be easier to work with the new system.

**Comment by Eloston** [comment] 2018-08-22 22:08
@probonopd 68 is out now. You can have a look at [the tar building instructions](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md#build-a-tar-archive) as a reference for your packaging scripts. [The design doc's packaging section also changed a bit](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/design.md#packaging) to reflect the new design.

Let me know if you need clarifications.

**Comment by probonopd** [comment] 2018-08-25 06:59
Can you please point me at what I have to do on Ubuntu 14.04 (the oldest still-supported LTS release) to get the dependencies in place?

```
$ sudo apt-get -y install clang-6.0 lld-6.0 llvm-6.0-dev python python3 ninja-build
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package clang-6.0
E: Couldn't find any package by glob 'clang-6.0'
E: Couldn't find any package by regex 'clang-6.0'
E: Unable to locate package lld-6.0
E: Couldn't find any package by glob 'lld-6.0'
E: Couldn't find any package by regex 'lld-6.0'
E: Unable to locate package llvm-6.0-dev
E: Couldn't find any package by glob 'llvm-6.0-dev'
E: Couldn't find any package by regex 'llvm-6.0-dev'
```

Thank you.

**Comment by probonopd** [comment] 2018-08-26 06:04
Running into

```
$ ./get_package.py linux_simple build/src/ungoogled_packaging
Traceback (most recent call last):
  File "./get_package.py", line 18, in <module>
    from buildkit.common import (ENCODING, BuildkitAbort, get_logger, validate_and_get_ini,
  File "/home/travis/build/probonopd/ungoogled-chromium/buildkit/common.py", line 42
    return schema_dictcast({configparser.DEFAULTSECT: object, **data})
                                                               ^
SyntaxError: invalid syntax
```

Reference:
https://travis-ci.org/probonopd/ungoogled-chromium/builds/420681072#L599-L606

**Comment by probonopd** [comment] 2018-08-26 07:03
Using Python 3.6 (the newest one I can use) seems to remove that error, but now I am running into

```
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by probonopd** [comment] 2018-08-26 08:33
WIth `python2` I now get

```
+python2 ./tools/gn/bootstrap/bootstrap.py -o out/Default/gn -s
  File "./tools/gn/bootstrap/bootstrap.py", line 115
    exec(response, _globals, _locals)
SyntaxError: unqualified exec is not allowed in function 'CallPythonScopeScript' it is a nested function
```

**Comment by Eloston** [comment] 2018-08-26 18:33
> Using Python 3.6 (the newest one I can use) seems to remove that error

I developed the code on 3.5 (the only Python 3 available in stretch), so 3.5 is the minimum. Using 3.6 shouldn't hurt, though.

> SyntaxError: unqualified exec is not allowed in function 'CallPythonScopeScript' it is a nested function

I have seen this error once before on an older CentOS 7 machine. At the time, I didn't have much time to investigate.

After reading around a bit, there may be some differences in how `exec` is implemented in different Python 2 versions.

[From the latest Python 2 docs (2.7.15 at the time of writing)](https://docs.python.org/2/reference/simple_stmts.html?highlight=exec#exec):

> The first expression may also be a tuple of length 2 or 3. In this case, the optional parts must be omitted. The form exec(expr, globals) is equivalent to exec expr in globals, while the form exec(expr, globals, locals) is equivalent to exec expr in globals, locals. The tuple form of exec provides compatibility with Python 3, where exec is a function rather than a statement.

But, I keep seeing reports of people explicitly rewriting the `exec` function-like syntax into the old statement form. It might be originating from this bug, which was fixed in 2.7.9: https://bugs.python.org/issue21591

Debian stretch ships with 2.7.13. What version of Python 2 are you using?

**Comment by probonopd** [comment] 2018-08-26 18:58
After having pulled in Python 3.6.3 from a PPA, this error seems to be gone and I now have a new error:

```
/home/travis/build/probonopd/ungoogled-chromium/build/src/base/template_util.h:145:46: error: no template named 'is_trivially_copy_constructible' in namespace 'std'
using is_trivially_copy_constructible = std::is_trivially_copy_constructible<T>;
                                        ~~~~~^
1 error generated.
[7/367] CC base/third_party/libevent/evrpc.o
ninja: build stopped: subcommand failed.
Command '['ninja', '-C', '/tmp/tmp3nKiQf', 'gn']' returned non-zero exit status 1
```

https://travis-ci.org/probonopd/ungoogled-chromium/jobs/420804430#L2399-L2405

**Comment by Eloston** [comment] 2018-08-26 21:40
@probonopd Should be fixed in 674540188d48d997ea4bb02d0f19621743f64b29

**Comment by probonopd** [comment] 2018-08-26 22:08
Thank you. More errors... https://travis-ci.com/probonopd/ungoogled-chromium/builds/82908706#L2463-L2488

**Comment by Eloston** [comment] 2018-08-26 22:13
@probonopd In that case, you may want to do what Arch Linux does for Python 2 on these lines:

* https://github.com/Eloston/ungoogled-chromium/blob/821a4414a892472eebfdcf648a025519a1458cb1/packaging/archlinux/PKGBUILD.ungoogin#L130
* https://github.com/Eloston/ungoogled-chromium/blob/821a4414a892472eebfdcf648a025519a1458cb1/packaging/archlinux/PKGBUILD.ungoogin#L84

Out of curiosity, what platform are you building on that has `python` as Python 3? I thought you were building on Trusty?

**Comment by probonopd** [comment] 2018-08-26 22:17
Yes, I am building on Trusty. Here is my [.travis.yml](https://github.com/probonopd/ungoogled-chromium/blob/patch-1/.travis.yml).

**Comment by Eloston** [comment] 2018-08-26 22:36
@probonopd The Python issue may be because you specified "3.6" on top. Maybe you could specify "2.7" and then install 3.6 after the fact via apt so that `python` becomes Python 2?

However, you seem to be trying to fit an elephant in the room by building the source code in Travis CI. It is something we investigated in #37 and it definitely won't work (Chromium's build process is too computationally demanding to be willingly built for free by most service providers). So you'll either need to pull from ungoogled-chromium-binaries for new Portable Linux binaries, or delegate compilation to a willing third-party service.

**Comment by probonopd** [comment] 2018-08-26 22:38
The latest binaries on https://github.com/ungoogled-software/ungoogled-chromium-binaries/releases are from Dec 19, 2016?

**Comment by probonopd** [comment] 2018-08-26 22:39
> so that python becomes Python 2

I am doing this explicitly here:

https://github.com/probonopd/ungoogled-chromium/blob/67483c0f3ee6fd5817f5af90a1b54b67b1fc1b8e/.travis.yml#L35

**Comment by probonopd** [comment] 2018-08-26 22:48
Do you know how e.g., https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/67.0.3396.87-2 gets created? Where is it compiled, where are the build logs, etc.? It would be most likely really trivial to hook in AppImage generation into the existing pipeline in this case.

**Comment by Eloston** [comment] 2018-08-27 00:45
> Where is it compiled, where are the build logs, etc.? It would be most likely really trivial to hook in AppImage generation into the existing pipeline in this case.

I like your approach of learning backwards (i.e. from the implementation back to the design, like I do for Chromium), but I have design docs so you don't need to do this. Have a look at [the design doc section for packaging](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/design.md#packaging) to get an idea of this part of the process. Also, have a look at [the README for ungoogled-chromium-binaries](https://github.com/ungoogled-software/ungoogled-chromium-binaries/blob/master/README.md) to see what it's all about.

From those, I think we can figure out a workflow that suits us both.

**Comment by probonopd** [comment] 2018-08-27 18:32
Not sure I read the 2nd document correctly, but are you saying there is no CI build pipeline and project members/you are building on local machines?

**Comment by probonopd** [comment] 2018-08-27 20:07
> That is correct. For some background, I have declined offers in the past for dedicated building hardware because I did not want to handle that kind of responsibility. I also did not want others to feel obligated to provide the hardware either. It was a questionable perspective in hindsight, but that's where we are at now.

I fully understand your decision (and have made my fair share of mistakes trusting random people lending housed hardware in the past).

So, essentially if I write a bash script that takes the Portable Linux build and turns this into an AppImage, that's all you'd need?

**Comment by Eloston** [comment] 2018-08-27 21:42
> So, essentially if I write a bash script that takes the Portable Linux build and turns this into an AppImage, that's all you'd need?

Yep. I'm thinking that we can add a script like `package_appimage.sh` into `linux_simple` that runs after `build.sh` to generate the AppImage (and rename `package.sh` to `package_tar.sh` to prevent confusion). This way, we can generate multiple different packages directly from the build outputs.

FYI I'm not sure if you will need this, but the buildkit command `filescfg list` (which uses `filescfg_generator()` in `buildkit.filescfg`) will list out only the files needed to run Chromium.

**Comment by probonopd** [comment] 2018-08-30 06:27
I have written an initial recipe to convert the existing build into an AppImage:

https://github.com/AppImage/AppImages/blob/master/recipes/ungoogled-chromium.yml

Feedback appreciated.

**Comment by Eloston** [comment] 2018-08-30 07:46
@probonopd Two potential issues:

1. You have written quite the shell command to determine the Portable Linux binary to download, but it's assuming that I will be the uploader. This will fail if someone else uploads a Portable Linux binary.
2. There is a slight branding change of the browser. I'm guessing this is unavoidable because of the nature of AppImages (e.g. a user has a real Chromium AppImage side-by-side with an ungoogled-chromium AppImage). If this is not the case, then I'd prefer if the change were reverted.

Everything else LGTM.

**Comment by probonopd** [comment] 2018-08-31 19:11
Thanks for your feedback @Eloston.

1. How can I find the URL to the latest version? Do you have a permalink URL that redirects to the latest, for example?
2. Are you referring to the fact that I change the desktop file to say "Ungoogled Chromium" instead of "Chromium"? I think this is the correct thing to do since the name of the application is actually "Ungoogled Chromium", and we need to somehow distinguish it as something different from upstream Chromium. Please keep in mind that users may have multiple versions of Chromium on their machine, both Ungoogled and upstream. What should I do?

**Comment by Eloston** [comment] 2018-08-31 21:41
@probonopd 

> How can I find the URL to the latest version? Do you have a permalink URL that redirects to the latest, for example? We could also change it so that instead of downloading something it copies in some local deb, but for that we would at least know the name and location of that deb.

Unfortunately, there's no way to create a permalink using only GitHub Pages. I haven't really thought of using one before, so I never looked into it. Do you happen to know of any free permalink services that are simple enough to be updated via CI?

The other alternative would be to parse the INI file, but that won't be trivial with just shell commands (it's already hard enough to get the version to use).

> we need to somehow distinguish it as something different from upstream Chromium. Please keep in mind that users may have multiple versions of Chromium on their machine, both Ungoogled and upstream

I see. Thanks for confirming my suspicions in the previous message.

In that case, we can just leave it alone. But for aesthetics, could you change it to "ungoogled-chromium" or "Chromium (ungoogled)"? Seeing it as "Ungoogled Chromium" looks a little weird to me.

**Comment by Eloston** [comment] 2018-09-04 17:42
> Who else could be the uploader? And where would those files be hosted? Can the name of the uploader be determined dynamically? How?
> I have not quite understood what the problem is in the current method of getting the most recent available *_linux.tar.xz. Can you please elaborate and describe the optimal strategy? Thanks.

* Every published version of 64-bit Portable Linux binaries are [defined in ini files under config/platforms/linux_portable/64bit](https://github.com/ungoogled-software/ungoogled-chromium-binaries/tree/master/releases/linux_portable/64bit). Each ini file contains file names (in section headers, excluding the designated section for metadata), the hashes of said file, and the URL for retrieving the file contents via an HTTP GET request.
* Additionally, each INI file represents a separate page with file links that you see on the downloads page. For example, [67.0.3396.87-2 for Portable Linux 64-bit](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/67.0.3396.87-2) has its INI file defined in [config/platforms/linux_portable/64bit/67.0.3396.87-2.ini](https://github.com/ungoogled-software/ungoogled-chromium-binaries/blob/master/config/platforms/linux_portable/64bit/67.0.3396.87-2.ini).
* Because the version of each download is defined by the ini file name, [config/valid_versions defines all valid published versions](https://github.com/ungoogled-software/ungoogled-chromium-binaries/blob/master/config/valid_versions) to prevent typos in the file names and define the ordering of versions. You could use this to determine potential INI file names.

**Comment by Eloston** [comment] 2018-09-06 06:31
@probonopd At that rate you might as well do a shallow clone of the `ungoogled-chromium-binaries` repo. That way you can use standard shell commands to sort the ini files in there, pick the latest one, and read it. Unless you're up to parsing generated HTML...

**Comment by Eloston** [comment] 2018-09-10 06:39
Well, AppImage suppport is in now. Thanks @probonopd for implementing it.

If anyone wants to add Flatpak or Snap support, please open separate issues for them.

**Closed by Eloston** 2018-09-10 06:39 UTC
Labels: enhancement, help wanted

**Comment by intika** [comment] 2018-09-11 01:57
is pushing an appimage binary to download section planned ?

**Comment by Eloston** [comment] 2018-09-11 02:39
@intika I don't have any plans to do it. If it's appropriate to do so, then I'd be willing to merge a PR.

**Comment by probonopd** [comment] 2018-09-12 05:47
@Eloston that'd be of course awesome, as it would a) be much easier for users b) "official" (never trust applications downloaded from random sites - especially browsers!), and c) would allow the application to be listed in the AppImageHub central directory of available AppImages.

**Comment by probonopd** [comment] 2018-09-12 05:48
> Well, AppImage suppport is in now. 

Please don't forget to update

https://github.com/Eloston/ungoogled-chromium/blob/cc80091a8e6b357e6ba8fc21ab566a63255fc90d/docs/building.md#building-an-appimage-flatpak-or-snap-package

on how to get it.

**Comment by intika** [comment] 2018-09-12 22:07
@probonopd why don't you just PR https://github.com/ungoogled-software/ungoogled-chromium-binaries with the appimage you did ?

**Comment by probonopd** [comment] 2018-09-14 17:37
> may be you want it to be build and published by @Eloston

yes 👍

**Comment by Eloston** [comment] 2018-09-14 17:55
@probonopd Why must I be the builder and publisher of the AppImage? Can't anyone do it?

If all it takes to be "official" is be on `ungoogled-chromium-binaries`, i.e. the "contributor binaries website", then I fail to see the reason. Also, I will be a bottleneck if I have to maintain binaries.

**Comment by probonopd** [comment] 2018-09-14 19:04
Who ensures how that we can trust those binaries?

**Comment by Eloston** [comment] 2018-09-14 19:31
@probonopd Who's to say I'm more trustworthy than any other contributor here?

I believe that everyone who has been contributing binaries are doing so out of their own good will, mainly because of the following factors:

* The target audience of this project is relatively small (technically-able *and* privacy-conscious)
* This is still a relatively small project within that target audience
* The effort to produce malicious binaries is pretty high compared to any rewards from malicious intent I can think of.

Once binary reproducibility becomes a reality, then we could go by independent replication of the build process to verify if the binaries are valid. It's not as good as understanding and building the source code by oneself, but at least the trust is more distributed rather than centralized on single individuals.

**Comment by probonopd** [comment] 2018-09-14 19:39
Yes, I'm highly interested in peer-producing a web-of-trust!

**Comment by intika** [comment] 2018-09-15 01:36
> Once binary reproducibility becomes a reality
Its very cool and important to see devs working on that, opensource world is unique  
> Yes, I'm highly interested in peer-producing a web-of-trust!
mee too :D 

But at the end of the day who is willing to provide the appimage ?

**Comment by intika** [comment] 2018-09-16 19:11
a build from @Eloston is not a must have, according to this project policy about binary distribution system, also all linux distro packages are not build by the same person... so in the other hand it's a waste of time regarding the time consumption of dev for this project... following the idea of @picsi & @Eloston  i think adding the appimage build script to the sources with a PR (and a PR to build instruction) will be the way to go once merged i guess we will at least have one build from @Eloston or not lol :+1: but at least we will have a build

**Comment by probonopd** [comment] 2018-09-18 06:43
...hence I was wondering if we could/should use Travis CI or something like it for the builds (not just the AppImage)

**Comment by intika** [comment] 2018-10-06 15:44
Just landed an AppImage build... 
i will pr that soon 
https://www.opendesktop.org/p/1266054/

**Comment by intika** [comment] 2018-10-06 16:10
Done https://github.com/ungoogled-software/ungoogled-chromium-binaries/pulls

**Comment by intika** [comment] 2018-10-06 21:55
Now TODO : 
- Update/PR pkg2appimage to make it compatible with non debian system 
- Integrate & PR pkg2appimage/uc-appimage script to ungoogled-chromium

**Comment by intika** [comment] 2018-10-07 01:05
Done everything is landed 
https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/29 and https://github.com/Eloston/ungoogled-chromium/pull/551 and https://github.com/AppImage/AppImages/pull/349

Build instructions : 
On portable build instructions after : 
```
./ungoogled_packaging/build.sh
./ungoogled_packaging/package.sh
```
Just run 
`./ungoogled_packaging/package.appimage.sh`
