### ISSUE TITLE
Your browser is managed

### ISSUE THREAD

**Issue by ppavacic** [Eloston/ungoogled-chromium#1408] opened 2021-02-21 23:49 UTC
I'm not sure whether that is a bug or not, but in my ungoogled chromium it says "Your browser is managed by your organization". I've installed browser from  https://download.opensuse.org/repositories/home:/wchen342:/ungoogled-chromium-fedora/Fedora_33/ 

**To Reproduce**
1. Go to three dot menu at the top right corner
2. Does it say this browser is managed by your organization?

**Screenshots**
![image](https://user-images.githubusercontent.com/5007441/108642769-6e128500-74a7-11eb-9897-f429f24fe4b5.png)
![image](https://user-images.githubusercontent.com/5007441/108642781-78cd1a00-74a7-11eb-8514-917c0596eeef.png)

**Environment (please complete the following information):**
 - Linux/Fedora 33

**Comment by qvint** [comment] 2021-02-22 05:21
It's not a bug. Fedora provides some policy rules for all Chromium derivatives, see chrome://policy/

```
$ rpm -q --whatprovides /etc/chromium/policies/managed/00_gssapi.json
fedora-chromium-config-1.1-7.fc33.noarch
```

**Comment by wchen342** [comment] 2021-02-22 17:09
Are you on the first page of `chrome://settings/`? If so then something is different on your machine. On my F33 this doesn't occur (at least on the first page).

**Comment by qvint** [comment] 2021-02-22 17:50
If you didn't patch out [the hard-coded path](https://chromium.googlesource.com/chromium/src/+/ae22099890d9da068dc02e225508b55ed669cca9/chrome/common/chrome_paths.cc#429), it *will* use [the policy rules](https://src.fedoraproject.org/rpms/fedora-chromium-config/blob/6578a0c943d8a25897333be6d5b973eae3ca526f/f/fedora-chromium-config.spec#_80) from `fedora-chromium-config` (it comes [pre-installed](https://pagure.io/fedora-comps/blob/942f68a73e41aa75a5b268fd901a117d57ba160d/f/comps-f33.xml.in#_5456) in Fedora Workstation).

**Comment by wchen342** [comment] 2021-02-22 17:55
I didn't remember I uninstalled `fedora-chromium-config` on my machines..maybe it is only pre-installed on certain variants? (I use the KDE spinoff).

**Comment by mahsank** [comment] 2021-04-19 12:12
I am seeing the exact same behavior. I don't have `fedora-chromium-config` installed. `rpm -qa | grep -i fedora-chromium` returns nothing. I'm using KDE as well.

**Comment by mahsank** [comment] 2021-05-12 07:18
Ok; I did some more digging and it appears if you have defined any custom policies in `/etc/chromium/policies`, you will see the message "Your browser is managed". In my case, I have defined some custom policies in `/etc/chromium/policies/managed/policies.json`. I did some experimenting and (re)moved the folder managed from this location. After removing the managed folder, the message disappears.

**Comment by mahsank** [comment] 2021-05-12 08:10
IMHO, this issue can be closed as this is not really an issue with the browser but with the user setup/customizations.

**Closed** 2021-09-25 11:36 UTC
