### ISSUE TITLE
why are the builds for are not in the releases section?

### ISSUE THREAD

**Issue by j0k4rX** [Eloston/ungoogled-chromium#1909] opened 2022-04-13 15:21 UTC
Hi @Eloston ,
It'd be great if the builds for different os'es are posted in the releases section.
Regards.

**Comment by PF4Public** [comment] 2022-04-13 15:23
Is current approach somehow unusable? https://ungoogled-software.github.io/ungoogled-chromium-binaries/

**Comment by networkException** [comment] 2022-04-13 15:26
Including platform binaries in the GitHub releases of this repository would not only require all packaging to be contained in here, it would also require all maintainers to update at the same time.

That is not feasable due to varying complexity of the update process and different people having different amounts of spare time.

**Comment by PF4Public** [comment] 2022-04-13 15:32
> Including platform binaries in the GitHub releases of this repository would not only require all packaging to be contained in here, it would also require all maintainers to update at the same time.

Not entirely true. It is quite possible to use [empty repository](https://github.com/PF4Public/ungoogled-chromium-bin/commits/master) for [binary releases](https://github.com/PF4Public/ungoogled-chromium-bin/releases), all hanging on the same commit :)

>That is not feasable due to varying complexity of the update process and different people having different amounts of spare time.

Agree with this though

**Comment by rubyando** [comment] 2022-04-13 23:56
> Is current approach somehow unusable? https://ungoogled-software.github.io/ungoogled-chromium-binaries/

downloading sus builds from random people is kinda sus

"these binaries are not necessarily reproducible, authenticity cannot be guaranteed"

**Comment by networkException** [comment] 2022-04-14 00:01
Yes but that's nothing including platform releases in this repository will solve

**Comment by rubyando** [comment] 2022-04-14 03:13
look all i want is an "official" upload of win x64 U-C build from @Eloston himself is that too much to ask?

**Comment by PF4Public** [comment] 2022-04-14 09:51
> is that too much to ask

it is

**Comment by PF4Public** [comment] 2022-04-14 09:55
Duplicate of #1623
Please search existing and closed issues for similar ones first

Also see the discussion in #1549

**Closed by PF4Public** 2022-04-14 09:55 UTC
