### ISSUE TITLE
windows tool to set as default browser / wiki

### ISSUE THREAD

**Issue by xhiddle** [Eloston/ungoogled-chromium#693] opened 2019-02-25 14:51 UTC
I'm not savvy enough to understand how to overcome this shortfall with a third party tool by _Christoph Kolbicz_:

https://kolbi.cz/blog/2017/11/10/setdefaultbrowser-set-the-default-browser-per-user-on-windows-10-and-server-2016-build-1607/

via: https://kolbi.cz/blog/2017/10/25/setuserfta-userchoice-hash-defeated-set-file-type-associations-per-user/

It scans to find all installed browsers.  Had Ungoogled Chromium been installed in some normal way it likely would be found.  I have replaced edge with firefox which itself should only  be used after recovering user control of privacy 

https://github.com/ghacksuserjs/ghacks-user.js

https://github.com/ghacksuserjs/ghacks-user.js/releases

soooo... I've moved the ball down the field a little

**Comment by TCB13** [comment] 2019-02-26 15:19
@xhiddle I believe that tool can't find Ungoogled because it isn't registered in the system. If you go to Windows Settings Ungoogled won't also show on the Default Browser section, can you confirm this?

If yes, you might be able to use my changes to the reg attached. This will register Ungoogled in your system.
[ungoogled-chromium.zip](https://github.com/Eloston/ungoogled-chromium/files/2906142/ungoogled-chromium.zip)

**Comment by Eloston** [comment] 2019-03-02 21:52
This is a duplicate of #623.

**Closed by Eloston** 2019-03-02 21:52 UTC

**Comment by Innomen** [comment] 2019-07-11 18:44
> This is a duplicate of #623.

Ya and it's still not addressed. Why are you insufferable? Quit closing threads as if that's frixing things, damn.

**Comment by jstkdng** [comment] 2019-07-11 19:38
Chrlauncher has this nice batch script to set chrlauncher the default browser, I just changed it to use chromium directly, though, chromium doesn't recognize itself as a default browser, something is missing.
To use this script just execute SetDefaultBrowser.bat as admin and to remove it execute RegistryCleaner.reg as admin.
You have to have chromium extracted to C:\Program Files\Chromium\
[tool.zip](https://github.com/Eloston/ungoogled-chromium/files/3383621/tool.zip)

**Comment by temosh1** [comment] 2020-10-19 17:05
> Chrlauncher has this nice batch script to set chrlauncher the default browser, I just changed it to use chromium directly, though, chromium doesn't recognize itself as a default browser, something is missing.
> To use this script just execute SetDefaultBrowser.bat as admin and to remove it execute RegistryCleaner.reg as admin.
> You have to have chromium extracted to C:\Program Files\Chromium
> [tool.zip](https://github.com/Eloston/ungoogled-chromium/files/3383621/tool.zip)
> Making an installer would be easier, but dunno how.

thanks

**Comment by Gus-X** [comment] 2022-01-19 17:05
My two cents here:
Made my mod for default version of  Chromium copied to this folder ->  "C:\Program Files\chrome-win\chrome.exe"
Copy Chromium to provided folder due file  *.reg provided by @TCB13 was modded for this folder specifically. 
[chromium.zip](https://github.com/Eloston/ungoogled-chromium/files/7899086/chromium.zip)

Note: I needed to reboot to make it "Apply settings" but it should work straight forward.
