### ISSUE TITLE
Enhacement: Compile online

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#200] opened 2017-03-18 23:55 UTC
Considering the chromium size use a normal pc (if you've a shitty computer its bad)

use wercker/travis blocks you

but OBS its unlimited 

you can use my build
as base

https://build.opensuse.org/package/show/home:meh924f:archlinux/inox

https://build.opensuse.org/project/show/home:meh924f:archlinux

**Comment by Eloston** [comment] 2017-03-19 00:35
Thanks, but we aren't lacking computational resources at this time.

Also, this is a duplicate of #17.

**Closed by Eloston** 2017-03-19 00:35 UTC

**Comment by triceratops1** [comment] 2017-03-19 00:41
ok

**Comment by triceratops1** [comment] 2017-03-19 00:42
but that would make very easy 
for users with bad pcs
mantain ungoogled

**Comment by Eloston** [comment] 2017-03-19 03:25
Like I said, we are not lacking computational resources at this time. If this does become an issue, we will deal with it then.
