### ISSUE TITLE
Chromium v89.0.4389.114-1 - Error libicui18n.so.68

### ISSUE THREAD

**Issue by v00v** [Eloston/ungoogled-chromium#1492] opened 2021-04-17 09:48 UTC
**Describe the bug**
Update to latest icu/harfbuzz packages resulted in chromium not starting.

**Versions**
* icu-69.1-1
* harfbuzz-2.8.0-3
* harfbuzz-icu-2.8.0-3

**To Reproduce**
Upgrade to package versions above.

**Expected behavior**
For chromium to open!

**Screenshots**

**Environment (please complete the following information):**
 - OS/Platform and version: Arch Linux / Kernel 5.11.11-arch1-1
 - ungoogled-chromium version: 89.0.4389.114-1

**Additional context**

**Comment by git-bruh** [comment] 2021-04-17 09:52
This happens because the chromium build you're using links to system ICU instead of statically linking the ICU that ships with the chromium source. Since icu updated to 69.1, the soname of the library changed aswell. It might not work but you can try symlinking the new library to the old library's soname as a hack: `cd /usr/lib; ln -s libicui18n.so.69 libicui18n.so.68`. A proper fix would be to chromium be rebuilt to link with the new system icu.

**Comment by v00v** [comment] 2021-04-17 10:02
@git-bruh After I run `cd /usr/lib; ln -s libicui18n.so.69 libicui18n.so.68` it also showed me `libicuuc.so.68` so I tried `cd /usr/lib; ln -s libicuuc.so.69 libicuuc.so.68` and now I'm getting this following error `undefined symbol: _ZN6icu_688TimeZone13createDefaultEv`. So the only way this can work if chromium is recompiled using newest icu packages. Can you guys submit a `89.0.4389.114-2` please? It takes forever to compile here, slow CPU.

**Comment by git-bruh** [comment] 2021-04-17 10:14
You could also install the old version of `icu` into `/usr/local/lib` and `export LD_LIBRARY_PATH=/usr/local/lib` before running chromium.

**Comment by v00v** [comment] 2021-04-17 10:26
That what I said above, I tried downgrade but it did not work this time. Thank for your help!

**Comment by braewoods** [comment] 2021-04-17 16:23
Where did you get your build from?

**Comment by v00v** [comment] 2021-04-18 10:50
@braewoods, https://ungoogled-software.github.io/ungoogled-chromium-binaries/

**Comment by braewoods** [comment] 2021-04-18 10:52
I thought as much. Our new OBS repository for Arch recently launched. It's currently rebuilding for this issue.

**Comment by braewoods** [comment] 2021-04-18 10:52
See here for more information.
https://github.com/ungoogled-software/ungoogled-chromium-archlinux

**Comment by braewoods** [comment] 2021-04-18 10:54
I estimate the new build should appear in about 4 hours.

**Comment by v00v** [comment] 2021-04-18 10:55
@braewoods Thank you! I did not know you guys have OBS repository now :+1: Will take a look!

**Comment by v00v** [comment] 2021-04-18 10:58
Added OBS repo to ``/etc/pacman.conf`` and got this error upon running ``pacman -Sy``:

```
pacman -Sy
error: home_ungoogled_chromium_Arch: key "02456C79B2FD48BF" is unknown
:: Import PGP key 02456C79B2FD48BF? [Y/n] 
error: key "02456C79B2FD48BF" could not be looked up remotely
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 home_ungoogled_chromium...  1347.0   B   219 KiB/s 00:00 [##############################] 100%
 home_ungoogled_chromium...   280.0   B  0.00   B/s 00:00 [##############################] 100%
error: home_ungoogled_chromium_Arch: key "02456C79B2FD48BF" is unknown
:: Import PGP key 02456C79B2FD48BF? [Y/n] 
error: key "02456C79B2FD48BF" could not be looked up remotely
error: failed to update home_ungoogled_chromium_Arch (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
```

**Comment by braewoods** [comment] 2021-04-18 11:00
You need to follow the curl step which downloads the repository key and adds it.

**Comment by braewoods** [comment] 2021-04-18 11:03
The normal key import will probably fail because I don't think OBS adds these keys to any key server. It just generates them when needed.

**Comment by v00v** [comment] 2021-04-18 11:12
@braewoods, Thank you for your help. Curl command worked :-) ``home_ungoogled_chromium_Arch is up to date`` now will wait for new version.

**Comment by v00v** [comment] 2021-04-18 11:43
But I think you should also contribute to official binary page here too @ https://ungoogled-software.github.io/ungoogled-chromium-binaries/  I'm sure you can automate this process too on every new version compile.

**Comment by braewoods** [comment] 2021-04-18 11:46
I can't automate the builds as there's a lot that can break. Not all rebuilds are going to go as smoothly as this one. At best I can automate detection. And we only really need one good source for this.

**Comment by braewoods** [comment] 2021-04-18 11:47
I already had the contributor binaries for Ubuntu and Debian dropped because OBS is a much better place to get them ultimately. I'll probably drop the Arch ones at a later time but not for now.

**Comment by v00v** [comment] 2021-04-18 12:26
Another issue found, by simply running this command;
```
pacman -S ungoogled-chromium
:: ungoogled-chromium is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
```
Please note I do not have this package in "IgnorePkg/IgnoreGroup".

**Comment by braewoods** [comment] 2021-04-18 13:09
It sounds like a local issue as I never saw that in my test containers.

**Comment by v00v** [comment] 2021-04-18 15:25
@braewoods, There was an error in my config file, fixed now. I used inline comment and pacman.conf does not support inline comments. I've also tested latest compiled version ``89.0.4389.114-2`` and everything works as expected now. Thank you for taking your time to re-compile this package. I hope you continue to support Arch Linux, because many people use it.

**Comment by Iron-E** [comment] 2021-04-19 14:23
I can confirm as well. Thank you @braewoods!

**Comment by adamshem** [comment] 2021-04-19 16:25
I am also experiencing `/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory` 

I am using the arch binaries and installing the local package with pacman -U

Has this been fixed yet?

**Comment by Iron-E** [comment] 2021-04-19 16:35
@adamshem it should be. Are you using the [OBS repo](https://github.com/ungoogled-software/ungoogled-chromium-archlinux#binary-downloads) with `pacman`?

**Comment by adamshem** [comment] 2021-04-19 16:40
@Iron-E I am going to try this now and report back.

**Comment by adamshem** [comment] 2021-04-19 16:57
@Iron-E it worked! Thank you!

**Comment by Iron-E** [comment] 2021-04-19 16:58
Happy to hear it!

**Comment by blipk** [comment] 2021-04-22 04:06
I'm experiencing this issue using the latest OBS Arch Linux repository build (89.0.4389.114-2)

`/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory`

I tried creating a symbolic link, then I get
`/usr/lib/chromium/chromium: error while loading shared libraries: libicuuc.so.69: cannot open shared object file: No such file or directory`

So I linked that as well, now I get:
`/usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: _ZN6icu_698TimeZone13createDefaultEv`

Are there still issues with the build in OBS?

**Comment by Iron-E** [comment] 2021-04-22 04:09
What does `pacman -Qs icu` say?

**Comment by git-bruh** [comment] 2021-04-22 04:09
@blipk You should update your `icu` package, the problems were due to chromium being linked against the old icu 68 (which you currently have on your system), now it's been relinked against icu 69.

**Comment by blipk** [comment] 2021-04-22 04:11
All my packages are up to date. Looks like icu 69 isn't in the main branches?

```
pacman -Qs icu
local/harfbuzz-icu 2.8.0-1
    OpenType text shaping engine (ICU integration)
local/icu 68.2-1
    International Components for Unicode library
local/lib32-icu 68.2-1
    International Components for Unicode library (32 bit)
```

**Comment by Iron-E** [comment] 2021-04-22 04:16
Hm… it should be on version 69. You can try `pacman -Syyu` to force refresh all repos, or manually download the latest versions from [here](https://archlinux.org/packages/core/x86_64/icu/).

**Comment by braewoods** [comment] 2021-04-22 04:18
It's due to the fact that they're using Manjaro. They are based on Arch but are always behind in their packages so they can't always use packages built against Arch.

**Comment by blipk** [comment] 2021-04-22 04:18
Apologies, forgot to mention I was on Manjaro, looks like their repositories are behind the main Arch ones.
Thanks anyway.

**Comment by Iron-E** [comment] 2021-04-22 04:19
Ahh I missed that. Thanks for catching me uo to speed!

**Comment by Eloston** [comment] 2021-05-29 18:53
Closing as resolved

**Closed by Eloston** 2021-05-29 18:53 UTC
