### ISSUE TITLE
Linux Simple build from 69.0.3497.100-2 - "Missing parentheses in call to 'print'"

### ISSUE THREAD

**Issue by jlj2** [Eloston/ungoogled-chromium#555] opened 2018-10-15 18:10 UTC
**Describe the bug**
When running `./ungoogled_packaging/build.sh`, output after c.15mins was interrupted, including: 
```
File "/tmp/ungoogled-chromium/build/src/tools/gn/build/gen.py", line 171
    print 'Installing Debian root image from %s' % url
                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Installing Debian root image from %s' % url)?
```

**To Reproduce**
Followed guidance for [Any Linux Distribution](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md#any-linux-distribution), except see Notes.

**Note 1:**  The system somehow seems to not accept filenames over c. 121 characters long, including extension.  Perhaps this is due to limitations of encrypting the **home** (and **/swap**) folders. 

_Preparation_
**Note 2:**  Python 2 & 3 and LLVM 6.0.1 were already installed, not 'LLVM 7.0 or 8.0';  hopefully LLVM 7.0.0 and 7.0.0-r1 can be avoided as they are unstable.

Ninja, Clang and LLD for Gentoo were installed, if correct:
```
$ sudo emerge dev-util/ninja clang lld
```

**Note 3:**  Although <code>packaging-dev</code> is mentioned for install in Debian higher up on that guidance page, its counterpart for Gentoo (<code>packaging</code>?) was not installed, as it is not listed in the *Any Linux Distribution* guidance section.

_Build_
```
$ cd /tmp
$ git clone https://github.com/Eloston/ungoogled-chromium.git
$ cd ungoogled-chromium
$ mkdir -p build/src
$ ./get_package.py linux_simple build/src/ungoogled_packaging
$ cd build/src
```
**Note 4:** No "export ..." parameters for "AR, NM, CC, CXX, or others" were specified; the compiler "defaults to LLVM tools" and, hopefully, this may be sufficient.
```
$ ./ungoogled_packaging/build.sh	
```

**Expected behavior**
To complete build without error and be able to continue with final steps:  
1. `./ungoogled_packaging/package.sh`
2. Untar the resulting tar archive to a long-term location (not `/tmp/.../`).

**Environment**
 - OS and version:  Calculate Linux 18 (Gentoo) on x86_64 AMD A10-4600M.
 - ungoogled-chromium version: 69.0.3497.100-2.
 - Packaging type: Aiming to build linux_simple.
 - Compiler toolchain: see Notes 2 & 4.

**Additional context**
More complete output:
```
$ ./ungoogled_packaging/build.sh	
[...]
2018-10-15 13:24:54,097 - INFO: * Applying relax-ninja-version-requirement.patch (114/116)
2018-10-15 13:24:54,098 - DEBUG: /usr/bin/patch -p1 --ignore-whitespace -i /tmp/ungoogled-chromium/build/src/ungoogled_packaging/patches/ubuntu/relax-ninja-version-requirement.patch -d .. --no-backup-if-mismatch --forward
patching file tools/gn/tools/gn/ninja_build_writer.cc
2018-10-15 13:24:54,103 - INFO: * Applying manpage.patch (115/116)
2018-10-15 13:24:54,104 - DEBUG: /usr/bin/patch -p1 --ignore-whitespace -i /tmp/ungoogled-chromium/build/src/ungoogled_packaging/patches/ungoogled-chromium/linux/manpage.patch -d .. --no-backup-if-mismatch --forward
patching file chrome/app/resources/manpage.1.in
2018-10-15 13:24:54,123 - INFO: * Applying remove-fcomplete-member-pointers-cflag.patch (116/116)
2018-10-15 13:24:54,123 - DEBUG: /usr/bin/patch -p1 --ignore-whitespace -i /tmp/ungoogled-chromium/build/src/ungoogled_packaging/patches/ungoogled-chromium/remove-fcomplete-member-pointers-cflag.patch -d .. --no-backup-if-mismatch --forward
patching file build/config/compiler/BUILD.gn
+ python3 -m buildkit domains apply -b config_bundles/linux_portable -c domainsubcache.tar.gz ../
2018-10-15 13:25:00,978 - DEBUG: Initialized logger 'buildkit'
2018-10-15 13:25:00,979 - INFO: Path has no substitutions: chrome/browser/plugins/plugins_resource_service.cc
2018-10-15 13:25:01,303 - INFO: Path has no substitutions: chrome/browser/safe_browsing/client_side_model_loader.cc
2018-10-15 13:25:01,885 - INFO: Path has no substitutions: chrome/common/page_load_metrics/page_load_metrics_util.cc
2018-10-15 13:25:02,885 - INFO: Path has no substitutions: components/dom_distiller/content/browser/dom_distiller_viewer_source.cc
2018-10-15 13:25:02,887 - INFO: Path has no substitutions: components/dom_distiller/core/html/preview.html
2018-10-15 13:25:02,891 - INFO: Path has no substitutions: components/domain_reliability/google_configs.cc
2018-10-15 13:25:02,967 - INFO: Path has no substitutions: components/google/core/browser/google_url_tracker.cc
2018-10-15 13:25:03,886 - INFO: Path has no substitutions: components/variations/net/variations_http_headers.cc
2018-10-15 13:25:26,531 - INFO: Path has no substitutions: net/tools/transport_security_state_generator/transport_security_state_generator.cc
2018-10-15 13:25:26,784 - INFO: Path has no substitutions: rlz/lib/lib_values.cc
2018-10-15 13:25:47,115 - INFO: Path has no substitutions: third_party/catapult/third_party/polymer/components/font-roboto/roboto.html
2018-10-15 13:25:48,830 - INFO: Path has no substitutions: third_party/catapult/tracing/third_party/gl-matrix/jsdoc-template/static/default.css
2018-10-15 13:25:50,654 - INFO: Path has no substitutions: third_party/crashpad/crashpad/doc/support/crashpad_doxygen.css
2018-10-15 13:26:12,621 - INFO: Path has no substitutions: tools/md_browser/base.css
2018-10-15 13:26:21,226 - INFO: Path has no substitutions: build/config/compiler/BUILD.gn
+ python3 -m buildkit gnargs print -b config_bundles/linux_portable
+ popd
/tmp/ungoogled-chromium/build/src
+ export AR=llvm-ar
+ AR=llvm-ar
+ export NM=llvm-nm
+ NM=llvm-nm
+ export CC=clang
+ CC=clang
+ export CXX=clang++
+ CXX=clang++
+ ./tools/gn/bootstrap/bootstrap.py -o out/Default/gn
  File "/tmp/ungoogled-chromium/build/src/tools/gn/build/gen.py", line 171
    print 'Installing Debian root image from %s' % url
                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Installing Debian root image from %s' % url)?
Traceback (most recent call last):
  File "./tools/gn/bootstrap/bootstrap.py", line 92, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/gn/bootstrap/bootstrap.py", line 78, in main
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/lib/python-exec/python3.6/python', '/tmp/ungoogled-chromium/build/src/tools/gn/build/gen.py', '--no-last-commit-position', '--out-path=/tmp/ungoogled-chromium/build/src/out/Release/gn_build', '--no-sysroot']' returned non-zero exit status 1.
```

**Comment by ian-moone** [comment] 2018-10-15 23:47
@jlj2 You'll better off if you try one of those [`ungoogled-chromium*`](https://gitlab.com/chaoslab/chaoslab-overlay/tree/master/www-client) ebuilds.

**Comment by jlj2** [comment] 2018-10-16 01:43
As users are advised to become more cautious about whether to trust sources, binaries, etc., users should be able to understand and check what is downloaded before running it.

So, @ian-moone, to help trust that ebuild, please spell out what would be substituted in for this system for the `{PN}` parameter in your [ebuild](https://gitlab.com/chaoslab/chaoslab-overlay/blob/master/www-client/ungoogled-chromium/ungoogled-chromium-69.0.3497.100-r1.ebuild) at line 23:
	`https://github.com/Eloston/${PN}/archive/${UGC_PV}.tar.gz -> ${UGC_P}.tar.gz`
How `${PN}` is defined is not clear to me.  
Also, please explain your strapline, ['The cancer is coming!'](https://github.com/ian-moone)  Thank you, @ian-moone.  

My original question remains, however.

**Comment by ian-moone** [comment] 2018-10-16 02:09
> As users are advised to become more cautious about whether to trust sources, binaries, etc., users should be able to understand and check what is downloaded before running it.

👍 

> How `${PN}` is defined is not clear to me.

It's a [standard variable](https://devmanual.gentoo.org/ebuild-writing/variables/index.html) in portage build system.

> Also, please explain your strapline, ['The cancer is coming!'](https://github.com/ian-moone)

Well that's a bit off-topic. Anyways, it's just a sarcastic expression to reference Microsoft's GitHub acquisition.

**Comment by jlj2** [comment] 2018-10-16 03:09
@ian-moone, thank you kindly. Now, __https://github.com/Eloston/ungoogled-chromium/archive/69.0.3497.100-2.tar.gz__ is interpreted to be downloaded by your ebuild.

Running a comparison between extracted versions of that download and a .zip download of the currently displayed [ungoogled-chromium-master](https://github.com/Eloston/ungoogled-chromium), differences appear:-
```
 $ diff -qr ../ungoogled-chromium-69.0.3497.100-2/ungoogled-chromium-69.0.3497.100-2/ ungoogled-chromium-master/ |sort
Files ../ungoogled-chromium-69.0.3497.100-2/ungoogled-chromium-69.0.3497.100-2/docs/building.md and ungoogled-chromium-master/docs/building.md differ
Files ../ungoogled-chromium-69.0.3497.100-2/ungoogled-chromium-69.0.3497.100-2/docs/design.md and ungoogled-chromium-master/docs/design.md differ
Files ../ungoogled-chromium-69.0.3497.100-2/ungoogled-chromium-69.0.3497.100-2/docs/developing.md and ungoogled-chromium-master/docs/developing.md differ
Files ../ungoogled-chromium-69.0.3497.100-2/ungoogled-chromium-69.0.3497.100-2/README.md and ungoogled-chromium-master/README.md differ
Only in ../ungoogled-chromium-69.0.3497.100-2/ungoogled-chromium-69.0.3497.100-2/.github: issue_template.md
Only in ungoogled-chromium-master/docs: contributing.md
Only in ungoogled-chromium-master/.github: ISSUE_TEMPLATE
Only in ungoogled-chromium-master/.github: PULL_REQUEST_TEMPLATE.md
Only in ungoogled-chromium-master/packaging/linux_simple: package.appimage.sh.ungoogin
Only in ungoogled-chromium-master/packaging/linux_simple: ungoogled-chromium.yml
Only in ungoogled-chromium-master/: SUPPORT.md
```
If those variations could be explained, it would help, but this is not a forum to dwell into them.  

Thank you for kindly explaining your strapline, @ian-moore.  

Thanks to all for your efforts to hopefully resolve the original issue re ungoogled-chromium source code.

**Comment by ian-moone** [comment] 2018-10-16 03:38
> If those variations could be explained, it would help, but this is not a forum to dwell into them.

It's easy to explain. The ebuild uses the tagged/released tarball. In this case, the commit 009c8e19255a8a0255ec0be40eb4872471318463 is `69.0.3497.100-2`. The master _zip_ archive contains the latest changes, so naturally won't be the same.

Since the last tagged version (`69.0.3497.100-2`), the master branch has the  following changes https://github.com/Eloston/ungoogled-chromium/compare/009c8e19255a8a0255ec0be40eb4872471318463...2ce08944aebdb704c1cd66e2515f6d2cf32c2d88, which certainly will match your _diff_ above.

**Comment by intika** [comment] 2018-10-16 18:03
Yeah it depend what version tag you are downloading, on the main repo you can chose the version tag before downloading the zip and then you should have the exact same version.

Now going back to your issue, it seems that you have a python issue probably the used version of python is not good

can you please check what's the output of `python --version ` otherwise try to link the compiling script to the right version of python or link your /usr/bin/python to the right version... note that you will need python 3.6.6

Let me know if this solve your issue ;)

**Comment by jlj2** [comment] 2018-10-16 18:54
Thank you @ian-moone and @intika.
Apologies to @ian-moore.

@intika, You are correct:
```
$ python --version
Python 3.6.5
```
Could a stated software requirement for [Any Linux Distribution](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md#any-linux-distribution), _'Python 3 (tested on 3.5)'_, need to be updated regarding the current Linux Simple release, unless the absence of LLVM 7.0 on this system is relevant?

As 3.6.6 and above are currently marked as unstable for this OS, I am withholding installing ungoogled-chromium for now.

**Comment by intika** [comment] 2018-10-16 21:17
@jlj2 normally the gn python code should be run with python 2.7 not with python3... something is missing on your system, can you post what's the output of `python2 --version` i am not sure if 3.6.6 is really required it's the version i am using to build UC. 

You will need LLVM 7 later in the building process so after solving you will probably have other errors because of llvm

**Comment by intika** [comment] 2018-10-17 02:34
@jlj2 it's not a problem thank you for your kindness, and don't worry we will figure that out and you will get it build ;) at least i am sure that you will with v68 (if you don't want to upgrade llvm)

The thing is that GN Script is using python v2 it's intended to work that way, it's possible to convert that script to python v3 but it's a lot of work for nothing. we just need to figure out why python 3 is used at that moment in your machine... 

Note python v2 syntax differ from v3 it's why you are having that issue and why GN script is not working...  

okay here is something you can try instead
- Start again from scratch
- At step build.sh before running the (./ungoogled_packaging/build.sh)
- Edit ./ungoogled_packaging/build.sh	and delete 3 last lines or comment them with `#` here are the lines i am talking about
```
./tools/gn/bootstrap/bootstrap.py -o out/Default/gn
./out/Default/gn gen out/Default --fail-on-unused-args
ninja -C out/Default chrome chrome_sandbox chromedriver
```
- Run the build script it should work just fine... (at least you will have a build dir ready to manipulate you don't have to start from scratch every time and wait 15 min) 
- Run the next command manually (instead of `./tools/gn/bootstrap/bootstrap.py -o out/Default/gn` run `python2 ./tools/gn/bootstrap/bootstrap.py -o out/Default/gn`
- if it works just run the 2 last commands manually 

Let me know if it worked, if it's the case i will PR build script with the modifications to fix that... for users who have python3 set as main python command

**Comment by Eloston** [comment] 2018-10-17 16:44
Arch Linux has the same problem where `python` points to Python 3 instead of Python 2. As a result, the PKGBUILD for Arch Linux modifies the Chromium source tree to use `python2`. I do not recommend modifying your system to make `python` point to Python 2.

**Comment by intika** [comment] 2018-10-18 00:10
@jlj2 
First thing first here is some infos about switching default python version temporarily... 
https://stackoverflow.com/questions/7237415/python-2-instead-of-python-3-as-the-temporary-default-python 
and 
https://stackoverflow.com/questions/36278220/how-to-switch-to-python2-in-a-particular-terminal-window-temporarily

Now going back to your build... first 
> ERROR:root:Git error: rc=0, output=''
This one is normal we all have that, just ignore that... 

For the error 
> FAILED: gen/third_party/blink/renderer/platform/color_data.cc 

You probably missing a package/python-module... (in this case i think the missing package is gperf-native) and you will probably have other errors later for other missing packages / out dated package version... so to accelerate a little bit the whole thing you can install all needed dependency to build chromium/uc with some commands... there is an aur package https://aur.archlinux.org/packages/ungoogled-chromium for UC 

You can use that command to get what package is missing 
`makepkg -s PKGBUILD` 
```
      -s, --syncdeps
           Install missing dependencies using pacman. When build-time or run-time dependencies are not found, pacman
           will try to resolve them. If successful, the missing packages will be downloaded and installed.
```
there is also an other command to install dependency for building a package there is `emerge -o package-name` replace package name with chromium or chromium-browser depending on how the package is named on gentoo 

After getting the missing dependency you can run once again the build as you did or use the aur i linked... 

Let me know what's next ;)

**Comment by jlj2** [comment] 2018-10-19 03:43
Thanks for showing me along the way, @intika, but questions (Q4)-(Q6) below could be the most relevant at this point.  

Thank you also for the interesting and practical solutions to use python 2 instead of python 3.  Maybe `virtualenvwrapper` could be the most appealing choice, if need be.

> so to accelerate a little bit the whole thing you can install all needed dependency to build chromium/uc with some commands... there is an aur package https://aur.archlinux.org/packages/ungoogled-chromium for UC

Linux Simple UC was being built with chromium 69.0.3497.100 already installed with a view to uninstalling it before untaring the target build, so presumably all dependencies were already installed?  Linux Portable UC 69 didn't install any dependencies that I know of (without chromium installed at the time!), so I thought that Linux Simple UC wouldn't require any either.

A list of chromium dependencies is indeed given at that link, but (Q1) if you mean that `makepkg -s PKGBUILD` could be a quick way to determine which are 'missing' dependencies (despite chromium 69 operating ok!), how could I run **makepkg**, seeing that it isn't in the Gentoo repository? (Q2)  Wouldn't `makepkg -s PKGBUILD` also need `ungoogled-chromium` or `chromium` as an argument?  (Q3) If so, what is the syntax?

A backup could be done to proceed, but the link you suggested to build LLVM 7 lists python 2.7 as a [prerequisite](https://llvm.org/docs/GettingStarted.html#software), which is missing on my system and is not planned to be installed.  Maybe once my python 2 is upgraded I will.

> Note II : Also as you are using llvm 6 you can directly try to build v68 just use 'git checkout 68...' after cloning the project... 

Thanks anyway for trying to help those in a situation like mine, @intika;  v68 could be a fallback.  (Q4) Could you please spell out that command, as I am not familiar with 'after cloning the project', and the last tagged v68 source code tagged is 68.0.3440.106-2, e.g.:
```
$ git clone https://github.com/Eloston/ungoogled-chromium.git
$ git checkout 68.0.3440.106-2
$ cd ungoogled-chromium
etc
```

(Q5) Another alternative:  what do you think about using ebuilds offered for gentoo, as suggested earlier, which may address environments like mine with python 2.6.5 and llvm 6.0.1?

Well, this was thought to be a bug report, but it isn't identified as that yet.  (Q6) Is it because my system is missing python 2.7 and LLVM 7?  Or is it kept open to try to solve situations with systems that 'default' to python 3 (as signalled earlier re Arch systems)?  Despite your continued help, my interest to keep stable python 2.6.5 seems to mean that there is no way forward for Linux Simple UC v69 here.  Even some temporary install of python 2.7 in order to build LLVM 7 is not appealing.

Thank you very much anyway for all your help, @antika, and have a great Friday and weekend!

**Comment by intika** [comment] 2018-10-19 06:04
@jlj2 
> (Q1)-(Q2)-(Q3)

There is 2 levels of dependency for every package the first level is usage level and the second is build level... so if you just want to use a package you will be installing the depended on packages, but in the other hand if you want to build the package you will need a whole other set of packages like devel one etc. so having chromium installed does mean that you have all the needed packages to build it and it's often not the case. those commands i gave you are used to install required packages for building purpose. UC and Chromium need the same packages to be built so you don't need to have UC on your distro repo just install dependency of chromium and you should be good to go. i am not using an Arch based system, i can't test to give you the exact syntax... just for info in my system i use `dnf builddep chromium-browser` in your system the command should be something like `makepkg -s chromium-browser`
 
> A backup could be done to proceed, but the link you suggested to build LLVM 7 lists python 2.7 as a [prerequisite](https://llvm.org/docs/GettingStarted.html#software), which is missing on my system and is not planned to be installed. Maybe once my python 2 is upgraded I will

You already have python 2.7... you will just probably need to set it as default during build like you do for UC

```
$ python2 --version
Python 2.7.15
```

> V68 could be a fallback. (Q4) Could you please spell out that command, as I am not familiar with 'after cloning the project', and the last tagged v68 source code tagged is 68.0.3440.106-2, e.g.

```
git clone https://github.com/Eloston/ungoogled-chromium.git
cd ungoogled-chromium
git checkout tags/68.0.3440.106-2
```
> (Q5) Another alternative: what do you think about using ebuilds offered for gentoo, as suggested earlier, which may address environments like mine with python 2.6.5 and llvm 6.0.1?

Yes of course you could do that... if you have unsolved building issue with the ebuilds you could fall back to what we are doing here ;) 

> Well, this was thought to be a bug report, but it isn't identified as that. (Q6) Is it because my system is missing python 2.7 and LLVM 7? Is it kept open to try to solve situations with systems that 'default' to python 3 (as signalled earlier re Arch systems)? Despite your continued help, my interest to keep stable python 2.6.5 seems to mean that there is no way forward for Linux Simple UC v69 here. Even some temporary install of python 2.7 in order to build LLVM 7 is not appealing.

It will be probably closed when @Eloston will have the time to and/or when your specific issue will be solved :D... this is not a bug but an issue about helping you building the project :D "Help needed" tag will be probably added to this issue later... outdated dependency is not a bug indeed but it's always a good to have work around for other users with the same issue :) ... now regarding default python 2/3 this is not a bug either as @Eloston already mentioned `PKGBUILD for Arch Linux modifies the Chromium source tree to use python2` so it's solved on specific PKGBUILD ... now this topic is helpful for any system that have python3 set to default ;)

> Thank you very much anyway for all your help, @antika, and have a great Friday and weekend!

You are welcome, have a great weekend too ;)

**Comment by Eloston** [comment] 2018-10-19 17:03
Here is my rough tl;dr for this issue:

This issue is mainly dealing with Chromium build tools (i.e. in the source tree) using Python 3 instead of Python 2, which is solvable by either:

1. Making `python` in PATH be Python 2
2. Modifying the Chromium source tree so it uses `python2` to invoke Python 2 (like Arch Linux does in its package build).

Also, there are some minor issues with getting a new fLLVM, Python 2.6 vs 2.7 (with the latter being required), and installing all other required build tools (e.g. gperf). 

From a broader perspective, the issue topic shifted from a bug report to a support thread for setting up the build environment for @jlj2.

Everything looks solved now. Closing.

**Closed by Eloston** 2018-10-19 17:03 UTC
