### ISSUE TITLE
Use an open build service or CI system

### ISSUE THREAD

**Issue by Alvintrmp** [Eloston/ungoogled-chromium#17] opened 2016-06-06 04:46 UTC
Somepeople has ancient computers and can't compile ungoogled with his computer

because chromium EVEN with a good pc need some hours  

for let more people  enjoy your software

i suggest you  try to make compatible ungoogled with a popular build service´such as opensuse build service

thanks for read my suggestion

**Comment by Eloston** [comment] 2016-06-06 05:05
Are you suggesting to use an open build platform to support more systems? If so, what systems and what build platforms do you recommend?

It's not a bad idea considering the hassle of building it myself. I'll need one or some that provides Debian Stretch, Ubuntu Xenial, and Windows environments.

**Comment by Alvintrmp** [comment] 2016-06-06 16:11
opensuse build service supports   debian 7-8, ubuntu 15.10-16.04, centos 6-7,  fedora 22-23, oepnsuse 13.1-1.2, tumbleweed and arch linux  


and gives an extra advantage, lets users of ancient computers "or without huge amounts of ram"   compile them, because the buildscript used for now requires  a good cpu and many ram "intel i5 + 16gm ram delays 5 hours"

**Comment by Alvintrmp** [comment] 2016-06-06 16:12
as i think  would fine  give support  "ading to the default chromium .src.rpm"     the patches for opensuse and fedora,  or at least arch   


that lets anybody enjoy it   "without a good hardware"

**Comment by Eloston** [comment] 2016-06-06 18:54
I'll look into using OpenSUSE Build Service for building Debian 8 and Ubuntu 16.04 packages for now. I still have some work to do to make support for other platforms easier, and I still need to finish work on Chromium 51.

**Comment by Alvintrmp** [comment] 2016-06-06 19:01
this junk of clear-http-auth-cache-menu-item.patch  isn't compatible with chromium 51

@@ -92840,6 +92841,7 @@ To add a new entry, add it with any value and run test to compute valid value.
     </obsolete>
   </suffix>
   <suffix name="Cast"/>
+  <suffix name="ClearHttpAuthCache"/>
   <affected-histogram name="WrenchMenu.TimeToAction"/>
 </histogram_suffixes>
 
i am trying patches "and reading bugs"

**Comment by Eloston** [comment] 2016-06-06 20:25
Please open another bug report for that.

**Comment by Eloston** [comment] 2016-09-30 18:43
For reference: There is some discussion about Travis-CI  and Launchpad over on #37.

**Comment by Eloston** [comment] 2018-03-02 08:58
There currently isn't a need for this right now. GitLab CI can handle Linux builds, or push to other platforms that can create other packages. Also, none of the other platforms need an automated process right now.

**Comment by Eloston** [comment] 2018-10-24 18:01
In recent months, I've changed my stance on this issue. Having CI would boost development productivity and shorten the time needed to build and publish binaries ourselves.

Right now, there are several sub-ideal scripts I wrote to do sanity checking using CircleCI, but it would be better to actually run builds. It doesn't need to be after every commit; it could be done weekly or after a new tag is published for now.

I'm open to suggestions. Free plans from TravisCI and many other systems are out of the question because Chromium takes quite a bit of computational resources compared to that of most other free CI jobs (CPU, RAM, storage, and time). I also don't want to take the responsibility of maintaining this system, especially if it means I need to manage a paid plan and the funds that go into them.

**Comment by devnoname120** [comment] 2018-10-25 20:41
Related: https://github.com/ungoogled-software/ungoogled-chromium-binaries/issues/30

**Comment by intika** [comment] 2018-10-25 23:03
> Related: [ungoogled-software/ungoogled-chromium-binaries#30](https://github.com/ungoogled-software/ungoogled-chromium-binaries/issues/30)
> 
> > Free plans from TravisCI and many other systems are out of the question because Chromium takes quite a bit of computational resources compared to that of most other free CI jobs (CPU, RAM, storage, and time)
> 
> I would suggest asking them anyway, we never know what they might answer.

Send a request referring to this and let us know... but i don't think they will answer with a offer that will build the project in a reasonable time

**Comment by intika** [comment] 2018-10-25 23:29
Now i have an idea... google-cloud-computing offer a cli to manage servers and they bill only when the server is running, i could make some script that will automate the whole process BUT never the less this will cost approx 1~2 euros per build... 

basically it's what i am doing manually to build the releases that i published... 

Thinking of 2 releases per month time the different releases 1,5€ x 2 releases x 10 builds = 30€/month a financial solution could using "google search" to be payed back. 

All this to come back to what @Eloston have posted 
> I also don't want to take the responsibility of maintaining this system, especially if it means I need to manage a paid plan and the funds that go into them.

So to make it simple is there any volunteer for that ?

Note : in my personal situation i don't want to assume that (even if i do that manually from time to time)


We could setup a paypal donation account or something similar, but 
1. is @Eloston okay with such a solution ?
2. is there any volunteer to manage that account ?


Other Idea : a designated packagers team... 
(in my case i can not guarantee that i will build every release)

**Comment by Eloston** [comment] 2018-10-26 01:53
@intika 

> Other idea : setup something like a "button to build and publish" that would cost 2€ and any user can click it and pay to automatically build and publish hahahahaha never the less its doable (we will see a build popping up every day lol)

This is an interesting idea; have the user pay for computational power to run a predefined process. However, I'm not sure if users would be willing to pay for builds; the technically-able could just purchase computing power themselves, so people who aren't as knowledgeable would be the main audience. I'm not sure what the main audience would like in this scenario.

Your other ideas are not bad, but they ultimately create more responsibility for at least one of us; examples of responsibilities include:

* Upholding a title (e.g. designated packager)
* Maintaining hardware (e.g. dedicated server)
* Working with people (e.g. sponsor). I already have enough with what I do on GitHub.

I think the best solution here is something that creates minimal responsibilitiy for us (financially and socially), and is sustainable for the provider (e.g. a CI service, volunteer, etc.). I realize that these requirements are pretty atypical (normally someone has to dedicate some part of their lives and resources to maintain this sort of thing), but I personally don't believe the benefits from a better CI system outweighs the dedication required.

**Comment by devnoname120** [comment] 2018-10-26 07:31
@intika I don't feel comfortable asking on the behalf of a project I'm not the owner of (I'm not even a contributor).

**Comment by intika** [comment] 2018-10-26 10:30
> but I personally don't believe the benefits from a better CI system outweighs the dedication required.

Agree 100%
@Eloston i love the way you write its amazing and aspirating, english is not my mother lang but i would love to be able to write like you :) ... you should write a book lol :D :yum: :dancing_women: 

> @intika I don't feel comfortable asking on the behalf of a project I'm not the owner of (I'm not even a contributor).

@devnoname120 You are a contributor participating to this by you answers etc. :+1: 

> ...

@Alvintrmp @devnoname120 @ArjonBu @ryneeverett @9Morello @lenormf @alexbakker @d33tah @RobinThrift @pizzadude @hrj @podshumok @MikolajQ @kirylpl @Lesik @zabbal @message @pseudoj @T-vK @metsatron @mtimofiiv @fedenko @sixtyfive  @olosz @dannycolin  @raininja @nyancat18 and all others and any one interested in this... 

Any one willing to pay for builds ?

**Comment by hrj** [comment] 2018-10-26 11:51
@intika Great to see your enthusiasm. I can chip in about 5 to 10 USD per month and send it to any paypal account designated by @Eloston or @intika .

If we are able to collect the target of 30€/month, then fine. Otherwise, we can choose a smaller server and live with increased build time for now. Instead of 15 min per build, it might be 2 hours per build.

IMO the important thing is to get the ball rolling.

**Comment by alexbakker** [comment] 2018-10-26 12:01
Asking DigitalOcean for some free credits on their platform may be worth a shot. They're known to support lots of open source projects.

**Comment by T-vK** [comment] 2018-10-26 12:03
It wouldn't really be a problem to set up a private GitLab instance on a $5/month VPS, but we would need a maintainer who we can trust and who always ensures that the latest security patches are installed. And honestly there are not many people who I would trust enough to blindly load their binaries onto my computer. 
In my opinion we should use a trusted service that takes care of the CI process. I'm not even sure if it would be necessary to pay for it at all. For instance, once #37 is resolved, we would be able to fully automate builds and distribution for Ubuntu, just by using a free gitlab.com account and launchpad.net.

**Comment by sixtyfive** [comment] 2018-10-26 12:16
Whatever you feel you should do, you should do. Because in turn, at the moment there doesn't seem to be an awful lot of trust in you from the side of distributions. At least Solus think it's better to stay away from ungoogled-chromium: https://dev.getsol.us/T1117 .

**Comment by Eloston** [comment] 2018-10-26 17:19
@hrj brings up a good point; we need to get something going to make progress. As @T-vK brought up, we are pretty close to having an automated system for making .deb packages with GitLab and Launchpad; opening this channel for builds will help in bringing more users. Having more users helps with exposure, which in turn helps with development; it opens the possibility for a virtuous cycle of improvement. This should help build trust, which @sixtyfive and @intika brought up.

After #37 gets resolved (or even simultaneously), we could consider solutions like the ones @alexbakker  brought up to setup automated builds for more configurations.

**Comment by ArjonBu** [comment] 2018-10-26 17:21
@intika Why did you tag me? 

BTW Just use the opensuse build service.

**Comment by intika** [comment] 2018-10-26 19:37
> @intika Why did you tag me?
> 
> BTW Just use the opensuse build service.

Why not ! lol ... (just joking... i tagged you because of https://github.com/Eloston/ungoogled-chromium/issues/59)

**Comment by hrj** [comment] 2019-01-29 03:32
Regarding the financial and legal overhead of managing something like this:

I came across [OpenCollective](https://opencollective.com/) today, which might be suitable for this project. In a nut shell, they "host" a collective, which means they take care of the bank account and accounting hassle. People who incur costs for the collective can raise an invoice, and the collective's admin can approve the invoice. Once approved, the funds for the invoice are released. People who want to donate to the collective get more transparency.

A good article explaining it is [here](https://venturebeat.com/2017/04/05/open-collective-is-a-gofundme-like-service-for-open-source-projects/)

If there is interest and approval, especially from @Eloston, I will be happy to setup a collective for this project and see how it flies.

**Comment by Eloston** [comment] 2019-01-29 07:14
@hrj This is an interesting concept; thanks for sharing. However, I don't quite understand what value my approval has on this; what kind of responsibility would I incur as a result?

In addition, based on the article you linked, it seems that OpenCollective is targeted more towards funding developers rather than infrastructure itself. Are there similar cases to this on OpenCollective?

**Comment by hrj** [comment] 2019-01-29 15:18
@Eloston It is definitely useful for infrastructure. I have seen collectives which have invoices for `loomio` for example. Here's another collective that was started for paying hosting and domain costs: https://www.reddit.com/r/ponylang/comments/9nw2uy/pony_is_a_now_a_member_of_opencollective_looking/

About approval, I just meant informal approval, that is, confirmation that you don't mind something like this.

I tried creating a collective for my own projects, but it requires some github permissions to the repo. So, I probably won't be able to create a collective for this repo. You, or somebody with contributor permission to the repo, will have to initiate the creation.

**Comment by Eloston** [comment] 2019-01-29 18:24
@hrj I looked into the GitHub permissions they use, and it seems they require a lot of permissions to work properly right now: https://github.com/opencollective/opencollective/issues/355

If we're going to use this, I'd rather we enable this on a mirror of this repository until the permissions are more reasonable. But, would this cause any major issues?

**Comment by marataziat** [comment] 2019-06-12 17:31
I think travis ci is the most trusted CI! We can use it for free!!  https://travis-ci.com/plans
> Always free for open source projects

**Comment by tonowoe** [comment] 2019-06-14 10:16
> I think travis ci is the most trusted CI! We can use it for free!! https://travis-ci.com/plans
> 
> > Always free for open source projects

How does that work? Someone just can use their service to build open source project (like ungoogled-chromium) for multiple systems for free?

**Comment by sixtyfive** [comment] 2019-06-14 11:08
Just one click on that link and it asks you for GitHub authorization...

**Comment by zrose584** [comment] 2019-11-11 13:26
Really I think OBS is the solution here:
  - completly free, costs nothing
  - integrates nicely into native package-manager (apt, pacman, dnf, ...)
  - supports 15 different distros (debian, ubuntu, arch, fedora, ...)
  - one can [specifiy](https://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.build_job_constraints.html) how much resources/memory is needed (no out-of-memory errors)
  - extra:
	* has plans to [support windows](https://en.opensuse.org/openSUSE:Build_Service_Concept_Windows_Support)
	* opensource: [frontend](https://github.com/openSUSE/open-build-service) and [build-tool](https://github.com/openSUSE/obs-build)
		This allowed me realise that one can control the buildprocess in detail via [build.script](https://github.com/openSUSE/obs-build/blob/8a202fcd163c074b1013324badb635fdcc516cc7/build-recipe-dsc#L99) for .debs (ok, docs could do this too).

___

I am aware that others have alredy suggested the use of OBS.
Maybe a [working example](https://build.opensuse.org/package/show/home:zrose584/ungoogled-chromium) can help.

Some things to keep in mind:
  - the build-process has no internect connection, but one can use [services](https://en.opensuse.org/openSUSE:Build_Service_Concept_SourceService) to download arbitrary files.
  - one currently has no easy way to add external or backports repositories.
    But on can create a package (on OBS) for the missing/outdated dependencie and then link to it.  
    See [here](https://en.opensuse.org/openSUSE:Build_Service_Tutorial): `The Build Service provides a few different ways to facilitate handling of these [external] dependencies. [...]`
  - if using gcc, one requires at least 12GB RAM, while clang only requries 10GB RAM (hardware + swap).
    btw, gcc also produces 14% larger binaries and takes 7% longer to build.


A good resource for getting started is [this](https://en.opensuse.org/openSUSE:Build_Service_Tutorial).

___

After everything is done, installing is as easy as
```
curl https://build.opensuse.org/projects/home:zrose584/public_key | sudo apt-key add -
echo "deb https://download.opensuse.org/repositories/home:/zrose584/Debian_10 ./" | sudo tee -a /etc/apt/sources.list
sudo apt-get update

sudo apt-get install ungoogled-chromium ungoogled-chromium-common
```

And since using `apt`, future updates will be installed automatically.
Not to mention that these builds are reproducable, so you don't have to trust an unknown person when using prebuild binaries.

**Comment by jstkdng** [comment] 2019-11-28 23:53
+1 on the OBS solution, and the openSUSE folks even have a nice landing page for each project, e.g. my repo for arch.
![image](https://user-images.githubusercontent.com/52050345/69835475-f6a46600-120f-11ea-8de1-eda16d2385d5.png)
https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home%3Ajustkidding
With this maybe we could even replace the ungoogled-chromium-binaries repo.
We could manage all binaries for each distribution, not sure how to do it. Maybe create a UngoogledChromium project and add packages for each distribution.

**Comment by Eloston** [comment] 2020-06-24 23:44
I think this can finally be closed now as each platform is starting to integrate OBS or other solutions.

**Closed by Eloston** 2020-06-24 23:44 UTC
Labels: enhancement, help wanted
