### ISSUE TITLE
macOS  URL bar is black text on a black background

### ISSUE THREAD

**Issue by jrdmcgr** [Eloston/ungoogled-chromium#536] opened 2018-09-29 00:48 UTC
#### ungoogled-chromium version: 

Version 68.0.3440.106 (Official Build) (64-bit)

#### Configuration and/or platform(s): 

macOS

### Problem description

My URL bar is black text on a black background.

<img width="1437" alt="screen shot 2018-09-28 at 8 45 35 pm" src="https://user-images.githubusercontent.com/382637/46238942-c9380000-c35f-11e8-8361-c8d11544d996.png">

**Comment by csmk** [comment] 2018-09-29 01:01
Duplicate of https://github.com/Eloston/ungoogled-chromium/issues/525

**Closed** 2018-09-29 03:55 UTC
Labels: duplicate
