### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID broken in 102.0.5005.61

### ISSUE THREAD

**Issue by ih8ms** [Eloston/ungoogled-chromium#1981] opened 2022-05-31 16:58 UTC
### OS/Platform

Portable Linux

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

102.0.5005.61

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Wrong behaviour of NET::ERR_CERT_AUTHORITY_INVALID

### How to Reproduce?

1. Open an URL with self signed certificate, e.g. https://self-signed.badssl.com/

### Actual behaviour

The following page is displayed:

### This site can’t be reached
The webpage at **https://self-signed.badssl.com/** might be temporarily down or it may have moved permanently to a new web address.
ERR_CERT_AUTHORITY_INVALID

### Expected behaviour

The following page should be displayed (works as expected in Chrome 102.0.5005.61):

### Your connection is not private
Attackers might be trying to steal your information from self-signed.badssl.com (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_AUTHORITY_INVALID
To get Chrome’s highest level of security, [turn on enhanced protection](chrome-error://chromewebdata/#)
[Advanced] [Back to safety]

### Additional context

Running on Linux, installed from https://github.com/macchrome/linchrome

**Comment by networkException** [comment] 2022-05-31 17:00
Duplicate of #1974, this has already been addressed by #1976 and got released as a fix in release 102.0.5005.61-3

**Closed as completed by networkException** 2022-05-31 17:00 UTC
Labels: bug, duplicate
