### ISSUE TITLE
uBlock Origin "Adding to Chromium..." > Install Never Completes

### ISSUE THREAD

**Issue by bburt91** [Eloston/ungoogled-chromium#984] opened 2020-03-29 21:19 UTC
Windows 10 1909
Ungoogled-chromium version 80.0.3987.132
Developer Mode enabled in chrome://extensions
Always Prompt for Install enabled in chrome://flags

When adding uBlock Origin via CRX URL, Chromium attempts to add the extension but never finishes. I have successfully set up ungoogled-chromium with UBO on two other machines running Linux (Arch and Ubuntu). This issue only occurs on my Windows desktop.

Also, unable to drag 'n drop to chrome://extensions. 

![reffe](https://user-images.githubusercontent.com/54790276/77861199-1a38e680-71d9-11ea-8292-cc8d280ff059.png)

**Comment by PF4Public** [comment] 2020-03-30 08:54
Duplicate of #923 and ungoogled-software/ungoogled-chromium-windows#23

**Comment by ianpan870102** [comment] 2020-03-30 14:21
I faced the same issue earlier today. But after restarting my computer, it worked all right -- worth giving a try

**Comment by bburt91** [comment] 2020-03-31 03:43
> I faced the same issue earlier today. But after restarting my computer, it worked all right -- worth giving a try

Gave this a go, no dice, unfortunately.

**Comment by Eloston** [comment] 2020-04-02 02:34
Unfortunately you'll need to unpack all extensions to install them on Windows.

Closing as duplicate.

**Closed by Eloston** 2020-04-02 02:34 UTC
