### ISSUE TITLE
Trying to install versions >55 in stretch fail

### ISSUE THREAD

**Issue by 133794m3r** [Eloston/ungoogled-chromium#268] opened 2017-10-05 21:20 UTC
It complains about libnettle4 being installed for _some_ reason.

```
dpkg: regarding chromium_57.0.2987.110-1_amd64.deb containing chromium:
 chromium conflicts with libnettle4
  libnettle4:amd64 (version 2.7.1-5+deb8u2) is present and installed.

dpkg: error processing archive chromium_57.0.2987.110-1_amd64.deb (--install):
 conflicting packages - not installing chromium
Errors were encountered while processing:
 chromium_57.0.2987.110-1_amd64.deb

```

**Comment by Eloston** [comment] 2017-10-07 11:21
Duplicate of #242

**Closed by Eloston** 2017-10-07 11:21 UTC
