### ISSUE TITLE
Portability under Windows OS

### ISSUE THREAD

**Issue by caada** [Eloston/ungoogled-chromium#444] opened 2018-08-01 07:11 UTC
I use Chrome as a portable application under WIndows OS. In the past Chrome was partially portable. If chrome browser was moved to another system, extensions were kept. Although, some settings were reset, it was good enough. 

Version 55 of the ungoogled chrome was portable. However, after version 60 or so Chrome became unportable. When chrome is carried to another system, chrome deletes the extensions. I think google is checking file "Secure Preferences" for system changes, but I am not sure.

There are a few chrome based browsers that are portable such as Opera, maybe that would give an idea what needs to be changed.

I like ungoogled chrome, but because of portability, I am stuck at version 55. I am not able to use the latest builds.

If someone can look at what needs to be done, I will be happy.  

Thanks.

**Comment by Eloston** [comment] 2018-08-05 03:38
Hmm, this is interesting.

Is Brave Browser portable?

**Comment by caada** [comment] 2018-08-06 09:34
I downloaded the Brave browser yesterday. I made it portable. I changed the settings and modified the extensions. I copied to 3 computers. And settings and extensions are preserved. So, yes Brave is portable as far as I tested. 

Based on my research, people are saying related file is pref_hash_store_impl.cc and functions are GenerateDeviceId 
GetDeterministicMachineSpecificId 
LookupAccountNameW

**Comment by Eloston** [comment] 2018-08-08 18:04
Thanks for testing, and the technical details. I may be able to propose a patch later once my current tasks are complete, but I don't have a machine to make a Windows build with right now.

Feel free to submit a PR before then.

**Comment by octopuserectus** [comment] 2018-09-06 19:33
I think you can achieve portability by using this launcher, it keeps everything in one folder: https://github.com/henrypp/chrlauncher
I am not sure though, but I think it worked fine on another system when I tried it some time ago.

**Comment by caada** [comment] 2018-09-06 21:26
"chrlauncher"

is not portable accross systems. chrome is checking for system change lately. 

Thanks for the suggestion.

**Comment by mehrdadn** [comment] 2018-10-01 05:52
I just realized my issue (#538) is essentially a duplicate of this one. I believe the patch I suggested there should solve this problem.

**Comment by Eloston** [comment] 2018-10-01 16:41
@mehrdadn Thanks for your solution. Did you have this problem on a non-Windows platform?

Also, do you have an idea why Google decided to have this feature? If there's a technical reason for this feature, then it may be problematic to enable it by default.

**Comment by mehrdadn** [comment] 2018-10-01 16:45
I believe it's performed only on Windows (but I don't know for sure) and the rationale is to prevent external programs from messing with preferences. I think that wasn't common in other platforms, hence why it occurs only on Windows.

**Comment by Eloston** [comment] 2018-10-01 17:49
@mehrdadn Based on the symbol names of your solution, it seems your solution is modifying code related to the preferences store. I believe the preferences store is one component of a profile (i.e. the Preferences file and potentially several other files). I suspect there may be separate logic to determine if the profile is being used on a different machine.

Furthermore, if a hash is used to ensure validity of the store, then it's possible that not all syntax or semantic errors are caught after hash validation passes successfully. This can be a problem if the stored preferences gets corrupted (and also if someone makes a mistake modifying preferences. But, I believe it's important to maintain integrity over ease of tweaking for most users. At most, I will allow a flag to toggle hash validation.)

**Comment by mehrdadn** [comment] 2018-10-01 18:32
I think it's just the preferences file that's checked for tampering (there's a file called "Secure Preferences"). But even if other things are checked for migrating profiles between machines, note that migrating profiles between machines is not the real issue here—the problem here is that even on the exact same account and machine, you can't migrate a Chrome profile to ungoogled-chromium. I think it'd directly benefit this project to make that migration easy; the ability to migrate to other machines, if affected, would only be a side benefit.

And yes, it's true that not all errors are caught, but errors are not introduced in the first place unless an external entity is messing with the profile. Given that normal Chrome doesn't allow tampering on Windows, programs don't do that anymore either, so the only time this would occur for a user is if he tried to modify his preferences by hand himself in ungoogled-chromium... in which case I think the user would know what he's doing and the potential for the resulting damage. Though even then, Google's solution of just wiping their settings/extensions/etc. isn't exactly helpful... it inflicts a ton more damage than the user himself did.

But in any case, I think a flag would suffice anyway if you think it needs to be behind one, though it probably wouldn't help make it too easy to migrate to ungoogled-chromium.

**Comment by Eloston** [comment] 2018-10-01 20:47
> note that migrating profiles between machines is not the real issue here

In this issue, that seems to be the real issue... is there an alternative interpretation I'm missing here?

> the problem here is that even on the exact same account and machine, you can't migrate a Chrome profile to ungoogled-chromium

I didn't realize that was also a side effect of this problem from reading your issue report. Thanks for clarifying.

> And yes, it's true that not all errors are caught, but errors are not introduced in the first place unless an external entity is messing with the profile

I just realized that the files mentioned here and in your report are the same... it's possible that the logic is more unified and the metric gathering more extensive than I originally thought.

But, if the "pref hash store" also includes a hash of the preference contents, then my earlier point still stands with corruption, i.e. errors introduced by hardware and/or software glitches.

**Comment by mehrdadn** [comment] 2018-10-01 20:51
Oh, the alternative interpretation _was_ migrating from Chrome to ungoogled-chromium.

And again, yes, it does "catch" corruption caused by software/hardware glitches, and it "fixes" it by just obliterating almost everything. You can judge whether that's a cure better or worse than the disease; personally I think it's the latter, since I've literally not found this helpful even once...

**Comment by Eloston** [comment] 2018-10-01 21:34
> And again, yes, it does "catch" corruption caused by software/hardware glitches, and it "fixes" it by just obliterating almost everything. You can judge whether that's a cure better or worse than the disease

I will reserve decisions and further comments on this issue until I learn how the hashing works, what exactly it needs to function, and how it relates to hashes generated by other Chromium variants (e.g. Chrome, Opera, Brave, regular Chromium).

**Comment by Eloston** [comment] 2018-11-14 20:12
I think we can reference these changes to solve this issue:

* https://github.com/brave/brave-core/pull/795
* https://github.com/Eloston/ungoogled-chromium/issues/538#issuecomment-435613533
    * I'm planning on investigating the CWS change to see what it affects.

If I have time, I'll look into it.

**Comment by caada** [comment] 2018-11-14 22:01
If someone can build chrome windows version with --disable-machine-id and --disable-encryption switches, I can test portability.

Thanks keeping an eye on this issue.

**Comment by Eloston** [comment] 2018-11-15 00:01
Unfortunately, Windows support is broken and no one's working on it right now (#475). I could test this on Linux once it gets added.

**Comment by crazy-max** [comment] 2018-11-17 19:14
@Eloston I can implement the changes I made on brave-core here if you like ?

**Closed** 2018-11-19 22:58 UTC
Labels: enhancement, help wanted
