### ISSUE TITLE
I get no sound when trying to use ungoogled chromium for work

### ISSUE THREAD

**Issue by lalascott7** [Eloston/ungoogled-chromium#452] opened 2018-08-13 14:49 UTC
Hello,
I need help. I am wondering how can I use ungoogled chromium for work to do my calls. I use ytel.com to take calls. I have enabled my headset and still no sound. When I got to Hooktube or Bitchute, I am good. I can hear the sound. Is there a way to enable the sound on ytel.com telephony site?

**Comment by lalascott7** [comment] 2018-08-13 17:34
No. It is a telephony website where you dial calls like a cloud-based dialer similar to Five9. Not sure if you are familiar with that. I have to end up using Firefox for now. But I am wondering if I can make Chromium work for ytel

**Comment by Eloston** [comment] 2018-08-13 17:37
Does it work with Chrome or regular Chromium?

**Comment by lalascott7** [comment] 2018-08-13 19:44
It It works with regular Chrome :( I don't want to have to go back to that. I really need it to work for my job. When I log in I get the sound prompt. But when I hit active status to dial my calls in it, I don't get the sound that I a ready to take calls. Same with mycallcloud which is another web phone. :(

**Comment by lalascott7** [comment] 2018-08-13 19:45
Do you have access to IRC? I am tired of waiting to get requests. This is so tiring.

**Comment by lalascott7** [comment] 2018-08-13 20:18
Can I just get immediate help, please? I have to use this for work, otherwise, I will have to say forget it and use the original chrome and just don't sign into it. Just remove the tracking stuff. I wish someone can create an article on how to get sound to work on web phones in telephony.

**Comment by Eloston** [comment] 2018-08-13 21:13
Welcome to the free software community, where developers are plentiful and support is minimal on average.

I am support*, and also the main developer. This isn't a company with a paid support team; this is a hobby project. I don't have time to provide support all day, much less develop on it every day. Although I would like to have all issues resolved in a timely manner, this simply isn't possible.

I'd recommend that you stick to Brave or Chromium, and tweak them to your liking. They aren't as aggressive in removing Google integration, so the possibility of breakage is low.

\* There are other kind strangers who lend a hand in support too.

Now, regarding your issue:

Given your site is a web-based call system, it is very likely that it is using WebRTC. I do recall calling not working on Discord (also WebRTC-based), but I haven't dug into it to discover the issue. If you or anyone can confirm this site is using WebRTC, that would be helpful. (If not, we'd still probably need to know what they're using.)

I'm also curious to know if Chromium or Brave work with the site too. If there's Chrome-specific code making it work, then there may not be much we can do about it.

**Comment by lalascott7** [comment] 2018-08-13 21:51
hmm ok well my Project Manager told me to use Chrome in incognito mode so I had to set the settings exactly how Chromium is and jus use that. I understand this is hobby to you. I did my research on both ytel.com and mycallcloud.com webphones and yes they are both WebRTC-based.  So it would be possiblity it can work?

**Comment by Eloston** [comment] 2018-08-13 23:00
> If you guys can see if it can work in Chromium that would be awesome!

I'm confused. So you confirmed that Chromium doesn't work? Or by "Chromium", do you mean ungoogled-chromium?

> So it would be possible it can work?

WebRTC testing sites say WebRTC is functional, but it seems that certain web applications don't work anyway. I don't know why, and I'm not sure how to diagnose (I know little about WebRTC). Seeing whether Chromium and Chromium-based browsers (like Brave) work or not may give us a clue of the root cause.

**Comment by lalascott7** [comment] 2018-08-13 23:36
Yes it was Chromium the ungoogled one.

**Comment by Eloston** [comment] 2020-04-18 22:56
This issue is pretty old now. If you're still having this issue, let us know.

**Closed by Eloston** 2020-04-18 22:56 UTC
Labels: bug, help wanted

**Comment by lalascott7** [comment] 2020-04-19 03:06
Ok thanks. Wow you been too long for a response lol. 

--
Best Regards,

 LaToya Scott
 lalascott@postinbox.com

....
Are you a health, health & beauty, or creative entrepreneur that needs an extra helping hand with enhancing your brand, managing your website, your social media, or handling your endless to-do list of tasks? Or do you have your financial options open? Learn more at lsvirtualconsulting.com. Let us help you save time growing your business, virtually.

**Comment by SollyBunny** [comment] 2025-02-03 20:47
From reading this I have no idea if the problem is actually just on ungoogled chromium and if WebRTC is involved. But if it is on ungoogle chromium and WebRTC is involved

I have left a comment on another post with a solution, which I'm linking here for future googlers

https://github.com/ungoogled-software/ungoogled-chromium/issues/1483#issuecomment-2632034703
