### ISSUE TITLE
Cannot Install Extensions

### ISSUE THREAD

**Issue by MrTeeXD** [Eloston/ungoogled-chromium#1009] opened 2020-04-20 03:39 UTC
**Describe the bug**
So, i recently stumbled upon this Software of yours and I see where you are going with this. One problem though, i cannot seem to install Extentions from the Chrome Store

**To Reproduce**
1. Go to The Chrome Store
2. Click on any Extension
3. See error by looking at the Button that says Available For Chrome

**Expected behavior**
What should happen is the extention should install into the browser

**Screenshots**

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 1909
 - ungoogled-chromium version: Chromium 80

**Additional context**
If this is not gonna be fixed then may I suggest a Alternative to make a Website that contains Extensions that you can download as a file and install it manually into the browser.

**Comment by eggplanting** [comment] 2020-04-20 06:58
Hello,

this is a wanted behavior, but you can install an extension to directly install Extensions via Chrome Store.

Since the update URL doesn't get interpreted by Ungoogle Chromium . Please look at the FAQ: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#will-extensions-auto-update

You still can get this work with this addon, mentioned in the FAQ: https://github.com/NeverDecaf/chromium-web-store

**Comment by MrTeeXD** [comment] 2020-04-20 07:03
Ahh interesting, I might consider using this Browser. I hope its still alive and kicking.

**Comment by Eloston** [comment] 2020-04-25 19:55
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/23. The workaround is to use the Chromium Web Store extension, but it doesn't work right now because CRX installation is broken (as indicated by the linked issue).

**Comment by Eloston** [comment] 2020-04-25 19:56
The workaround for now is to unpack the CRX file and load it as an unpacked extension in chrome://extensions

**Closed by Eloston** 2020-04-25 19:55 UTC

**Comment by abh-oss01** [comment] 2020-05-13 04:38
> The workaround for now is to unpack the CRX file and load it as an unpacked extension in chrome://extensions

# still doens't work, I've managed to install the web store, but I cannot install any extensions from the store itself, the extension never install, it's infinitely loading.
