### ISSUE TITLE
is ungoogled-chromium from Homebrew safe?

### ISSUE THREAD

**Issue by j0k4rX** [Eloston/ungoogled-chromium#1910] opened 2022-04-14 06:49 UTC
Hi @Eloston ,
As the title suggests, is chromium arm binaries provided by (@kramred ) safe to be downloaded from there?
Regards.

**Comment by PF4Public** [comment] 2022-04-14 09:54
Duplicate of #1549
Please search existing and closed issues for similar ones first

**Closed by PF4Public** 2022-04-14 09:54 UTC
