### ISSUE TITLE
Drag-and-drop not working

### ISSUE THREAD

**Issue by pirate1337** [Eloston/ungoogled-chromium#923] opened 2020-02-01 04:32 UTC
[https://www.neverendingchartrendering.org/](url)

Hi, this site doesn't seem to work correctly in ungoogled chromium 79.0.3945.117 on Windows 10 when dragging the image onto the panel.
Tested it in firefox and it works fine.
Any fix?

EDIT: installing extensions by dragging the crx files into the extensions page also does not work.

**Comment by tangalbert919** [comment] 2020-02-01 20:49
I can confirm this as an issue on ungoogled-chromium 79.0.3945.130 on Windows. Haven't tried this on Linux yet, though.

**Comment by Eloston** [comment] 2020-02-02 01:16
On Linux, I've been having troubles dragging and dropping for a while now, such as files from a file manager. Maybe dragging and dropping is broken by a patch?

**Comment by cypherpunk1984** [comment] 2020-02-02 07:42
Not working either on Linux Mint 19.3 Cinammon 64bit. I tried installing NeverDecaf's Chromium Webstore. Dragged the CRX file and dropped it on chrome://extensions/ (Ungoogled Chromium Version 79.0.3945.130) but nothing happens. The screen changes to "Drop to install", but you drop and nada.

**Comment by flesti** [comment] 2020-02-03 11:13
Similar to #834 "[Windows] Extensions don't install via drag-and-drop bug"

Drag and Drop doesn't work for several versions back now. Either plain text, links, urls, images, files, etc, from explorer or other applications, rendering some functions in various sites unusable, like VirusTotal for example.

**Comment by flesti** [comment] 2020-02-12 18:55
All drag 'n drop works fine in 80.0.3987.87 (Official Build) (64-bit) 
Windows 7 SP1 x64 - WIndows 10 LTSC

**Comment by Eloston** [comment] 2020-02-16 05:23
@flesti We haven't updated Windows support to version 80 yet. I don't know what browser you're using.

**Comment by flesti** [comment] 2020-02-16 11:35
True. I just saw that you actually didn't. 
But [woolyss](https://chromium.woolyss.com/) apparently thought you did
with a [link](https://github.com/macchrome/winchrome/releases/download/v80.0.3987.87-r722274-Win64/ungoogled-chromium-80.0.3987.87-1_windows.7z) to this.

It's strange because it does actually look like ungoogled chrome. I don't know the difference if there's any.

**Comment by DonQuixoteI** [comment] 2020-02-18 17:51
Portable Linux 64-bit v.80.0.3987.106-1.1 has drag-and-drop issue in Bookmark Manager.
Previous (portable) 78.0.3904.108-2.1 does not that issue. 
No problems in 80.0.3987.106-1 provided by Debian (unstable).

**Comment by xahldera** [comment] 2020-03-12 12:56
Having issues with drag and drop installation of extensions in Windows 8.1 Pro 64 bit, Ungoogled Chromium version 80.0.3987.132

**Comment by cypherpunk1984** [comment] 2020-03-12 13:00
Ungoogled Chromium Version 80.0.3987.132

Linux Mint Tricia 19.3 (64-bit)

Drag and drop not working

**Comment by flesti** [comment] 2020-03-12 13:53
and it's strange because in the macchome builds drag and drop works fine

> Standard build of Eloston's ungoogled-chromium. All patches applied apart from "Safe Browser"

[https://github.com/macchrome/winchrome/releases](url)

**Comment by AyoungDukie** [comment] 2020-04-05 22:54
Just to add some more context, I did a clean reinstall of the earliest version with installer executable (78.0.3904.70-1), and found some more verbose gui errors **before** adding the flag for chrome://flags/#extension-mime-request-handling

https://github.com/NeverDecaf/chromium-web-store/issues/8#issuecomment-60949477

**Comment by Gooberpatrol66** [comment] 2020-04-05 23:04
#extension-mime-request-handling used to work, but doesn't anymore. now it just downloads the .crx file. I can no longer update chromium-web-store.

**Comment by perfect7gentleman** [comment] 2020-04-07 10:30
confirm

**Comment by PF4Public** [comment] 2020-04-07 10:48
>#extension-mime-request-handling used to work, but doesn't anymore. now it just downloads the .crx file. I can no longer update chromium-web-store.

Same for 80.0.3987.163

**Comment by Rohaq** [comment] 2020-04-07 10:59
Similar issue in ungoogled-chromium 80.0.3987.1492, installed via Chocolatey.

Set the flag, dragged the CRX file to an extensions tag, and it just sits there spinning its wheels forever.

**Comment by seanking2919** [comment] 2020-04-07 23:17
As of 80.0.3987.163, this issue apparently does not occur in [Woolyss builds](https://chromium.woolyss.com/), which apparently do not use the Safe Browsing patches. We'll probably need to look at the patches related to Safe Browsing because they might be the source of the problem.

**Comment by woolyss** [comment] 2020-04-08 14:28
Hello all,
Few days ago, I made a video to show that drag-and-drop works nicely on our ungoogled-chromium version:
https://github.com/NeverDecaf/chromium-web-store/issues/10#issuecomment-595535488

Thanks for all developers and mainly Eloston. Very good job!
It is an hard work to maintain an ungoogled version of Chromium. Respect!

**Comment by cypherpunk1984** [comment] 2020-04-08 15:22
Linux versions aren't ungoogled though, I prefer staying with an ungoogled version like Eloston's.

**Comment by xnaas** [comment] 2020-04-09 17:40
Per https://github.com/Eloston/ungoogled-chromium/issues/988#issuecomment-611656303 I can't install any extensions at all.

> I can't get any CRX files to install at all on:
>
> Chromium	80.0.3987.149 (Developer Build) (64-bit)
> Revision	5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
> OS	Windows 10 OS Version 1909 (Build 18363.752)
> JavaScript	V8 8.0.426.27
> Flash	(Disabled)
> User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
> 
> Trying to install through drag and drop or any methods mentioned in the FAQ only results in this happening indefinitely:
> 
> ![img](https://xnaas.info/img/DeadTheseManatee.png)

**Comment by Eloston** [comment] 2020-04-11 04:44
For anyone reading this, @xnaas's particular issue is https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/23

**Comment by linuxtopia** [comment] 2020-04-15 11:50
> For anyone reading this, @xnaas's particular issue is [ungoogled-software/ungoogled-chromium-windows#23](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/23)
> 
> EDIT: Workaround is to unpack CRX as a zip file (by renaming extension), then load the unpacked extension.

how to be renaming?

**Comment by AyoungDukie** [comment] 2020-04-15 11:53
Just by renaming the file in the file manager (ie <filename>.crx to <filename>.zip)

**Comment by linuxtopia** [comment] 2020-04-15 12:01
> Just by renaming the file in the file manager (ie .crx to .zip)

"Directory is not valid" alike an error appears when Ungoogled try to load unpack version of Web Store

**Comment by seanking2919** [comment] 2020-04-15 18:05
Yeah, renaming from CRX to ZIP didn't work for me either.

**Comment by seanking2919** [comment] 2020-04-15 18:31
On Debian/Ubuntu Linux builds, you can add downloaded extensions by opening them in the browser. You can also add extensions from CRX extractor. That's pretty much it. Even if I set the extension mime flag to always prompt for install, it doesn't auto-install downloaded extension files from elsewhere. Additionally, it doesn't do drag-and-drop.

**Comment by AyoungDukie** [comment] 2020-04-15 18:37
@seanking2919 @linuxtopia Fair enough, I hadn't personally done that; I was able to get it to work by "unpacking" the CRX like Sean mentioned, then using the developer options add the unpacked extension (did this while booted into windows 10 1909)

**Comment by seanking2919** [comment] 2020-04-15 22:22
@flesti How did you install version 80 official build?

**Comment by nunbit** [comment] 2020-04-24 15:08
> On Debian/Ubuntu Linux builds, you can add downloaded extensions by opening them in the browser. You can also add extensions from CRX extractor. That's pretty much it. Even if I set the extension mime flag to always prompt for install, it doesn't auto-install downloaded extension files from elsewhere. Additionally, it doesn't do drag-and-drop.
> 
> Tested on Linux Mint 19.3 Tricia (w/ Cinnamon desktop; 64-bit)

Thank you. @seanking2919 changing flag from default to always prompt for install solved it for me too. 
Arch Linux.

**Comment by flesti** [comment] 2020-04-24 16:38
> @flesti How did you install version 80 official build?

Turns out isn't official, it's builds from [winchrome](https://github.com/macchrome/winchrome/)
suggested by [woolyss](https://chromium.woolyss.com/) identical to Eloston apart from the "Safe Browser" patch
https://github.com/macchrome/winchrome/releases/

sorry for the late reply

**Comment by Eloston** [comment] 2020-04-26 04:28
Compiled Debian buster changes with this fix (https://github.com/ungoogled-software/ungoogled-chromium-debian/commit/102dfab77f1f44ae312949166f632a1fdba3bfce), and it seems to be working. I tested drag-and-drop with Chromium Web Store and uBlock Origin; both seem to install correctly.

How frustrating that this issue was caused by a silly mistake, but fortunate that it was easy to find and fix. Hopefully #845 can eliminate issues like these...

Closing as I think the issue should be fixed, but testing is appreciated. If the issue persists, I'll re-open.

**Closed by Eloston** 2020-04-26 04:28 UTC
Labels: bug, help wanted

**Comment by xnaas** [comment] 2020-04-27 02:59
This is a little off-topic for this issue, but I notice the Windows binaries are pretty out of date. Does a community member need to step up and compile binaries? Do the current old binaries automatically update to the newest stuff?

**Comment by Eloston** [comment] 2020-04-27 04:32
@xnaas 

> Does a community member need to step up and compile binaries?

Roughly, yes. More accurately, someone needs to update the Windows patches.

**Comment by FrankSalmick** [comment] 2020-05-08 09:55
@Eloston is there anything to doing builds other than `git pull` and following the instructions in [the windows repo's build instructions](https://github.com/ungoogled-software/ungoogled-chromium-windows)? I see in [one of their pull requests](https://github.com/ungoogled-software/ungoogled-chromium-windows/pull/41) it seems like they are actually making changes in addition to building it. I didn't realize updates were waiting for community support, so I'm going to start building my own versions now. If it's just building and not improving I'd be happy to push changes up when I compile a new version.

**Comment by Eloston** [comment] 2020-05-09 19:39
@FrankSalmick Every platform has platform-specific patches that needs to be updated every time Chromium is updated. I'm not too involved in maintaining platform support except for Debian.

**Comment by Flashwalker** [comment] 2023-03-15 17:05
### Drag-and-drop still ot working on _Flatpak_ version 110.
Tested on: **figma.com**
Cant drop images to figma working area.

Works only with version from .deb package.

**Comment by Flashwalker** [comment] 2023-03-31 06:59
it works now... may be because i installed new video driver
