### ISSUE TITLE
Cookies will be deleted when closing Chromium on Windows even when disabled in the settings.

### ISSUE THREAD

**Issue by onabi** [Eloston/ungoogled-chromium#378] opened 2018-04-01 14:50 UTC
The cookies get cleared when closing the browser even after disabling it in the settings.
![cookies](https://user-images.githubusercontent.com/36529080/38174330-e9962574-35cb-11e8-8e0d-2081081bd07e.png)
This is my build. http://www43.zippyshare.com/v/KGfC4FUJ/file.html

**Comment by CardealRusso** [comment] 2018-04-01 15:21
thanks for the virus

**Comment by ribatamu** [comment] 2018-04-01 16:04
Why, this build is connecting to clients2.google.com ?

**Comment by onabi** [comment] 2018-04-01 16:14
It's not a virus, it's the package I got after building it by following the instructions and as for why it is connecting to clients2.google.com I have no idea.

**Comment by ribatamu** [comment] 2018-04-01 16:50
Ublock Origin is crashing at start up. Something to do with the WebRTC?

**Comment by onabi** [comment] 2018-04-01 17:30
@ribatamu https://github.com/gorhill/uBlock/issues/533 That fixed it for me.
I don't recommend using my build though as it may be broken...

**Comment by squalus** [comment] 2018-04-01 18:20
You compiled without webrtc? I got build errors when I tried to do that.

**Comment by squalus** [comment] 2018-04-01 18:22
With my Windows build I don't see problems persisting cookies, nor is it connecting to google.

**Comment by ribatamu** [comment] 2018-04-01 18:38
Squalus, could you share your build?

**Comment by squalus** [comment] 2018-04-01 18:39
@ribatamu https://github.com/squalus/ungoogled-chromium-winbuild/releases/tag/65.0.3325.181-1

I have a PR open to put it up on the main site

**Comment by onabi** [comment] 2018-04-01 18:41
After trying on another windows 10 installation, cookies seem to be saved properly, my bad, I should have done it before opening an issue.

**Comment by ribatamu** [comment] 2018-04-01 18:51
Squalus, I have the same issue with your build. The build is connecting to http://clients2.google.com and Ublock Origin is crashing at start up. Do you have this issues on your end?

**Comment by squalus** [comment] 2018-04-01 19:33
I just tested in a clean Windows Server 2016 install. I don't see a connection to google or anywhere else on startup. I do see the same problem with uBlock Origin crashing though. A few other extensions I tested seem to work fine.

**Comment by squalus** [comment] 2018-04-01 19:52
It is something related to the webrtc check. You can get it working if you comment out code in `js/is-webrtc-supported.js`.

**Comment by ribatamu** [comment] 2018-04-01 19:52
I am not sure if anybody is using, but there is extension called privacy manager by saroyanm... After installation if I mouse click on this extension icon, Ungoogled Chromium is closing.

**Comment by squalus** [comment] 2018-04-01 20:01
`new self.RTCPeerConnection(null)` causes a crash on Windows but not Linux

**Comment by ribatamu** [comment] 2018-04-01 20:08
The connections to clients2.google.com are not caused by Ungoogled Chromium.

**Comment by ribatamu** [comment] 2018-04-01 20:21
Squalus, Ungoogled Chromium is closing, when you open new incognito window.

**Comment by squalus** [comment] 2018-04-01 20:25
Same here

**Comment by onabi** [comment] 2018-04-01 21:24
@ribatamu My build closes too when using incognito mode.

**Comment by Eloston** [comment] 2018-04-02 01:03
Opened issues #380 and #381 to resolve new issues.

`clients2.google.com` could be extensions trying to do an update check. You can try without extensions to see if any connections to clients2.google.com still go through.

Closing this one with invalid due to https://github.com/Eloston/ungoogled-chromium/issues/378#issuecomment-377807512

**Closed by Eloston** 2018-04-02 01:03 UTC
