### ISSUE TITLE
Chromium 72.0.3626.122-2 compiling fails on Windows

### ISSUE THREAD

**Issue by tangalbert919** [Eloston/ungoogled-chromium#711] opened 2019-03-20 19:14 UTC
### Description

Attempting to build ungoogled-chromium 72.0.3626.122-2 on Windows fails during the last part of `build.py`.

### Console output and logs

`[15799/20080] CXX obj/chrome/common/safe_browsing/file_type_policies/file_type_policies.obj
FAILED: obj/chrome/common/safe_browsing/file_type_policies/file_type_policies.obj
../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /nologo /showIncludes  "-imsvcC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-imsvcC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-imsvcC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" "-imsvcC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-imsvcC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-imsvcC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" -DV8_DEPRECATION_WARNINGS -DUSE_AURA=1 -DNO_TCMALLOC -DOFFICIAL_BUILD -DCHROMIUM_BUILD "-DCR_CLANG_REVISION=\"346388-5\"" -D_HAS_NODISCARD -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=1 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=0x0A000002 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DWEBP_EXTERN=extern -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSK_SUPPORT_GPU=1 "-DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\"" -DGR_GL_FUNCTION_TYPE=__stdcall -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=wchar_t -I../.. -Igen -I../../third_party/libwebp/src -I../../third_party/wtl/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/docs -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/gpu -I../../third_party/skia/include/pathops -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/codec -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/skia/modules/skottie/include -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n /utf-8 /X -fcolor-diagnostics -fmerge-all-constants -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -no-canonical-prefixes -fcomplete-member-pointers /Gy /FS /bigobj /d2FastFail /Zc:sizedDealloc- -fmsc-version=1911 -m64 /Brepro /W4 -Wimplicit-fallthrough -Wthread-safety /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /wd4702 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-null-pointer-arithmetic -Wno-nonportable-include-path -Wno-ignored-pragma-optimize /O1 /Ob2 /Oy- /Zc:inline /Gw /Oi /MT -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-inconsistent-missing-override -Wno-shorten-64-to-32 /TP /wd4577 /GR- /c ../../chrome/common/safe_browsing/file_type_policies.cc /Foobj/chrome/common/safe_browsing/file_type_policies/file_type_policies.obj /Fd"obj/chrome/common/safe_browsing/file_type_policies_cc.pdb"
../../chrome/common/safe_browsing/file_type_policies.cc(53,29):  error: use of undeclared identifier 'IDR_DOWNLOAD_FILE_TYPES_PB'
  bundle.GetRawDataResource(IDR_DOWNLOAD_FILE_TYPES_PB).CopyToString(binary_pb);
                            ^
1 error generated.`

### Environment details

* ungoogled-chromium version: 72.0.3626.122-2
* Configuration bundle: `windows`
* Packaging type (if applicable): `windows`
* OS and version for building: Windows 10 Home Build 17763 (Version 1809)
* Compiler toolchain: From downloads.ini

### Building and packaging steps

I used the instructions for Windows from `docs/building.md`, but with the 10.0.17134 SDK installed as it is the SDK that must be used, as outlined [here](https://chromium.googlesource.com/chromium/src/+/72.0.3626.122/docs/windows_build_instructions.md#visual-studio).

**Comment by r4sas** [comment] 2019-03-20 19:17
Please check issue tracker before opening new one.
Dupe of #675.

**Closed** 2019-03-20 21:50 UTC
