### ISSUE TITLE
Spell check stopped working

### ISSUE THREAD

**Issue by flesti** [Eloston/ungoogled-chromium#1030] opened 2020-05-08 13:29 UTC
Fresh install. New user. Any language. Any option/flag combination. Not about google connection either, since it uses hunspell for quite a long time now.
Willing to bet has something to do with this new "use enhanced spell check" option and those new spell check flags.

80.0.3987.149-2
windows 7 sp1 x64

**Comment by Eloston** [comment] 2020-05-10 19:41
Duplicate of #188 I believe.

**Closed by Eloston** 2020-05-10 19:41 UTC

**Comment by flesti** [comment] 2020-05-11 03:38
As I said, it used to work just fine, so it's not that.

**Comment by qvint** [comment] 2020-05-11 03:48
Did you try to [re-download *.bdic-files](https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries/+/master) and put them to `~/.config/chromium/Dictionaries`?

**Comment by flesti** [comment] 2020-05-11 09:27
those links of bdic flies seem to be [empty](https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries/+/master/en-US-9-0.bdic)
didn't try all of them, but the en-US one and some other are empty
