### ISSUE TITLE
chrome.exe from within symlink/junction fails [windows] [ERROR:sandbox_policy_base.cc(359)]

### ISSUE THREAD

**Issue by 55f** [Eloston/ungoogled-chromium#1380] opened 2021-02-06 14:44 UTC
version [87.0.4280.141-1.1_windows-x64](https://github.com/tangalbert919/ungoogled-chromium-binaries/releases/download/87.0.4280.141-1/ungoogled-chromium_87.0.4280.141-1.1_windows-x64.zip)

# initial situation:
install via [scoop](https://github.com/lukesampson/scoop) (`scoop install ungoogled-chromium`) worked fine ("package manager for windows"; builds shim; each new version into new directory and linking to the current)

# layout on disk:
```
C:\Users\user123\scoop\apps\ungoogled-chromium>dir
Directory of C:\Users\user123\scoop\apps\ungoogled-chromium

<DIR>        87.0.4280.141-1
<JUNCTION>   current [C:\Users\user123\scoop\apps\ungoogled-chromium\87.0.4280.141-1]
```

# following issue:
running from `C:\Users\user123\scoop\apps\ungoogled-chromium\current>chrome.exe` (the symlink/junction dir) as designated will fail to start up properly 💥 and logs into **C:\Users\user123\scoop\apps\ungoogled-chromium\current\debug.log**:
> [0206/151735.730:ERROR:sandbox_policy_base.cc(359)] Failed to add sandbox rule. error = 2, subsystem = 0, semantics = 1, pattern = 'C:\Users\user123\scoop\apps\ungoogled-chromium\current\\*.pdb'

🤷 

but running directly from `C:\Users\user123\scoop\apps\ungoogled-chromium\87.0.4280.141-1>chrome.exe` will work ✔️ 

I suspect some internal issue in the code here when executing from within symlink/junction, 
to double-check I also tried the "standard chromium (`scoop install chromium-dev`)" browser and it starts perfectly fine from within a symlink `C:\Users\user123\scoop\apps\chromium-dev\current>chrome.exe` ✅ 

😟

**Comment by Eloston** [comment] 2021-02-07 21:24
What version of Chromium is `chromium-dev`? Is it newer than that of ungoogled-chromium?

**Comment by EPIVISION** [comment] 2021-02-14 14:20
no, same major

**Comment by r4sas** [comment] 2021-02-14 20:24
dupe of https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/16#issuecomment-551068481.

**Comment by EPIVISION** [comment] 2021-02-17 14:19
> duplicate of [ungoogled-software/ungoogled-chromium-windows#16 (comment)](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/16#issuecomment-551068481).

yes definitely 😢 
also broken in 88.0

**Comment by PF4Public** [comment] 2021-12-10 18:44
@BinaryNate Thanks for your information! Given that it is a Chromium issue, I tend to close this issue, especially now that you've filled an issue with Chromium. If at a later time you'll have any new information on it, feel free to keep us informed.

Also let us know if new information arrives, that requires this issue to be re-opened and/or re-evaluated.

**Closed by PF4Public** 2021-12-10 18:44 UTC
