### ISSUE TITLE
x86 (i386) Debian build

### ISSUE THREAD

**Issue by cheater** [Eloston/ungoogled-chromium#64] opened 2016-09-29 01:02 UTC
Many people use x86. I'm one of them. I'm not sure of any better arguments, so I'll spare you the bs. Please start making builds for x86 versions of Ubuntu.

**Comment by Eloston** [comment] 2017-03-30 03:50
I believe the code in the repository right now can build natively for the i386 architecture.

Anyone who wants to upload binaries, please let me know here or via Gitter.

**Comment by Eloston** [comment] 2020-04-25 22:37
(Referencing issue https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/43 for context)

@braewoods Do you know the status of i386 builds?

**Comment by PF4Public** [comment] 2020-04-26 00:00
Slightly off-topic here, but still.

I can confirm, that in case of Gentoo x86 variant compiles and runs just fine.

**Comment by braewoods** [comment] 2020-04-26 00:44
@Eloston I have been able to build it for all supported architectures in the Debian repository. It should do fine. I've only disable it on i386 for Ubuntu releases newer than 18.04 because they're in the process of deprecating it. It won't be a primary architecture anymore so not much point in building for it.

**Comment by Eloston** [comment] 2020-04-26 01:27
@braewoods I see, I didn't realize Ubuntu was deprecating i386. I'm assuming that OBS will support i386 builds for Debian, right?

**Comment by braewoods** [comment] 2020-04-26 01:30
Yes. It should still work as I don't think Debian has plans to remove it any time soon.

**Comment by Eloston** [comment] 2020-04-26 01:36
Awesome. I'll close this after OBS i386 builds come around.

**Comment by guest271314** [comment] 2020-04-26 05:10
Re https://github.com/Eloston/ungoogled-chromium/issues/1015 was able to disable google . com as default search engine using a Policy

```
"chromePolicies": {
      "DefaultSearchProviderEnabled": {
         "level": "mandatory",
         "scope": "machine",
         "source": "platform",
         "value": true
      },
      "DefaultSearchProviderSearchURL": {
         "level": "mandatory",
         "scope": "machine",
         "source": "platform",
         "value": "http://localhost:8000?q={searchTerms}"
      }
```

It does not appear to be possible to disable or change default search engine at chrome://settings at Chromium 84.0.4122.7.

One issue with Ubuntu 18.04 and Chromium is that  libgl1-mesa-dri_19.2.8-0ubuntu0~18.04.3_i386.deb does not install on 32-bit when `apt upgrade` is run. That is the only upgradable package which does not install without an error. Chromium tries to load mesa drivers at startup. Am not sure if that leads to pages randomly crashing, e.g., the new GitHub notifications page. DevTools (inspect) also does not open at Chromium 83.

**Comment by Eloston** [comment] 2020-04-26 20:15
@guest271314 Due to lack of resources/interest, we only focus on stable releases of Chromium. We will deal with issues as they come down the stable channel.

**Comment by guest271314** [comment] 2020-04-26 20:52
@Eloston Ok. Just shared what found while trying to use newest release of dev channel that could locate for 32-bit, FWIW. Will check back at this issue when closed.

**Comment by PF4Public** [comment] 2021-10-18 15:33
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.

**Closed by PF4Public** 2021-10-18 15:33 UTC
Labels: enhancement, help wanted
