### ISSUE TITLE
uBlock Origin extension doesn't works properly

### ISSUE THREAD

**Issue by Flashwalker** [Eloston/ungoogled-chromium#1841] opened 2022-02-16 10:02 UTC
Cannot apply/save custom filters in **uBlock Origin** extension.

I'm using **97.0.4692.71** (Developer Build, **ungoogled-chromium**) on **Win 7 x64**.
Updated **ungoogled-chromium** from old version **89.0.4389.114**, and updated **uBlock Origin** extension to **1.40.8**

When i'm trying to save custom filters rules, the Apply button do nothing anymore.
https://github.com/uBlockOrigin/uBlock-issues/issues/1881#issuecomment-1040076730
https://github.com/uBlockOrigin/uBlock-issues/issues/1790

**Comment by PF4Public** [comment] 2022-02-16 12:47
Have you tried resetting uBlock's settings and/or reinstalling the extension?

**Comment by gorhill** [comment] 2022-02-16 15:10
Probably a duplicate of <https://github.com/Eloston/ungoogled-chromium/issues/1824>?

**Comment by PF4Public** [comment] 2022-02-16 15:26
@gorhill The issue you're linking is a separate building issue IIRC. It affects only that very particular binary built via GitHub Actions in https://github.com/ungoogled-software/ungoogled-chromium-debian repository. I mean that issue is a separate one.

I do however [remember experiencing something similar](https://github.com/uBlockOrigin/uBlock-issues/issues/1751#issuecomment-939313096) on both Linux and Windows, which was fixed by itself after reinstalling the extension.

@gorhill Thanks for stopping by ;)

**Comment by Flashwalker** [comment] 2022-02-22 11:47
@PF4Public , looks like uninstall an install UBo solves problem

**Comment by PF4Public** [comment] 2022-02-22 13:36
@Flashwalker Thanks for getting back to us. Closing.

**Closed by PF4Public** 2022-02-22 13:36 UTC
Labels: need info
