### ISSUE TITLE
Update Portable Linux to Latest Version

### ISSUE THREAD

**Issue by christianitus03** [Eloston/ungoogled-chromium#1191] opened 2020-09-19 20:22 UTC
**Is your feature request related to a problem? Please describe.**
Portable Linux is still on 83.0.4102.97-1.1. This is almost three months old.

**Describe the solution you'd like**
Please update Portable Linux to the latest stable version.

**Comment by Eloston** [comment] 2020-09-19 22:02
Marking as duplicate of https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/69

**Closed by Eloston** 2020-09-19 22:02 UTC
