### ISSUE TITLE
No prompt appears when a website asks for some permission

### ISSUE THREAD

**Issue by jstkdng** [Eloston/ungoogled-chromium#1081] opened 2020-06-23 19:23 UTC
**Describe the bug**
Basically what the title says, haven't tested with other permissions.

**To Reproduce**
1. Start chromium with a clean profile
2. Open reddit.com (for example)
3. Reddit asks for permission to show notificatiosn
4. No prompts appears, the screen only turns black and there is a white dot on the center of the page

**Expected behavior**
A prompt appears allowing me to decide whether to give said permission or not.

**Screenshots**
![2020-06-23_14-14](https://user-images.githubusercontent.com/52050345/85448833-b6feec00-b55c-11ea-9683-dfe34843316f.png)

**Environment**
 - OS/Platform and version: Arch Linux
 - ungoogled-chromium version: 83.0.4103.106

**Additional context**
The problem has been there since 83.0.4103.97, I just didn't notice at the time since my profile already had the permissions I gave to the sites I visit frequently. Until some days ago I reinstalled arch and started with a new profile, allowing me to notice the issue.

**Comment by PF4Public** [comment] 2020-06-23 20:04
After refreshing this dot disppears and never returns. Weird.

**Comment by jstkdng** [comment] 2020-06-23 20:58
After some time it will try to ask again, only way to stop it is to change the sites permissions directly.

**Comment by PF4Public** [comment] 2020-06-23 22:54
@jstkdng Have you tried any other website? I have tried https://www.bennish.net/web-notifications.html but it fails. Looks like notifications are broken completely.

**Comment by Eloston** [comment] 2020-06-24 00:12
This sounds like a regression in the upgrade to 83. Labeling as a bug until shown otherwise.

**Comment by wchen342** [comment] 2020-06-24 01:09
Has anyone checked whether this also happens with vanilla chromium?

**Comment by jstkdng** [comment] 2020-06-24 02:41
I also have brave installed and the prompt appears normally. Havent tested with regular chromium.

@PF4Public
The same happens with the 4chan-x extension, it tries to ask for notification permissions and nothing happens.

**Comment by wchen342** [comment] 2020-06-24 02:51
Well that doesn't draw any conclusion because brave may have their own patch fixed the problem. I don't have a machine that I can create a new profile so I cannot test at this time..

**Comment by jstkdng** [comment] 2020-06-24 12:13
@wchen342 
Just tested on regular chromium and the notifications shows up normally, at least on reddit:
![image](https://user-images.githubusercontent.com/52050345/85553925-0dfed280-b5ea-11ea-959f-f2ee5c5f519b.png)

**Comment by wchen342** [comment] 2020-06-24 18:29
Then there is a patch that causes this. Maybe trying to build with one more patch each time and see which one causes the problem?

**Comment by Eloston** [comment] 2020-07-31 21:49
Is this still a problem with 84?

**Comment by wchen342** [comment] 2020-08-04 02:08
v84 works fine with clean profile on Arch. Not sure about other systems though.

**Comment by Eloston** [comment] 2020-08-04 17:15
So the problem fixed itself? That's interesting...

Closing for now.

**Closed by Eloston** 2020-08-04 17:15 UTC
Labels: bug, help wanted
