### ISSUE TITLE
Fullscreen Permissions

### ISSUE THREAD

**Issue by lefedor** [Eloston/ungoogled-chromium#541] opened 2018-10-02 02:21 UTC
Hello, I'm trying to write video player on embed system.
Standard googled chrome not allows me to run fullscreen video:

"""
Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
"""

Havent found any flag at settings to force this permission/disable limitation.

Same correct for 65.0.3325.181-1 ungoogled tested.

Is there way to modify ungoogled-chromium so it will accept some flag if started from shell, like:
  --fullscreen-policy=no-user-gesture-required
Or may be someone knows the right existing startup key?

**Comment by Eloston** [comment] 2018-10-02 05:43
I'd prefer a solution that doesn't require a patch first. If it doesn't exist, then I welcome a PR to add this functionality behind a flag.

**Comment by lefedor** [comment] 2018-10-02 09:48
Judging by third_party/blink/renderer/core/fullscreen/fullscreen.cc there's no build-in key for that feature.

**Comment by lefedor** [comment] 2018-10-02 10:11
Have made estimated patch file but don't have disk space currently to compile this beast and don't know if it's the right way to implement feature.
[allowanyfsr.patch.zip](https://github.com/Eloston/ungoogled-chromium/files/2437426/allowanyfsr.patch.zip)

**Comment by bershanskiy** [comment] 2019-10-07 14:02
@lefedor Is this still relevant or did you find another solution?

I'd recommend looking into puppeteers like Selenium that allow you to emulate all the user actions as if they were initiated by user. Also, there is WebDriver API which has [an explicit endpoint for entering full-screen](https://www.w3.org/TR/webdriver2/#fullscreen-window) (no idea how widely it is supported, though).

**Comment by bershanskiy** [comment] 2019-10-08 12:56
@lefedor Also, I'd recommend looking into so-called "kiosk mode" which was designed to make Chrome display a page in full-screen mode without any browser UI elements.

**Comment by Eloston** [comment] 2020-04-18 22:59
Closing because this is pretty old. Let us know if you still have this issue.

**Closed by Eloston** 2020-04-18 22:59 UTC
Labels: help wanted, question
