### ISSUE TITLE
[User discussion] Future of Ungoogled Chromium

### ISSUE THREAD

**Issue by ribatamu** [Eloston/ungoogled-chromium#751] opened 2019-04-30 18:02 UTC
I see the recent topics for new name, logo, manivest v3, future etcetera...

I don't know what the community is thinking really but I am personally sick to see how Google is taking good staff from Chrome and bringing craps instead of that. 
Of course they make a lots good stuff but  generally they are really good in NOT listening what the user want. They play their own game :)

I think is good to have Chromium for a base but the name and the logo, should be completely different than Chrome and Chromium.

I think Ungoogled Chromium should have adblock build inside, which is completely different than the manifest v3 crap (I think Brave this time is in the right direction). Just think Ungoogled and UblockOrigin in the same place :) One name, one idea, one browser ahh :)

Personally that's the direction in which I would like to see ungoogled going, because Chrome is looking more and more like a part from advertisement agency.

Eloston, sorry for creating a new topic but for me they are different topics and the issue is the same.

**Comment by ribatamu** [comment] 2019-04-30 18:24
I have some knowledge in latin and ... I don't know just the name "Secretum" came in my mind...
Secterum is a latin word, which in english mean private.

**Comment by Eloston** [comment] 2019-05-01 05:32
If I'm not mistaken, this is a duplicate of #640. My stance hasn't changed since then, but there are still a lot of good ideas and perspectives discussed in there.

**Closed by Eloston** 2019-05-01 05:32 UTC
