### ISSUE TITLE
Ubuntu 17.04 "Zesty Zapus" Builds

### ISSUE THREAD

**Issue by wincinderith** [Eloston/ungoogled-chromium#218] opened 2017-04-17 07:37 UTC
There doesn't seem to be any Zesty Zapus builds available yet. Any plans for this?

**Comment by Eloston** [comment] 2017-04-18 02:18
There are no plans for that right now. Getting official builds (i.e. statically-linked binaries) working is a higher priority.

I think 17.04 might be similar enough to Stretch for that configuration to work out-of-the-box. I will accept a pull request anytime to get this working if it is necessary.

**Comment by 9Morello** [comment] 2017-04-26 16:18
I can confirm that the `develop` branch works out of the box in 17.04.

**Comment by wincinderith** [comment] 2017-04-27 00:22
@Eloston What's the process for setting it up on the build server then?

**Comment by Eloston** [comment] 2017-04-27 01:49
@wincinderith There is no build server. People still have to compile on their own.

**Comment by wincinderith** [comment] 2017-04-27 07:34
@Eloston How does one get he build added [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/)?

**Comment by Eloston** [comment] 2017-04-27 07:47
@wincinderith [I have a team of people maintaining binaries](https://github.com/orgs/ungoogled-software/teams/binaries-team). Do you want to join the team?

The process is pretty straight-forward:
1. Fork [the binaries repo](https://github.com/ungoogled-software/ungoogled-chromium-binaries/)
2. Create a new release and upload the binaries to the fork
3. Update the main binaries repo site data to point to the uploaded binaries. People in the binaries team have direct commit access for convenience. I guess pull requests can work too.

**Comment by brokoli-mate** [comment] 2017-05-18 07:50
I made binaries for ubuntu 17.04 and created [pull request](https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/4/commits/61c1d3e468c232b6411e0b6373eb95ccdb295bca) . Have i done everything rihght?

**Comment by Eloston** [comment] 2018-02-16 23:58
Closing because Canonical ended 17.04 support. See #310 for 17.10 development.

**Closed by Eloston** 2018-02-16 23:58 UTC
Labels: enhancement, help wanted
