### ISSUE TITLE
Vaapi working on v. 99?

### ISSUE THREAD

**Issue by Ph0rk0z** [Eloston/ungoogled-chromium#1861] opened 2022-03-14 01:08 UTC
On arch it no longer chooses the VDA decoder under media-internals. The thinkpad CPU churns up to 90% and the fan kicks on. V 96 works correctly.

Is this something related to arch packaging or is it broken on ubuntu too?

**Comment by PF4Public** [comment] 2022-03-14 09:41
Could this help: PF4Public/gentoo-overlay#133 ?

**Comment by Ph0rk0z** [comment] 2022-03-15 13:24
It did bring back the VDA decoder but still seems like chrome uses way more CPU now.

**Comment by PF4Public** [comment] 2022-03-15 14:58
Could be a Chromium bug or regression then.

**Comment by Ph0rk0z** [comment] 2022-03-15 23:07
Seems like it. For instance playing a video in the small player now eats 40% cpu. I can't go back earlier than v96. I was using 94 and tend to avoid upgrading chromium for this reason.

**Comment by PF4Public** [comment] 2022-03-16 15:49
I actually gave it a try and observe no abnormal CPU utilisation with hardware decoding:
![Unbenannt](https://user-images.githubusercontent.com/10319700/158628213-7b6ca313-8af1-4971-ae4c-64ea00418470.png)
![Unbenannt2](https://user-images.githubusercontent.com/10319700/158629444-c5be621b-3a9d-4e8f-a008-0765a84ac595.png)

**Comment by Ph0rk0z** [comment] 2022-03-16 22:26
Not in the mini player.

![notminiplayer](https://user-images.githubusercontent.com/59298527/158701420-e6d83a8f-1192-4619-b304-f05eb53030f6.png)

VS in the mini player


![miniplayer](https://user-images.githubusercontent.com/59298527/158701538-e3642c84-9556-4dd0-860e-4628bbe3869a.png)


It did not do this before or I would have noticed it while playing music.

The software decoder would put me into the 90s. The joke of it all is that video is a static image.

**Comment by PF4Public** [comment] 2022-03-17 19:49
Hmm, indeed looks like a mini-player issue:
![Unbenannt](https://user-images.githubusercontent.com/10319700/158883550-b3ad8b32-1bd6-4de5-aa26-b0f8135de33a.png)

**Comment by Ph0rk0z** [comment] 2022-04-21 14:24
Yeah bot, its still not any better in v100

**Comment by PF4Public** [comment] 2022-04-21 16:16
I've marked it as "need info" so that it would be closed automatically because I doubt we can do anything about it. It wouldn't hurt if someone could in the meanwhile provide any new information, for example a Chromium bug reference.

**Comment by PF4Public** [comment] 2022-05-21 14:16
Still an issue in 102. I'll close it.

**Closed by PF4Public** 2022-05-21 14:16 UTC
Labels: need info

**Comment by jstkdng** [comment] 2022-05-21 14:50
Is vaapi not working on 102? It works on 101.
![image](https://user-images.githubusercontent.com/52050345/169656863-be2f0dd0-7f2f-4d54-8db2-454ce539e99d.png)

**Comment by PF4Public** [comment] 2022-05-21 16:19
> Is vaapi not working on 102? It works on 101.

Works fine. It is a mini-player issue.
