### ISSUE TITLE
Drag'n'Drop not working even with "Handling of extension MIME type requests"

### ISSUE THREAD

**Issue by azev** [Eloston/ungoogled-chromium#894] opened 2019-12-18 16:29 UTC
Drag'n'Drop not working.

![s20191218132822](https://user-images.githubusercontent.com/6639188/71104306-5bf9d000-219a-11ea-982d-d7ac72621b45.png)

![s20191218132734](https://user-images.githubusercontent.com/6639188/71104343-674cfb80-219a-11ea-96c7-81ce0dc766ac.png)

![s20191218132131](https://user-images.githubusercontent.com/6639188/71103973-d70eb680-2199-11ea-80fd-da90775ac8cf.png)

**Comment by jstkdng** [comment] 2019-12-18 17:00
I can confirm Drag n' drop is not working, but the extension install thing only happens under windows.

**Comment by SteelChickens** [comment] 2019-12-18 21:39
I got dialog box on linux and hit add. But ublock did not updae from version 1.23 to new version.

**Comment by Eloston** [comment] 2019-12-19 00:17
Duplicate of #834.

**Closed by Eloston** 2019-12-19 00:17 UTC

**Comment by Eloston** [comment] 2019-12-19 00:18
@SteelChickens Does the new version not appear in `chrome://extensions`? Please make a new issue with more details.

**Comment by SteelChickens** [comment] 2019-12-19 22:09
No, I had ublock previously and it did not update the version. Installing an extensin that is not present does work... but only in linux.
