### ISSUE TITLE
extensions doesn't work on version 95

### ISSUE THREAD

**Issue by b1ackfa1c0n** [Eloston/ungoogled-chromium#1726] opened 2021-11-03 14:08 UTC
**Describe the bug**
after updating from ungoogled-chromium version 90 to 95 suddenly all extensions stopped working
**To Reproduce**
1. Go to 'update from version 90 to version 95'
2. install any kind of extension those that didn't work with me were ublock origin and dark reader'
3. whenever i try to click on the extension's icon it's menu won't open

**Expected behavior**
I want the extensions to work properly as they were working before updating.
**Screenshots**

**Environment (please complete the following information):**
 - OS/Platform and version: ubuntu 20
 - ungoogled-chromium version: 95

**Additional context**

**Comment by networkException** [comment] 2021-11-03 14:22
This likely is a duplicate of https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/247

**Closed** 2021-11-08 20:51 UTC
