### ISSUE TITLE
BUILD.gn error during compilation on Windows

### ISSUE THREAD

**Issue by hardhub** [Eloston/ungoogled-chromium#675] opened 2019-02-11 22:18 UTC
### Description

Error during patching:
```
patching file chrome/BUILD.gn
Hunk #2 FAILED at 83.
```
### Environment details

* ungoogled-chromium version: all tried versions starting 69.*
* Configuration bundle: windows
* Packaging type (if applicable): windows
* OS and version for building: Windows 7 x64
* Compiler toolchain: VS 2017

### Building and packaging steps

py ungoogled_packaging\build.py

**Comment by TCB13** [comment] 2019-02-17 21:44
Related to https://github.com/Eloston/ungoogled-chromium/issues/639

**Comment by TCB13** [comment] 2019-02-17 21:58
Maybe related to the safe browsing mess? https://github.com/Eloston/ungoogled-chromium/issues/639#issuecomment-461983120

I was stuck on this for a long time, manage to get around it on macOS but under windows looks like its harder...

**Comment by TCB13** [comment] 2019-02-17 22:37
Update: this isn't actually related to safe browser. Looks like a new issue of this version.

**Comment by hardhub** [comment] 2019-02-18 12:32
@TCB13 

I simply made all as specified in instructions.  
Maybe you used different version of chromium source.  
To be honest I do not know exactly.

**Comment by TCB13** [comment] 2019-02-18 14:00
@hardhub can you cofirm that your build process was like this?

1. Install:
- 7z1806-x64.msi
- python-2.7.15.amd64.msi (add it to path)
- python-3.6.5-amd64.exe (don't add to path; enable py launcher)
2. Run `pip install pypiwin32`
3. Install VSCode (vs_community__735157147.1549731593.exe) with the following components:
```
- Microsoft.VisualStudio.Workload.NativeDesktop
- microsoft.visualstudio.component.debugger.justintime
- microsoft.visualstudio.component.vc.diagnostictools
- microsoft.visualstudio.component.vc.cmake.project
- microsoft.visualstudio.component.vc.testadapterforboosttest
- microsoft.visualstudio.component.vc.testadapterforgoogletest
- microsoft.component.vc.runtime.ucrtsdk
- microsoft.visualstudio.component.vc.atlmfc
- microsoft.visualstudio.component.vc.cli.support
- microsoft.visualstudio.component.vc.140
- component.linux.cmake
```
4. Open `Settings > Apps & features > Windows SDK 10.0.17763.132 > Modify` and enable `Debugging Tools For Windows`
5. Download https://github.com/Eloston/ungoogled-chromium/archive/71.0.3578.98-2.zip and extract it to `c:\ungoogled-chromium-71.0.3578.98-2`
6. Add a new system variable `DEPOT_TOOLS_WIN_TOOLCHAIN` with value `0`
7. Run:
```
mkdir build\src
py get_package.py windows build\src\ungoogled_packaging
cd build\src
py ungoogled_packaging\build.py
```

**Comment by hardhub** [comment] 2019-02-18 21:53
@TCB13 

Not exactly so...

1. 7z was already installed. Just checked version - 16.04 (but nor sure it is so important).
>     * python-3.6.5-amd64.exe (don't add to path; enable py launcher)
both are in PATH but 27 before 37 (not 3.6.5) and py launcher is also in PATH

2. Yes, I did

3. I have Visual Studio 2017 Enterprise latest update (I am working on some .Net projects).
So I just installed all C++ features including MFC library.
I have list of all installed packages, but it is 36 KB (I cannot simply paste it here).

4. I have installed lastest Windows 10 SDK 1809:
17763.132.181022-1834.rs5_release_svc_prod1_WindowsSDK

Debugging Tools was also installed with this SDK.

5. No.. I did this:
```
mkdir build\src
py get_package.py windows build\src\ungoogled_packaging
cd build\src
py ungoogled_packaging\build.py
py ungoogled_packaging\package.py
```

I think get_package.py does that.

6. Yes
```
C:\>set | findstr DEPOT
DEPOT_TOOLS_WIN_TOOLCHAIN=0
```

7. Yes as described above.

**Comment by TCB13** [comment] 2019-02-18 22:17
@hardhub my 5th set is to just get the code from this repo, so I can have `get_package.py`... I guess we're doing it in the exact same way. Thanks for the clarification.

**Comment by TN0X** [comment] 2019-02-20 17:09
> ### Description
> Error during patching:
> 
> ```
> patching file chrome/BUILD.gn
> Hunk #2 FAILED at 83.
> ```

The problem arises due to problems in some patches since chromium 72.0.72.0.3626.xx.
So there is not only the known issue with all safe-browsing patches since 71.0.3578.98, which could be solved by disabling these patches and setting the approriate build-flag. Since 72.0.xxx there are new issues with other patches. These patches does not fit to the source code of chromium 72.0.xxx:

windows-disable-reorder-fix-linking.patch:
patching file chrome/BUILD.gn
Hunk #2 FAILED at 83.

windows-disable-rcpy.patch:
patching file build/toolchain/win/tool_wrapper.py
Hunk #1 FAILED at 195.
Hunk #2 FAILED at 227.

last working build with disabled safe-browsing patches is 71.0.3578.98-3

**Comment by TCB13** [comment] 2019-02-20 17:14
@TN0X thank you for the answer, can you tell use the exact steps to disable safe browsing in `71.0.3578.98-3` and to add the build-flag? I tried to do this and failed (not very well versed in chromium).

**Comment by TN0X** [comment] 2019-02-21 09:17
> @TN0X thank you for the answer, can you tell us the exact steps to disable safe browsing in `71.0.3578.98-x` and to add the build-flag? I tried to do this and failed (not very well versed in chromium).

see: https://github.com/TN0X/ungoogled-chromium/compare/master...TN0X:test1

you have to change thes files: 
config_bundles/windows/patch_order.list
config_bundles/common/patch_order.list
config_bundles/common/gn_flags.map

**Comment by warmaster345** [comment] 2019-02-21 12:18
I'm having the same issue. It seems that disabling safe browsing doesn't fix all problems, windows-disable-rcpy and windows-disable-reorder-fix-linking patches are still broken with the last chromium version on windows

**Comment by TCB13** [comment] 2019-02-22 12:22
@TN0X I tried to compile both `70.0.3538.110-3 and `71.0.3578.98-2` with your changes and it seems to work but it later fails on other issues.

- 70.0.3538.110-3: https://pastebin.com/raw/j9dUJkWD
- 71.0.3578.98-2: https://pastebin.com/raw/ZJEFTCGL

I'm not sure those errors aren't somehow related to Windows Updates. Two weeks ago I was trying to disable safe browsing, I also removed any references to the patches but forget the flag at `gn_flags.map`. At that time I wan't getting this kinds of errors, it was failing later on as you can see here:  https://github.com/Eloston/ungoogled-chromium/issues/639#issuecomment-461983120

**Comment by intika** [comment] 2019-02-23 01:51
Duplicate of https://github.com/Eloston/ungoogled-chromium/issues/675 ?

**Comment by TCB13** [comment] 2019-02-23 01:52
> Duplicate of #675 ?

Yes... the changes proposed by @TN0X fix this issues.

**Comment by intika** [comment] 2019-02-23 02:01
@Eloston can you close this, it will be solved here https://github.com/Eloston/ungoogled-chromium/issues/619

**Comment by TCB13** [comment] 2019-02-23 02:03
@intika #619 doesn't provide solutions, this issue and https://github.com/Eloston/ungoogled-chromium/issues/639 do.

**Comment by intika** [comment] 2019-02-23 02:05
Re enabling safe-browsing is a workaround, the patches needs to be updated to get a real fix

**Comment by TCB13** [comment] 2019-02-23 02:06
That feature was removed so...

**Comment by intika** [comment] 2019-02-23 02:08
@TCB13 can you please develop i am not aware of that

**Comment by lipici** [comment] 2019-03-09 10:04
@hardhub hardhub can you try again with latest version?

**Comment by TCB13** [comment] 2019-03-09 10:07
> @hardhub hardhub can you try again with latest version?

@lipici what do you mean by "latest version", a specific tag or master? Either way, is it even possible to build above 71.0.3578.98-2 under Windows? Seems like there is a lot of broken stuff...

**Comment by warmaster345** [comment] 2019-03-09 11:37
> @hardhub hardhub can you try again with latest version?
I have tried with the latest version, the same error occurred. Windows 10 x64, VS 2017

**Comment by lipici** [comment] 2019-03-09 17:31
Sorry if 71 is still the latest one. I believed chromium has the same version like chrome, in this case, 72.
    On Saturday, March 9, 2019, 12:07:18 PM GMT+2, TCB13 <notifications@github.com> wrote:  
 
 

@hardhub hardhub can you try again with latest version?


@lipici what do you mean by "latest version", a specific tag or master? Either way, is it even possible to build above 71.0.3578.98-2 under Windows? Seems like there is a lot of broken stuff...

**Comment by lipici** [comment] 2019-03-09 17:32
Thanks bro. Sad day for fans.
    On Saturday, March 9, 2019, 1:37:07 PM GMT+2, warmaster345 <notifications@github.com> wrote:  
 
 

@hardhub hardhub can you try again with latest version?
I have tried with the latest version, the same error occurred. Windows 10 x64, VS 2017

**Comment by hardhub** [comment] 2019-03-10 00:56
> 
> 
> @hardhub hardhub can you try again with latest version?

**master:**

```
subprocess.CalledProcessError: Command '['C:\\ungoogled-chromium\\build\\src\\third_party\\git\\usr\\bin\\patch.exe', '-p1', '--ignore-whitespace', '-i', 'C:\\ungoogled-chromium\\build\\src\\ungoogled_packaging\\patches\
\ungoogled-chromium\\windows\\windows-disable-reorder-fix-linking.patch', '-d', 'C:\\ungoogled-chromium\\build\\src', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
```

**72.0.3626.122-1**

```
(Stripping trailing CRs from patch; use --binary to disable.)
patching file chrome/BUILD.gn
Hunk #2 FAILED at 83.
Hunk #3 succeeded at 309 (offset -3 lines).
```

**Comment by lipici** [comment] 2019-03-10 02:12
Ahhh, no luck yet. Thanks, bro.
    On Sunday, March 10, 2019, 2:56:42 AM GMT+2, Maxim <notifications@github.com> wrote:  
 
 

@hardhub hardhub can you try again with latest version?


master:
subprocess.CalledProcessError: Command '['C:\\ungoogled-chromium\\build\\src\\third_party\\git\\usr\\bin\\patch.exe', '-p1', '--ignore-whitespace', '-i', 'C:\\ungoogled-chromium\\build\\src\\ungoogled_packaging\\patches\
\ungoogled-chromium\\windows\\windows-disable-reorder-fix-linking.patch', '-d', 'C:\\ungoogled-chromium\\build\\src', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.

72.0.3626.122-1
(Stripping trailing CRs from patch; use --binary to disable.)
patching file chrome/BUILD.gn
Hunk #2 FAILED at 83.
Hunk #3 succeeded at 309 (offset -3 lines).

**Comment by hardhub** [comment] 2019-03-10 19:58
Tried on master:

(Stripping trailing CRs from patch; use --binary to disable.)
patching file chrome/BUILD.gn
Hunk #2 FAILED at 83.
Hunk #3 succeeded at 309 (offset -3 lines).
1 out of 3 hunks FAILED -- saving rejects to file chrome/BUILD.gn.rej
(Stripping trailing CRs from patch; use --binary to disable.)
patching file tools/perf/chrome_telemetry_build/BUILD.gn
Hunk #1 succeeded at 36 (offset 4 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file chrome/test/chromedriver/BUILD.gn
Hunk #1 succeeded at 364 (offset 7 lines).
Traceback (most recent call last):
  File "ungoogled_packaging\build.py", line 187, in <module>
    main()
  File "ungoogled_packaging\build.py", line 164, in main
    buildkit.patches.patch_paths_by_bundle(bundle), source_tree, patch_bin_path=None)

**Comment by TCB13** [comment] 2019-03-14 22:57
Tried 72.0.3626.122-1:
``````
2019-03-14 22:54:14,811 - INFO: * Applying windows-disable-reorder-fix-linking.patch (115/124)
2019-03-14 22:54:14,811 - DEBUG: C:\ungoogled-chromium\build\src\third_party\git\usr\bin\patch.exe -p1 --ignore-whitespace -i C:\ungoogled-chromium\build\src\ungoogled_packaging\patches\ungoogled-chromium\windows\windows-disable-reorder-fix-linking.patch -d C:\ungoogled-chromium\build\src --no-backup-if-mismatch --forward
(Stripping trailing CRs from patch; use --binary to disable.)
patching file chrome/BUILD.gn
Hunk #2 FAILED at 83.
Hunk #3 succeeded at 309 (offset -3 lines).
1 out of 3 hunks FAILED -- saving rejects to file chrome/BUILD.gn.rej
(Stripping trailing CRs from patch; use --binary to disable.)
patching file tools/perf/chrome_telemetry_build/BUILD.gn
Hunk #1 succeeded at 36 (offset 4 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file chrome/test/chromedriver/BUILD.gn
Hunk #1 succeeded at 364 (offset 7 lines).
``````

**Comment by TCB13** [comment] 2019-03-15 22:11
So, I just tried to compile master after the patches by @r4sas and I got this:

````````
C:\ungoogled-chromium\build\src>"third_party\ninja\ninja.exe" "-C" "out\Default" "chrome" "chromedriver"
ninja: Entering directory `out\Default'
[479/20080] ACTION //chrome/test/chromedriver:embed_version_in_cpp(//build/toolchain/win:win_clang_x64)
ERROR:root:Git error: rc=0, output=''
[11021/20080] RC obj/chrome/elevation_service/elevation_service/elevation_service.res
FAILED: obj/chrome/elevation_service/elevation_service/elevation_service.res
C:/Python27/python.exe ../../build/toolchain/win/tool_wrapper.py rc-wrapper environment.x64 rc.exe /nologo -DV8_DEPRECATION_WARNINGS -DUSE_AURA=1 -DNO_TCMALLOC -DOFFICIAL_BUILD -DCHROMIUM_BUILD "-DCR_CLANG_REVISION=\"346388-5\"" -D_HAS_NODISCARD -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=1 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DNTDDI_VERSION=NTDDI_WIN7 -D_WIN32_WINNT=_WIN32_WINNT_WIN7 -DWINVER=_WIN32_WINNT_WIN7 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -I../.. -Igen -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src /foobj/chrome/elevation_service/elevation_service/elevation_service.res ../../chrome/elevation_service/elevation_service.rc

../../chrome/elevation_service/elevation_service.rc(38) : error RC2135 : file not found: chrome/elevation_service/elevation_service_idl.tlb

[11034/20080] ACTION //chrome/app:generated_resources_grit(//build/toolchain/win:win_clang_x64)
ninja: build stopped: subcommand failed.
````````

Thank you for the continuous effort.

**Comment by r4sas** [comment] 2019-03-16 12:25
I also stopped here, thats why I said about need for additional patching.

**Comment by r4sas** [comment] 2019-03-16 14:09
Looks like something wrong with gn output...
```
rule __chrome_elevation_service_elevation_service_idl_idl_action___build_toolchain_win_win_clang_x64__rule
  command = D$:/devel/Python27/python.exe ../../build/toolchain/win/midl.py environment.x64 gen/chrome/elevation_service none ${source_name_part}.tlb ${source_name_part}.h ${source_name_part}.dlldata.c ${source_name_part}_i.c ${source_name_part}_p.c ${in} /char signed /env x64 /Oicf
  description = ACTION //chrome/elevation_service:elevation_service_idl_idl_action(//build/toolchain/win:win_clang_x64)
  restat = 1
  pool = build_toolchain_action_pool
```
I'm about `${source_name_part}`, `${in}` in command line.

**Comment by warmaster345** [comment] 2019-03-16 23:12
Thanks to @r4sas patches the goal is close, but I'm still getting errors.

```
[15871/20080] CXX obj/chrome/common/media_router/mojo/media_router/media_router_jumbo_1.obj
ninja: build stopped: subcommand failed.
```

**Comment by r4sas** [comment] 2019-03-20 21:53
> Thanks to @r4sas patches the goal is close, but I'm still getting errors.

Can you provide full error info?

**Comment by r4sas** [comment] 2019-03-20 22:09
One question about patch that must fix building with safe browsing disabled: is it really needed?
I'm asking this because in no one folder for other distributions I see identical patch. So maybe it must be rewritten from scratch?

**Comment by tangalbert919** [comment] 2019-03-21 14:26
That patch came in handy for the "tlb" issue, since now I don't need to open a Native Tools cmd for that, but this happens:

`[15799/20080] CXX obj/chrome/common/safe_browsing/file_type_policies/file_type_policies.obj
FAILED: obj/chrome/common/safe_browsing/file_type_policies/file_type_policies.obj

../../chrome/common/safe_browsing/file_type_policies.cc(53,29):  error: use of undeclared identifier 'IDR_DOWNLOAD_FILE_TYPES_PB'
  bundle.GetRawDataResource(IDR_DOWNLOAD_FILE_TYPES_PB).CopyToString(binary_pb);
                            ^
1 error generated.`

**Comment by r4sas** [comment] 2019-03-21 15:01
> That patch came in handy for the "tlb" issue, since now I don't need to open a Native Tools cmd for that, but this happens:


chrome\browser\browser_resources.grd
```
@@ -148,9 +148,7 @@
       <include name="IDR_DOMAIN_RELIABILITY_INTERNALS_HTML" file="resources\domain_reliability_internals.html" compress="gzip" type="BINDATA" />
       <include name="IDR_DOMAIN_RELIABILITY_INTERNALS_CSS" file="resources\domain_reliability_internals.css" compress="gzip" type="BINDATA" />
       <include name="IDR_DOMAIN_RELIABILITY_INTERNALS_JS" file="resources\domain_reliability_internals.js" compress="gzip" type="BINDATA" />
-      <if expr="safe_browsing_mode != 0">
-        <include name="IDR_DOWNLOAD_FILE_TYPES_PB" file="${root_gen_dir}\chrome\browser\resources\safe_browsing\download_file_types.pb" use_base_dir="false" type="BINDATA" />
-      </if>
+      <include name="IDR_DOWNLOAD_FILE_TYPES_PB" file="${root_gen_dir}\chrome\browser\resources\safe_browsing\download_file_types.pb" use_base_dir="false" type="BINDATA" />
       <include name="IDR_DOWNLOAD_INTERNALS_HTML" file="resources\download_internals\download_internals.html" flattenhtml="true" allowexternalscript="true" type="BINDATA" compress="gzip" />
       <include name="IDR_DOWNLOAD_INTERNALS_CSS" file="resources\download_internals\download_internals.css" type="BINDATA" compress="gzip" />
       <include name="IDR_DOWNLOAD_INTERNALS_JS" file="resources\download_internals\download_internals.js" type="BINDATA" compress="gzip" />
```

**Comment by tangalbert919** [comment] 2019-03-21 16:38
I have applied that, only to get this error (and yes, I did look for ways to fix that):
```[4/4281] ACTION //chrome/browser:resources_grit(//build/toolchain/win:win_clang_x64)
FAILED: gen/chrome/resources_stamp.d.stamp gen/chrome/grit/browser_resources.h gen/chrome/browser_resources.pak gen/chrome/browser_resources.pak.info
C:/Python27/python.exe ../../tools/grit/grit.py -i ../../chrome/browser/browser_resources.grd build -o gen/chrome --depdir . --depfile gen/chrome/resources_stamp.d --write-only-new=1 --depend-on-stamp -D _chromium -E CHROMIUM_BUILD=chromium -D toolkit_views -D use_aura -D enable_app_list=false -D enable_arcore=false -D enable_background_mode=true -D enable_background_contents=true -D enable_extensions=true -D enable_hangout_services_extension=false -D enable_plugins=true -D enable_print_preview=true -D enable_printing=true -D enable_service_discovery=false -D enable_vr=true -D safe_browsing_mode=0 -D optimize_webui=false -E additional_modules_list_file=gen/chrome/browser/internal/additional_modules_list.txt -E root_gen_dir=gen -f ../../tools/gritsettings/resource_ids -p ../../tools/gritsettings/startup_resources_win.txt --assert-file-list=obj/chrome/browser/resources_expected_outputs.txt
Error processing node <?xml version="1.0" encoding="UTF-8"?>
<include file="${root_gen_dir}\chrome\browser\resources\safe_browsing\download_file_types.pb" name="IDR_DOWNLOAD_FILE_TYPES_PB" type="BINDATA" use_base_dir="false" />
Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 15, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
  File "D:\Git-Projects\ungoogled-chromium\build\src\tools\grit\grit\grit_runner.py", line 256, in Main
    return toolobject.Run(options, args[1:])
  File "D:\Git-Projects\ungoogled-chromium\build\src\tools\grit\grit\tool\build.py", line 260, in Run
    self.Process()
  File "D:\Git-Projects\ungoogled-chromium\build\src\tools\grit\grit\tool\build.py", line 401, in Process
    self.ProcessNode(self.res, output, outfile)
  File "D:\Git-Projects\ungoogled-chromium\build\src\tools\grit\grit\tool\build.py", line 324, in ProcessNode
    formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "D:\Git-Projects\ungoogled-chromium\build\src\tools\grit\grit\format\data_pack.py", line 83, in Format
    value = node.GetDataPackValue(lang, UTF8)
  File "D:\Git-Projects\ungoogled-chromium\build\src\tools\grit\grit\node\include.py", line 87, in GetDataPackValue
    data = util.ReadFile(filename, util.BINARY)
  File "D:\Git-Projects\ungoogled-chromium\build\src\tools\grit\grit\util.py", line 206, in ReadFile
    with open(filename, mode) as f:
IOError: [Errno 2] No such file or directory: u'..\\..\\out\\Default\\gen\\chrome\\browser\\resources\\safe_browsing\\download_file_types.pb'
[9/4281] CXX obj/components/download/database/database/download_db_conversions.obj
ninja: build stopped: subcommand failed.

**Comment by tangalbert919** [comment] 2019-03-22 00:14
Here's another build error, just after the 90% mark:

```[3385/4273] LINK(DLL) chrome.dll chrome.dll.lib
FAILED: chrome.dll chrome.dll.lib
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /IMPLIB:./chrome.dll.lib /DLL /OUT:./chrome.dll /PDB:./chrome.dll.pdb @./chrome.dll.rsp
lld-link.exe: error: undefined symbol: ?GetMainText@SettingsResetPromptController@safe_browsing@@QEBA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ
>>> referenced by ui.lib(ui_jumbo_9.obj):(??0SettingsResetPromptDialog@@QEAA@PEAVSettingsResetPromptController@safe_browsing@@@Z)


lld-link.exe: error: undefined symbol: ?GetMainTextUrlRange@SettingsResetPromptController@safe_browsing@@QEBA?AVRange@gfx@@XZ
>>> referenced by ui.lib(ui_jumbo_9.obj):(??0SettingsResetPromptDialog@@QEAA@PEAVSettingsResetPromptController@safe_browsing@@@Z)


lld-link.exe: error: undefined symbol: ?DialogShown@SettingsResetPromptController@safe_browsing@@QEAAXXZ
>>> referenced by ui.lib(ui_jumbo_9.obj):(?Show@SettingsResetPromptDialog@@QEAAXPEAVBrowser@@@Z)


lld-link.exe: error: undefined symbol: ?Close@SettingsResetPromptController@safe_browsing@@QEAAXXZ
>>> referenced by ui.lib(ui_jumbo_9.obj):(??1SettingsResetPromptDialog@@UEAA@XZ)
>>> referenced by ui.lib(ui_jumbo_9.obj):(?Close@SettingsResetPromptDialog@@UEAA_NXZ)


lld-link.exe: error: undefined symbol: ?GetWindowTitle@SettingsResetPromptController@safe_browsing@@QEBA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ
>>> referenced by ui.lib(ui_jumbo_9.obj):(?GetWindowTitle@SettingsResetPromptDialog@@UEBA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ)


lld-link.exe: error: undefined symbol: ?GetButtonLabel@SettingsResetPromptController@safe_browsing@@QEBA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ
>>> referenced by ui.lib(ui_jumbo_9.obj):(?GetDialogButtonLabel@SettingsResetPromptDialog@@UEBA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@W4DialogButton@ui@@@Z)


lld-link.exe: error: undefined symbol: ?Accept@SettingsResetPromptController@safe_browsing@@QEAAXXZ
>>> referenced by ui.lib(ui_jumbo_9.obj):(?Accept@SettingsResetPromptDialog@@UEAA_NXZ)


lld-link.exe: error: undefined symbol: ?Cancel@SettingsResetPromptController@safe_browsing@@QEAAXXZ
>>> referenced by ui.lib(ui_jumbo_9.obj):(?Cancel@SettingsResetPromptDialog@@UEAA_NXZ)


lld-link.exe: error: undefined symbol: ?GetInstance@ChromeCleanerController@safe_browsing@@SAPEAV12@XZ
>>> referenced by ui.lib(ui_jumbo_9.obj):(??0ChromeCleanupHandler@settings@@QEAA@PEAVProfile@@@Z)


lld-link.exe: error: undefined symbol: ?FetchExtensionNames@ChromeCleanerScannerResults@safe_browsing@@QEBAXPEAVProfile@@PEAV?$set@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@@std@@@Z
>>> referenced by ui.lib(ui_jumbo_9.obj):(?GetScannerResultsAsDictionary@?A@settings@@YA?AVDictionaryValue@base@@AEBVChromeCleanerScannerResults@safe_browsing@@PEAVProfile@@@Z)


lld-link.exe: error: undefined symbol: ?OnUserAction@ChromePasswordProtectionService@safe_browsing@@QEAAXPEAVWebContents@content@@W4LoginReputationClientRequest_PasswordReuseEvent_ReusedPasswordType@2@W4WarningUIType@2@W4WarningAction@2@@Z
>>> referenced by ui.lib(ui_jumbo_7.obj):(?HandleChangePassword@ChangePasswordHandler@settings@@AEAAXPEBVListValue@base@@@Z)


lld-link.exe: error: undefined symbol: ?ShouldShowChangePasswordSettingUI@ChromePasswordProtectionService@safe_browsing@@SA_NPEAVProfile@@@Z
>>> referenced by ui.lib(ui_jumbo_7.obj):(?UpdateChangePasswordCardVisibility@ChangePasswordHandler@settings@@AEAAXXZ)

[3387/4273] CXX obj/v8/src/inspector/inspector/inspector_jumbo_1.obj
ninja: build stopped: subcommand failed.

**Comment by TCB13** [comment] 2019-03-26 17:00
Having the same issue as @tangalbert919.

**Comment by hardhub** [comment] 2019-04-12 00:20
I tried latest master version (new build instructions) and result is still error:

```
INFO: Applying patches from patches
Traceback (most recent call last):
  File "C:\ungoogled-chromium\utils\patches.py", line 162, in <module>
    main()
  File "C:\ungoogled-chromium\utils\patches.py", line 158, in main
    args.callback(args)
  File "C:\ungoogled-chromium\utils\patches.py", line 116, in _apply_callback
    patch_bin_path=args.patch_bin)
  File "C:\ungoogled-chromium\utils\patches.py", line 35, in apply_patches
    raise ValueError('Could not find the patch binary')
```

**Comment by Eloston** [comment] 2019-04-12 21:38
Closing. Please continue discussin in the referenced issue.

**Closed by Eloston** 2019-04-12 21:38 UTC
