### ISSUE TITLE
System Tray Icon does not appear

### ISSUE THREAD

**Issue by KayGKay** [Eloston/ungoogled-chromium#806] opened 2019-07-30 17:36 UTC
**Describe the bug**
I'm using the Arch Linux binary from [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/archlinux/75.0.3770.142-1). I have enabled "Continue running background apps when Chromium is closed" option in `chrome://settings` -> `advanced` -> `system`. But there is no system tray icon visible. I'm using KDE Plasma 5 on Arch Linux.

**To Reproduce**
1. On Arch Linux with the latest KDE Plasma, download the binary from [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/archlinux/75.0.3770.142-1) and do `pacman -Syu <pkgname>.tar.xz`
2. Run chromium
3. Open `chrome://settings` and scroll down to `advanced` -> `system`
4. Enable "Continue running background apps when Chromium is closed".
5. System tray icon doesn't appear.

**Expected behavior**
Upon enabling, "Continue running background apps when Chromium is closed", a system tray icon should appear.

**Screenshots**
![2019-07-30_22-56](https://user-images.githubusercontent.com/30401343/62151641-50dbfb80-b2f0-11e9-96c8-e9e392061dd7.png)
![2019-07-30_23-01](https://user-images.githubusercontent.com/30401343/62151642-50dbfb80-b2f0-11e9-9417-98e1716170c7.png)
![2019-07-30_23-02](https://user-images.githubusercontent.com/30401343/62151643-51749200-b2f0-11e9-9340-c6a382643a26.png)

**Environment (please complete the following information):**
 - Arch GNU / Linux w/ latest version of KDE Plasma.
 - ungoogled-chromium version: 75.0.3770.142 (Official Build) Arch Linux (64-bit)

**Comment by Eloston** [comment] 2019-07-31 05:26
I'm not too familiar with KDE Plasma. Do they still support system tray icons? Does this happen with other DEs like XFCE?

**Comment by KayGKay** [comment] 2019-07-31 05:50
Yes, they do have system tray icons as you can see in the first screenshot. I have not tested this with other DEs. Let me try with XFCE and report back.

On July 31, 2019 10:56:20 AM GMT+05:30, Eloston <notifications@github.com> wrote:
>I'm not too familiar with KDE Plasma. Do they still support system tray
>icons? Does this happen with other DEs like XFCE?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Eloston/ungoogled-chromium/issues/806#issuecomment-516701170

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KayGKay** [comment] 2019-07-31 09:38
Hello! I just tried on an Xubuntu (18.04) system with the portable binary. No luck.

**Comment by Eloston** [comment] 2019-08-01 05:23
I wonder if there are GN flags that determine whether system tray icons show. Any help here would be appreciated.

**Comment by jstkdng** [comment] 2019-08-01 10:51
Just tested this and it not that the tray icon is not working, the problem is that that functionality doesn't work at all.
After enabling that option and closing chrome, there are no remaining chromium processes.

**Comment by KayGKay** [comment] 2019-08-01 10:58
I can confirm this as well.

On August 1, 2019 4:21:54 PM GMT+05:30, JustKidding <notifications@github.com> wrote:
>Just tested this and it not that the tray icon is not working, the
>problem is that that functionality doesn't work at all.
>After enabling that option and closing chrome, there are no remaining
>chromium processes.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Eloston/ungoogled-chromium/issues/806#issuecomment-517232726

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KayGKay** [comment] 2019-08-25 10:49
The system tray doesn't seem to appear even on Chromium and Brave Browser (Arch Linux).

**Comment by KayGKay** [comment] 2019-09-02 10:07
So I have found a (perhaps, temporary) solution to the problem. After installing this extension: https://chrome.google.com/webstore/detail/background-process/gghpjpjkgffajicbeidilgkogpmianag/ chromium successfully minimizes to system tray.

Found the extension [here](https://bbs.archlinux.org/viewtopic.php?id=234905).

![2019-09-02_15-35](https://user-images.githubusercontent.com/30401343/64107158-61f1af80-cd69-11e9-937e-5b04343820e0.png)

**Comment by KayGKay** [comment] 2019-09-02 10:08
So I have found a (perhaps, temporary) solution to the problem. After installing [this extension](https://chrome.google.com/webstore/detail/background-process/gghpjpjkgffajicbeidilgkogpmianag/), chromium successfully minimizes to system tray.

Found the extension [here](https://bbs.archlinux.org/viewtopic.php?id=234905).

![2019-09-02_15-35](https://user-images.githubusercontent.com/30401343/64107158-61f1af80-cd69-11e9-937e-5b04343820e0.png)

**Comment by Eloston** [comment] 2019-09-04 07:33
@KayGKay I suppose that's why the option is called "Continue running **background apps** when Chromium is closed". It's valid to not run Chromium at all when there are no background apps.

The fact that Chromium and Brave Browser have the same issue probably means it isn't our problem. Otherwise, let us know.

**Closed by Eloston** 2019-09-04 07:33 UTC
Labels: help wanted, need info

**Comment by KayGKay** [comment] 2019-09-04 10:35
There's another extension called TrayEnabler which causes the same result. But in both of these cases, background apps still do not work. What I did was create an "app" out of a webpage (Wire messenger's web version) and as soon as I close the tab or the window, the process ends (as visible in Chromium Task Manager) and only a service worker remains which is not reused if I open the "app" again. 

This is in contrast to Chrome on Windows where the tray icon instantaneously appears when you enable "Continue running background apps when Chromium is closed" option.
