### ISSUE TITLE
Please add search engine support for Google

### ISSUE THREAD

**Issue by Raj2032** [Eloston/ungoogled-chromium#1741] opened 2021-11-22 11:40 UTC
I know Google is hated for a reason and I understand why this project is called _ungoogled_-chromium. But sometimes Google is needed for searching and I would like to have this as my defaut search engine at times.

I was wondering if it could be added into the browser?

**Comment by PF4Public** [comment] 2021-11-22 11:51
Absolutely! You probably need to enable the collection of search engines or manually add google search.

**Comment by networkException** [comment] 2021-11-22 12:18
Duplicate of https://github.com/Eloston/ungoogled-chromium/discussions/1488#discussioncomment-619116

**Closed** 2021-11-22 12:18 UTC
Labels: duplicate

**Comment by Raj2032** [comment] 2021-11-23 09:48
Thanks guys :)
