### ISSUE TITLE
After enabling #dns-over-https, browser constantly connects to DNS Server without visiting any website.

### ISSUE THREAD

**Issue by TontyTon** [Eloston/ungoogled-chromium#1169] opened 2020-09-02 18:47 UTC
**Describe the bug**

EDIT: After enabling #dns-over-https, browser constantly connects to DNS Server without visiting any website. 

>Old
> After enabling and disabling flag #dns-over-https, browser connects to Google and Fastly. 

**To Reproduce**
1. Go to 'chrome://flags/'
2. Enable flag #dns-over-https, and 'Relaunch'
3. Check connections browser make, browser connects to DNS Server.

>Old
> 4. Disable flag #dns-over-https, and 'Relaunch'
> 5. Check connections browser make, browser still connects to Google and Fastly, less connections though.
> 6. Restart browser, browser still connects to Google and Fastly upon restart.
> 7 Set flag #dns-over-https to default, and 'Relaunch'
> 8. Check connections browser make, browser still connects to Google and Fastly, less connections though.
> 9. Restart browser, browser still connects to Google and Fastly upon restart.

**Expected behavior**
Edit: Browser should only connect to DNS server when i try to connect to a website, not everytime.

> Old
> Browser shouldn't connect to Google/Fastly after enabling, user should get option to choose which dns to choose, or use system dns. (I don't know correct term)
> Also, after disabling the flag, all changes made by flag should be reverted.
> 
> This only happens for profile for which flag was changed, other profiles behave as before.

**Screenshots**

Not Applicable

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 2004 x64
 - ungoogled-chromium version:  84.0.4147.125 and 84.0.4147.135 Portable

**Additional context**

P.S. Question - Is it not possible that instead of removing 'bad' stuff from chromium, only 'good' stuff should be taken from it or is integrated only after making 'bad' stuff 'good'?

**Comment by wchen342** [comment] 2020-09-03 00:44
Interesting, the flag exists on Windows, Mac, Android but not Linux..my guess is the connections are using IP addresses (because it is DNS lookup) directly so they slipped through domain substitution. According to the comments in code:
```
// Supply one or more space-separated DoH server URI templates to use when this
// feature is enabled. If no templates are specified, then a hardcoded mapping
// will be used to construct a list of DoH templates associated with the IP
// addresses of insecure resolvers in the discovered configuration.
```

What is the address it is connecting to?

> Question - Is it not possible that instead of removing 'bad' stuff from chromium, only 'good' stuff should be taken from it or is integrated only after making 'bad' stuff 'good'?

What is the definition of 'bad' and 'good' stuff? Also we need a "base" for a browser which involves a rendering engine, which in the case of chromium is blink. If you want to take functionality of chromium onto a different browser then it will be more like a modified version of anything browser like gecko/firefox.

**Comment by Ahrotahn** [comment] 2020-09-03 01:04
> my guess is the connections are using IP addresses (because it is DNS lookup) directly so they slipped through domain substitution

You seem to be spot on!  There is a hardcoded list of DoH providers in `net/dns/public/doh_provider_entry.cc` that uses IPs.  

I'm not yet sure why it would still attempt the connection after disabling DoH though.

**Comment by TontyTon** [comment] 2020-09-03 05:10
> What is the address it is connecting to?

I don't know the web address it tries to connect, I checked the IPs browser tries to connect.


> What is the definition of 'bad' and 'good' stuff? Also we need a "base" for a browser which involves a rendering engine, which in the case of chromium is blink. If you want to take functionality of chromium onto a different browser then it will be more like a modified version of anything browser like gecko/firefox.

By bad stuff I mean features/changes which connect to Google and by good stuff I mean features/changes which don't connect to Google or others servers.
I wanted to ask that when you are updating browser, at that time merge only the changes made in Chromium which don't break 'sans integration with Google' and for changes which break it make necessary chenges and then merge? (or you do like this only?)

> I'm not yet sure why it would still attempt the connection after disabling DoH though.

Ya, thats the thing which troubles me the most, as now even after disabling the flag my browser connects to Google and Fastly upon start and later too.

**Comment by wchen342** [comment] 2020-09-03 10:44
> I'm not yet sure why it would still attempt the connection after disabling DoH though.

Maybe have something to do with `fieldtrial_testing_like_official_build`, since it's a testing function?

> I wanted to ask that when you are updating browser, at that time merge only the changes made in Chromium which don't break 'sans integration with Google' and for changes which break it make necessary chenges and then merge? (or you do like this only?)

Do you mean a binary diff update for UC? Because if you are talking about codes it doesn't make much sense since everything here are basically patches.

**Comment by TontyTon** [comment] 2020-09-03 18:32
Ya, thats what I want to ask.
I don't know technical terms so to be clear, I would give you example -
Take latest/any version (call it base) of chromium, apply all the UC patches, test it to check if changing some setting breaks 'sans integration...'.
Then, to update, check the code of 'changes made to chromium' after base, and only merge the ones which don't break 'sans integration...' and for changes that break it make the necessary changes.

Am I clear now?
Is it possible to do, or includes a lot of unnecessary effort?

I think it would be better as then issues like this can't happen.\
 ---

Also please suggest what can I do now to prevent the connections, this is saved somewhere in profile folder. I think most probably, 'preferences' or 'secure preferences'.

**Comment by Ahrotahn** [comment] 2020-09-03 23:10
The way the UC project handles things is a bit different compared to others.  UC isn't actually a fork, it's just a collection of patches applied on top of chromium.  

To frame your original question using an analogy:  It would be like going in to surgery to have your appendix removed and asking the doctor to only take the parts of you that are still good rather than simply removing the appendix.  
<hr>
I spun up a win7 VM I had to test this out (the DoH flag is not available on linux as @wchen342 mentioned, I haven't dug into the reasoning on that).  

I couldn't reproduce the issue using tangalbert919's build.  I didn't see any new connections both before and after toggling the flag and restarting.  That hardcoded list should only be used to map non-DoH DNS servers to an equivalent DoH enabled one (that list is still something that should be addressed though).  

If you wouldn't mind giving us some extra info:
Whose windows build are you using?  
What dns servers is your system set to use?  And your router's?
Are you using any addons, if so which ones? 
What page do you have set to load on startup?
How are you verifying the connection attempts?

**Comment by TontyTon** [comment] 2020-09-06 18:29
> To frame your original question using an analogy: It would be like going in to surgery to have your appendix removed and asking the doctor to only take the parts of you that are still good rather than simply removing the appendix.

Yes, I was asking this only, but this sound really bad for human body xD. Is this not possible to do?

---
> Whose windows build are you using?

I am also using tangalbert919's build.
> What dns servers is your system set to use? And your router's?

I set to Cloudflare in windows, after the issue, before it wasn't set to anything. I think default is Google, thats why it was making connections to Google.

> Are you using any addons, if so which ones?

I checked on a new profile (without extensions), enabled the flag, but I saw connections to Cloudflare without even opening any website, browser was making connections constantly if browser was left open.

But I didn't see these connections after disabling the flag. Maybe it was extensions but i never saw those connections earlier.
I enabled and disabled flag on v84.0.4147.125 but now I am on v84.0.4147.135 So, update might have corrected it.
Now, Browser is not making connections on the old profile too, after disabling and enabling the flag. But, do make connections to Cloudflare when flag is enabled.
Sorry, I didn't check earlier with all extensions disabled.
> What page do you have set to load on startup?

None in both profiles.
> How are you verifying the connection attempts?

Using LiveTcpUdpWatch. (nirsoft.net)

If I see connections to Google or Fastly again, I will update here.
So, now the issue is only about connections to dns server, when flag is enabled.

**Comment by Ahrotahn** [comment] 2020-09-08 00:20
> Yes, I was asking this only, but this sound really bad for human body xD. Is this not possible to do?

Possible, yes.  But it would be much more effort than the way it's currently being done.  

<br>

I'm not familiar with how LiveTcpUdpWatch shows the connections, but do the they come in bursts of four at a time?  It's possible what you're seeing are SSDP broadcasts (should be fixed in version 85+).  Otherwise this has me stumped for now until I can get more time to dig into it.  One other thing you could try is clearing out any of the "Most visited" tiles and set your search provider to "No search" just to rule out favicon downloads.

**Comment by TontyTon** [comment] 2020-09-09 04:17
> Possible, yes. But it would be much more effort than the way it's currently being done.
 
Ok 
> do the they come in bursts of four at a time? It's possible what you're seeing are SSDP broadcasts (should be fixed in version 85+).

No, They are not SSDP, they use TCP, on port 443.

> you could try is clearing out any of the "Most visited" tiles and set your search provider to "No search" just to rule out favicon downloads.

No, they are not affecting the connections. There are still connections to Cloudflare.

**Comment by TontyTon** [comment] 2020-09-21 18:37
What info do you need? I can try to provide you.

**Comment by Eloston** [comment] 2020-09-27 22:41
I don't think there's anything we need from you specifically @TontyTon, we just need more info about the code.

**Comment by TontyTon** [comment] 2020-09-29 08:56
Oh ok Thanks for looking into the issue.

**Comment by TontyTon** [comment] 2021-11-14 07:32
@PF4Public I would describe what's the behaviour currently, then you can decide if it's an 'issue' or not.

In v95, as soon as I start the browser, browser makes 2 connections to the dns service (tried with Cloudflare and Quad 9), and keep both connections 'Established' for some time but don't send or receive packets if I don't visit a site. This I did with 'No Search' as the defualt search engine, to be sure that dns connection is not being made to resolve the search engine's url.

If no website is visited for sometime (that is, no address need to be resolved), then the connections are closed. Now connections are made when I try to visit a website (that is an address need to resolved).

I think this approach is good enough. You can close the issue if you also think so.

**Comment by PF4Public** [comment] 2021-11-15 13:29
@Ahrotahn is it OK to close this issue?

**Closed** 2021-11-16 16:14 UTC
Labels: help wanted, need info
