### ISSUE TITLE
Unable to Build in Windows 10

### ISSUE THREAD

**Issue by rlsbrowning** [Eloston/ungoogled-chromium#1104] opened 2020-07-14 04:18 UTC
Whenever I try to run the py build.py command in admin CMD, having tried both Python 3.8.3 and 3.7.7, I get the following error:
![Capture (1)](https://user-images.githubusercontent.com/36653213/87383036-aaffbc00-c555-11ea-9cb5-fa0a80465a6c.png)

1. Run the following command: "git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-windows.git"
2. cd into the ungoogled-chromium-windows folder
3. Run the following command: "git checkout --recurse-submodules 81.0.4044.138-1.1"
4. Run the following command: "py build.py"

You should recieve the same error message I have shown above.

 - OS/Platform and version: Windows 10
 - ungoogled-chromium version: 81.0.4044.138-1.1

I have set up the Build Environment as follows:
- Followed the build instructions for Ungoogled Chromium listed under "Visual Studio" here: https://chromium.googlesource.com/chromium/src/+/refs/tags/81.0.4044.113/docs/windows_build_instructions.md#visual-studio
- Installed 7-Zip
- Installed Python 3.8.3, also selected Add to Path and the option to lift the MAX_LENGTH restriction
- Installed Python 2.7.18 with pypiwin32 module
- Installed Git with "Git from the command line and also from 3rd-party software"

**Comment by wchen342** [comment] 2020-07-14 13:04
Try add `stdout=subprocess.PIPE,` after line 81 of `build.py`?

**Comment by rlsbrowning** [comment] 2020-07-14 22:35
Tried the suggestion, still getting the same error message.

**Comment by wchen342** [comment] 2020-07-14 23:33
Maybe because of [this issue](https://stackoverflow.com/questions/466801/python-piping-on-windows-why-does-this-not-work)?

**Comment by rlsbrowning** [comment] 2020-07-16 04:10
I don't think so, that looks like a completely different error output than what I've been getting.

**Comment by wchen342** [comment] 2020-07-16 04:14
Did you try the methods though? The error you are getting is because somehow your CMD did not return anything as `stdout` from the subprocess called (which is supposedly to be a python2 in your case). AFAIK this is will not happen on *nix systems so that is why I ended up finding this solution.

**Comment by Eloston** [comment] 2020-07-17 20:26
What do you get when you run command `python`? Does Python 2 launch?

**Comment by rlsbrowning** [comment] 2020-07-22 05:59
Not sure if this is what you're looking for, but it looks like Python 3 launches, I reset the command prompt though so that may affect the results: 
![Capture](https://user-images.githubusercontent.com/36653213/88140046-38728a00-cbae-11ea-9d32-42abaacf5ee3.PNG)

**Comment by kevin-ferrier** [comment] 2020-07-25 11:07
"Make sure Python 2.7 is set in the user or system environment variable PATH as python."
From the readme.
python command should point to your python2.7 version and py should be python 3.8.3.

```sh
# install virtualenv
pip install virtualenv

cd /path/to/your/chromium_git_folder

# create the virtual environment (check the python path for your python 2.7.18 version)
python -m virtualenv .venvwindows -p C:\Python27\python.exe
.venvwindows\Scripts\activate.bat

# install python2 libraries
pip install pypiwin32

# check python versions
python --version # should give you python 2.7.18

py --version # should give you 3.8.3
```
If py isn't giving you python3 you can also create an alias and use py3 to run it for instance
`set "py3=C:\Users\your_user_name\AppData\Local\Programs\Python\Python38-38\python.exe"`


You can leave the virtual environment by typing
`deactivate`

**Comment by lipici** [comment] 2020-07-31 02:55
any new progress? anyone else its working on building windows version ?

**Comment by Eloston** [comment] 2020-08-04 01:31
Closing because Windows updated to version 84.

**Closed by Eloston** 2020-08-04 01:31 UTC

**Comment by r4sas** [comment] 2020-08-04 12:10
> > Closing because Windows updated to version 84.
> 
> I only see the **81.0.4044.138-1.1** as latest. Where can I get a new version? On this page, there is only the source code, and I don't know how to merge it, and my PC is probably quite slow for it: https://github.com/ungoogled-software/ungoogled-chromium-windows

Please wait for anyone who will compile it. That can take from 8 hours.

**Comment by PF4Public** [comment] 2020-08-04 12:27
>Please wait for anyone who will compile it. That can take from 8 hours.

I think the problem is that _nobody_ does that since 81.

I was thinking some time ago to start compiling and uploading Windows binaries, but unfortunately, don't have sufficient time for that atm.

**Comment by r4sas** [comment] 2020-08-04 14:02
I started build some time ago, maybe tomorrow upload it for x64 firstly.

**Comment by Marek33** [comment] 2020-08-04 15:01
@r4sas  
>> > Closing because Windows updated to version 84.
> > 
> > 
> > I only see the **81.0.4044.138-1.1** as latest. Where can I get a new version? On this page, there is only the source code, and I don't know how to merge it, and my PC is probably quite slow for it: https://github.com/ungoogled-software/ungoogled-chromium-windows
> 
> Please wait for anyone who will compile it. That can take from 8 hours.

I understand, but I thought, that it was released, since Eloston has closed it.

@PF4Public 
> > Please wait for anyone who will compile it. That can take from 8 hours.
> 
> I think the problem is that _nobody_ does that since 81.
> 
> I was thinking some time ago to start compiling and uploading Windows binaries, but unfortunately, don't have sufficient time for that atm.

There are other two versions, but for some very weird reason, the browser, doesn't have a toolbar, and they have a different Audio formats, which is weird as well.

**Comment by r4sas** [comment] 2020-08-04 17:29
> I understand, but I thought, that it was released, since Eloston has closed it.

That version was released, and that was all what he doing about that repository. Builds provided by users.

**Comment by Marek33** [comment] 2020-08-04 21:04
> > I understand, but I thought, that it was released, since Eloston has closed it.
> 
> That version was released, and that was all what he doing about that repository. Builds provided by users.

Yes, now its released, but it wasn't before. I do hope though, there will be a classic version, without the installer, since it's way better, without that. _Thou, the installer doesn't seem to work for me._

Also, I hope, that your version is without the installer.

**Comment by lipici** [comment] 2020-08-04 21:08
thanks for the 84 version, all great

**Comment by r4sas** [comment] 2020-08-05 10:31
> Also, I hope, that your version is without the installer.

You can find them [here](https://github.com/r4sas/ungoogled-chromium-binaries/releases/tag/84.0.4147.105-1.1).

**Comment by Marek33** [comment] 2020-08-05 13:55
> > Also, I hope, that your version is without the installer.
> 
> You can find them [here](https://github.com/r4sas/ungoogled-chromium-binaries/releases/tag/84.0.4147.105-1.1).
> Now starting build for x86.

Thanks! Everything seems to be fine, but I don't get, why I need to open a new window, since in normal session, I don't have a visible toolbar, and I can move the browser window, even if it's maximized.

Also, do you have a Discord or an email at least?

**Comment by r4sas** [comment] 2020-08-05 16:15
> Everything seems to be fine, but I don't get, why I need to open a new window, since in normal session, I don't have a visible toolbar, and I can move the browser window, even if it's maximized.

Can you post screenshot of issue, can't understand correctly.


> Also, do you have a Discord or an email at least?

I think better discus such things here, neither in PM because here can be problem with chromium itself.

**Comment by Marek33** [comment] 2020-08-05 16:23
> > Everything seems to be fine, but I don't get, why I need to open a new window, since in normal session, I don't have a visible toolbar, and I can move the browser window, even if it's maximized.
> 
> Can you post screenshot of issue, can't understand correctly.
> 
> > Also, do you have a Discord or an email at least?
> 
> I think better discus such things here, neither in PM because here can be problem with chromium itself.

Yes, here: ![Chromium 84](https://user-images.githubusercontent.com/19204886/89438174-c7ec7100-d748-11ea-88be-ec722cdd178c.jpg)

Alright.

**Comment by r4sas** [comment] 2020-08-05 16:26
Which one toolbar? With bookmarks?

**Comment by Marek33** [comment] 2020-08-05 16:56
> Which one toolbar? With bookmarks?

No, the upper toolbar, with the minimize, maximize, and close.

And, whenever, I add the engaged to the next of the start menu, it doesn't have these two flags enabled: _-disable-webgl and -ignore-certificate-errors_. I have to have the second thing enabled, since there is some problem with the Chromium on my system, and I don't know, where exactly.

Also, do you know, if its possible to change the Permissions and Media devices to the Timeout? I think it can be changed in Firefox, but no idea, about the Chromium.

**Comment by r4sas** [comment] 2020-08-05 18:11
Ah, I think issue in your system and less possible in chromium. I haven't such problem on Windows 8.1.

**Comment by Marek33** [comment] 2020-08-05 18:23
@r4sas So, you don't have any of those problems on Win 8.1?

That's weird, since no previous versions had that. I'm using Win7 64bit.

Also, what about those two things?

**Comment by r4sas** [comment] 2020-08-06 11:39
> @r4sas So, you don't have any of those problems on Win 8.1?

![image](https://user-images.githubusercontent.com/7023612/89527696-700a4480-d7f2-11ea-903b-6988cef06fc0.png)
No problems here.

Maybe something changed in chrome about supporting Win7? Have you checked Chrome itself?

**Comment by r4sas** [comment] 2020-08-06 11:40
> Now starting build for x86.

Builded and added, available as same [place](https://github.com/r4sas/ungoogled-chromium-binaries/releases/tag/84.0.4147.105-1.1).

**Comment by Marek33** [comment] 2020-08-06 11:51
> 
> No problems here.
> 
> Maybe something changed in chrome about supporting Win7? Have you checked Chrome itself?

No, not yet, but I will. Thou, since the Brave has no issues, I don't think that the normal Chrome would have some problems.

That's weird, but as I can see, you also have the card, a bit lower, than usual. When I open a new window, its fixed, but on the normal one, it's almost the same as you have, except the blinding white color and the missing three buttons in the top right.

Also, what are those four extensions, expect Adguard, and the Ghostery?

**Comment by r4sas** [comment] 2020-08-06 11:59
> No, not yet, but I will. Thou, since the Brave has no issues, I don't think that the normal Chrome would have some problems.

You can try @Mathew-D build, I'm building with MSVC17, maybe he build it with MSVC19 and here will be some differencies.
I remember that I got such issue when using Remote Desktop (RDP) to connect to my computer. After disconnecting and logging in back locally, sometimes such bug happens. Only full chromium restart helps.

> Also, what are those four extensions, expect Adguard, and the Ghostery?

Mailvelope, ScriptSafe, Nimbus Screenshot, SwitchyOmega.

**Comment by PF4Public** [comment] 2020-08-06 12:01
> Remote Desktop (RDP) to connect to my computer. After disconnecting and logging in back locally, sometimes such bug happens. Only full chromium restart helps.

Could it be related to GPU then?

**Comment by r4sas** [comment] 2020-08-06 12:02
> Could it be related to GPU then?

I think it can be related to OpenGL or D3D (idk what chromium uses by default).

**Comment by PF4Public** [comment] 2020-08-06 12:08
> You can try @Mathew-D build,

Turns out there are a lot of people, building binaries, they just don't submit them here… I wasn't aware of that.


> I think it can be related to OpenGL or D3D

Yeah, I meant that. @Marek33  you could you try disabling GPU related features in chrome://flags/ like hardware acceleration, rasterisation and so on.


> However, why it should be related to that?

That's probably how they draw the window, ain't it?

**Comment by Marek33** [comment] 2020-08-06 12:17
> > You can try @Mathew-D build,
> 
> Turns out there are a lot of people, building binaries, they just don't submit them here… I wasn't aware of that.

Indeed, it's a pity that they don't submit it, anywhere.

> > I think it can be related to OpenGL or D3D
> 
> Yeah, I meant that. @Marek33 you could you try disabling GPU related features in chrome://flags/ like hardware acceleration, rasterisation and so on.

Thanks! I will try it.

> > However, why it should be related to that?
> 
> That's probably how they draw the window, aren't they?

Probably, but why when I open a new window, it's just like it should be?

> > I doubt that it's a GPU issue, since I have the same GPU, since I first discovered the Ungoogled Project.
> 
> Not the GPU itself. I meant the code that Chromium uses to interact with it.

I understand, and thanks for the info!

**Comment by PF4Public** [comment] 2020-08-06 12:22
> Probably, but why when I open a new window, it's just like it should be?

No idea. Try changing the theme, if you ever changed it from the default.

**Comment by Marek33** [comment] 2020-08-06 12:39
> > Probably, but why when I open a new window, it's just like it should be?
> 
> No idea. Try changing the theme, if you ever changed it from the default.
> 
> I remember experiencing a similar issue on Linux (max/min/close buttons absent) a while ago, but it solved itself really quick, I didn't have to do anything, just updated a single revision up.

Thanks for the tip! It seems that the issue is fixed, by removing the Porshe theme. It's really pity, that I have to remove that theme, since it's way better, than the normal white background, but after I add it back, there are no issues, and that's the main thing.
