### ISSUE TITLE
[Help] Widevine CDM Gentoo

### ISSUE THREAD

**Issue by WillPower3309** [Eloston/ungoogled-chromium#1135] opened 2020-08-14 03:30 UTC
After looking into widevine cdm and checking over the commonly asked questions documentation, I attempted to add it via
`wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`
and then copying the `opt/WidevineCdm` folder into my `/opt/chromium-browser` folder, to no avail. Am I missing something?

**Comment by PF4Public** [comment] 2020-08-14 07:20
Which version of chromium are you using, AFAIK widevine version should correspond to chromium version.
Do you use binary version of ungoogled-chromium or build from source?

**Comment by WillPower3309** [comment] 2020-08-14 13:14
Thanks for the response! I use the binary version

**Comment by PF4Public** [comment] 2020-08-14 14:11
If you're using binary from my overlay, it might be built without widevine support.

**Comment by WillPower3309** [comment] 2020-08-14 19:53
@PF4Public Ah yes, I think that is the case, ill try building it

**Comment by Eloston** [comment] 2020-08-15 17:55
Closing, unless the problem is not resolved.

**Comment by WillPower3309** [comment] 2020-08-17 23:06
After building the non binary package, I can observe Widevine Content Decryption Module in the chrome://components/ page, however it is displayed as version 0.0.0.0, and i cannot check for an update. It also does not work on sites such as netflix

**Comment by Eloston** [comment] 2020-08-20 02:35
Do you need to make a build config change to enable Widevine support?

**Comment by WillPower3309** [comment] 2020-08-23 16:59
[](https://i.imgur.com/NfktIuH.png)

I'm unsure, havent delved into build configs too much yet.
As you can see, it appears on chrome://components, however does not work on sites like netflix

**Comment by jstkdng** [comment] 2020-08-23 19:27
Maybe you need to symlink the .so to the chromium root?
![image](https://user-images.githubusercontent.com/52050345/90986938-74ea2a80-e54c-11ea-97f0-ea11cd26b818.png)
That is the file structure of chromium-widevine under arch, and sure enough, it is symlinked
```
$ file /usr/lib/chromium/libwidevinecdm.so
/usr/lib/chromium/libwidevinecdm.so: symbolic link to WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so
```
And chromium recognizes it correctly
![image](https://user-images.githubusercontent.com/52050345/90986964-a9f67d00-e54c-11ea-91ce-8746587462be.png)
The update error is nothing to worry about imo.

**Comment by WillPower3309** [comment] 2020-08-23 20:10
Hmm, that could very well be the issue, I don't even have a `usr/lib/chromium` folder, if I was to create it where would I symlink the libwidevinecdm.so file from?

**Comment by jstkdng** [comment] 2020-08-23 20:18
The `/usr/lib/chromium/` folder structure is used by arch, gentoo uses `/opt/chromium-browser`, you should symlink libwidevinecdm.so to `/opt/chromium-browser`

**Comment by PF4Public** [comment] 2020-08-24 11:55
Gentoo also uses /usr/lib64/chromium for Chromium

**Comment by jstkdng** [comment] 2020-08-24 18:59
wait what, then why does @WillPower3309 has their install root on /opt/chromium-browser? custom build maybe? oh well, the symlink should be on the same directory as the chromium binary, or however it is named on gentoo.

**Comment by WillPower3309** [comment] 2020-08-26 04:22
```
ls /usr/lib64/chromium-browser
chrome                  chromium-launcher.sh  libGLESv2.so          libvulkan.so  resources.pak
chrome_100_percent.pak  headless_lib.pak      libVkICD_mock_icd.so  locales       snapshot_blob.bin
chrome_200_percent.pak  libEGL.so             libvk_swiftshader.so  resources     v8_context_snapshot.bin
```

appears as though it is indeed missing

**Comment by PF4Public** [comment] 2020-08-26 11:32
So, @WillPower3309 , did you manage to make it work?

**Comment by WillPower3309** [comment] 2020-08-26 13:41
> So, @WillPower3309 , did you manage to make it work?

Unfortunately not, tried this morning and got libwidevinecdm.so from a couple different locations (most recently tried this lil guy):
```
#!/bin/bash
LATEST=`curl https://dl.google.com/widevine-cdm/current.txt`
wget https://dl.google.com/widevine-cdm/$LATEST-linux-x64.zip
```

And still same issue, shows as version 0.0.0.0 in `chrome://components`

**Comment by PF4Public** [comment] 2020-08-26 14:14
They have released 85 Chromium yesterday, so that $LATEST might point to 85-compatible one instead, but don't quote me on that, I may be wrong.

**Comment by zz64** [comment] 2020-10-24 11:31
Hi, using www-client/ungoogled-chromium-bin-86.0.4240.80_p1 from PF4Public, widevine not enabled.
![image](https://siasky.net/PAHiR6Hunv0BayiEfLYQ4KrbVANl649Xq_pXRSPD_yGGUA)

![image](https://siasky.net/rAAMWQU8xzZA6zdOyUlmWgqbrzrv959gKrJ7GPo-WR7WbQ)

Any solution ?
Thanks.

**Comment by PF4Public** [comment] 2020-10-24 16:14
> using www-client/ungoogled-chromium-bin-86.0.4240.80_p1 from PF4Public, widevine not enabled.

https://github.com/Eloston/ungoogled-chromium/issues/1135#issuecomment-674094167

> Any solution ?

https://github.com/Eloston/ungoogled-chromium/issues/1135#issuecomment-674246596

**Comment by zz64** [comment] 2020-10-24 16:45
> > using www-client/ungoogled-chromium-bin-86.0.4240.80_p1 from PF4Public, widevine not enabled.
> 
> [#1135 (comment)](https://github.com/Eloston/ungoogled-chromium/issues/1135#issuecomment-674094167)
> 
![image](https://siasky.net/XAEU_c71Si9nM2nJLXPjIKAREPNj--digtdkuGn3Plp_Jw)

**Comment by zz64** [comment] 2020-10-24 16:51
any way, Thankyou PF4Public for your work and ungoogled support for Gentoo :)

**Comment by PF4Public** [comment] 2020-10-24 17:46
@zz64 so, with `widevine` USE flag enabled in -bin, it doesn't seem to be functional? Did I get it right?

I should probably remove this use flag from -bin version, as all of them are built with "enable_widevine=false", so that this should not work. I can't remember, why was `widevine` USE flag incorporated into -bin at the first place. I probably thought, that adding a widevine .so would be enough. Looks like, it is not.

I would suggest @zz64 to build ungoogled-chromium from source (i.e. not using -bin), enabling `widevine` USE flag, like I suggested earlier. But if that doesn't make it work, I won't be of much help, as I don't use widevine myself, so cannot verify or help with it further.

Also, @WillPower3309 have you in the end succeeded or not?

**Comment by zz64** [comment] 2020-10-24 18:43
Yeah, I don't like to use binaries, for this reason I'm on Gentoo :-)
I am waiting for ungoogled-chromium (source) version compatible with libvpx-1.9.x, and after that, I compile it with widevine support.

**Comment by WillPower3309** [comment] 2020-10-29 19:02
@PF4Public I had to reinstall my system and have yet to recompile ungoogled chromium. I can confirm that on the version compiled from the AUR widevine support works once installed, but have yet to test the ebuild.

**Comment by PF4Public** [comment] 2020-10-29 20:19
>I can confirm that on the version compiled from the AUR widevine support works once installed

Well, we can "diff" things and find a way to make it work then.

**Comment by Eloston** [comment] 2021-01-02 01:17
From my experimentations, I know for Portable Linux, just enabling `enable_widevine=true` is sufficient, but I can't place the WidevineCdm files in `~/.local/lib`; I have to place it next to the Chromium files and then ensure that `WidevineCdm/latest-component-updated-widevine-cdm` in my User Data Directory contains the path to the WidevineCdm among the Chromium files (launching Chromium once might be enough to create it, but it might not take effect until the next launch).

It would be nice to eliminate the need for `latest-component-updated-widevine-cdm` and re-enable use of `~/.local/lib`, though.

**Comment by zz64** [comment] 2021-01-03 10:19
Hello, is fixed for me (build from PF4Public source)

here my config:
```
ls -la /usr/lib/chromium-browser
lrwxrwxrwx 1 root root 27  3 déc.  21:06 /usr/lib/chromium-browser -> /usr/lib64/chromium-browser
```

```
ls -la /usr/lib64/chromium-browser/
total 219720
drwxr-xr-x   5 root root      4096  8 déc.  23:19 .
drwxr-xr-x 127 root root    159744 24 déc.  19:03 ..
-rwxr-xr-x   1 root root 176847264  8 déc.  18:04 chrome
-rw-r--r--   1 root root    772425  8 déc.  18:03 chrome_100_percent.pak
-rw-r--r--   1 root root   1359432  8 déc.  18:03 chrome_200_percent.pak
-rwxr-xr-x   1 root root  11700048  8 déc.  18:04 chromedriver
-rws--x--x   1 root root     15680  8 déc.  18:04 chrome-sandbox
-rwxr-xr-x   1 root root      1624  8 déc.  18:03 chromium-launcher.sh
-rwxr-xr-x   1 root root    832936  8 déc.  18:04 convert_dict
-rw-r--r--   1 root root   4499492  8 déc.  18:03 headless_lib.pak
-rw-r--r--   1 root root  10527632  8 déc.  18:03 icudtl.dat
-rw-r--r--   1 root root     24408  8 déc.  18:04 libEGL.so
-rw-r--r--   1 root root   7381032  8 déc.  18:04 libGLESv2.so
-rw-r--r--   1 root root    115552  8 déc.  18:04 libVkICD_mock_icd.so
-rw-r--r--   1 root root   3734792  8 déc.  18:04 libvk_swiftshader.so
-rw-r--r--   1 root root    265008  8 déc.  18:04 libvulkan.so
lrwxrwxrwx   1 root root        58  3 déc.  21:12 libwidevinecdm.so -> WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so
drwxr-xr-x   2 root root      4096  8 déc.  23:19 locales
drwxr-xr-x   4 root root      4096  2 déc.  12:07 resources
-rw-r--r--   1 root root   6472889  8 déc.  18:03 resources.pak
-rw-r--r--   1 root root     51553  8 déc.  18:03 snapshot_blob.bin
-rwxr-xr-x   1 root root      1680  8 déc.  18:03 update-dicts.sh
-rw-r--r--   1 root root    172386  8 déc.  18:03 v8_context_snapshot.bin
drwxr-xr-x   3 root root      4096  3 déc.  21:08 WidevineCdm
```

**Comment by mrturcot** [comment] 2021-01-16 00:01
Hmm I dont even have that directory..

```
# ls -la /usr/lib/chromium-browser
ls: cannot access '/usr/lib/chromium-browser': No such file or directory
```

And in lib64 no widevine system links...

```
$ ls  -la /usr/lib64/chromium-browser/
total 186688
drwxr-xr-x  4 root root      4096 Jan 15 12:05 .
drwxr-xr-x 98 root root    143360 Jan 15 12:05 ..
-rwxr-xr-x  1 root root 166112520 Jan 15 12:05 chrome
-rw-r--r--  1 root root    772380 Jan 15 12:05 chrome_100_percent.pak
-rw-r--r--  1 root root   1359387 Jan 15 12:05 chrome_200_percent.pak
-rwxr-xr-x  1 root root      1624 Jan 15 12:05 chromium-launcher.sh
-rw-r--r--  1 root root   4489558 Jan 15 12:05 headless_lib.pak
-rw-r--r--  1 root root     34520 Jan 15 12:05 libEGL.so
-rw-r--r--  1 root root   6981368 Jan 15 12:05 libGLESv2.so
-rw-r--r--  1 root root    132760 Jan 15 12:05 libVkICD_mock_icd.so
-rw-r--r--  1 root root   3815960 Jan 15 12:05 libvk_swiftshader.so
-rw-r--r--  1 root root    263984 Jan 15 12:05 libvulkan.so
drwxr-xr-x  2 root root      4096 Jan 15 12:05 locales
drwxr-xr-x  4 root root      4096 Jan 15 12:05 resources
-rw-r--r--  1 root root   6792946 Jan 15 12:05 resources.pak
-rw-r--r--  1 root root     51553 Jan 15 12:05 snapshot_blob.bin
-rw-r--r--  1 root root    172386 Jan 15 12:05 v8_context_snapshot.bin
```

emereged with USE="widevide"

**Comment by PF4Public** [comment] 2021-01-16 08:45
I've examined Gentoo ebuild for www-plugins/chrome-binary-plugins:
```sh
src_install() {
	insinto "/usr/$(get_libdir)/chromium-browser"
	doins -r WidevineCdm
}
```

I suppose, that merely installing www-plugins/chrome-binary-plugins should suffice. If that's true, adding it as a depedency for widevine should solve this issue once and for all. Could someone test it?

**Comment by mrturcot** [comment] 2021-01-16 10:06
> I've examined Gentoo ebuild for www-plugins/chrome-binary-plugins:
> 
> ```shell
> src_install() {
> 	insinto "/usr/$(get_libdir)/chromium-browser"
> 	doins -r WidevineCdm
> }
> ```
> 
> I suppose, that merely installing www-plugins/chrome-binary-plugins and adding a symlink should suffice. If that's true, adding it as a dependency for widevine should solve this issue once and for all. Could someone test it?

That did the trick ;)

```
/usr/lib64/chromium-browser # ls -al
total 186696
drwxr-xr-x  5 root root      4096 Jan 16 01:59 .
drwxr-xr-x 98 root root    143360 Jan 15 23:27 ..
-rwxr-xr-x  1 root root 166112520 Jan 15 12:05 chrome
-rw-r--r--  1 root root    772380 Jan 15 12:05 chrome_100_percent.pak
-rw-r--r--  1 root root   1359387 Jan 15 12:05 chrome_200_percent.pak
-rwxr-xr-x  1 root root      1624 Jan 15 12:05 chromium-launcher.sh
-rw-r--r--  1 root root   4489558 Jan 15 12:05 headless_lib.pak
-rw-r--r--  1 root root     34520 Jan 15 12:05 libEGL.so
-rw-r--r--  1 root root   6981368 Jan 15 12:05 libGLESv2.so
-rw-r--r--  1 root root    132760 Jan 15 12:05 libVkICD_mock_icd.so
-rw-r--r--  1 root root   3815960 Jan 15 12:05 libvk_swiftshader.so
-rw-r--r--  1 root root    263984 Jan 15 12:05 libvulkan.so
lrwxrwxrwx  1 root root        86 Jan 16 01:59 libwidevinecdm.so -> /usr/lib64/chromium-browser/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so
drwxr-xr-x  2 root root      4096 Jan 15 12:05 locales
drwxr-xr-x  4 root root      4096 Jan 15 12:05 resources
-rw-r--r--  1 root root   6792946 Jan 15 12:05 resources.pak
-rw-r--r--  1 root root     51553 Jan 15 12:05 snapshot_blob.bin
-rw-r--r--  1 root root    172386 Jan 15 12:05 v8_context_snapshot.bin
drwxr-xr-x  3 root root      4096 Jan 16 01:48 WidevineCdm
/usr/lib64/chromium-browser # 
```

`www-plugins/chrome-binary-plugins` created the `WidevineCdm` dir and system link finished it. Netflix/Amazon Prime fully functional. Cheers thanks for the assistance.

**Comment by PF4Public** [comment] 2021-01-16 11:34
I believe this issue is now completely resolved. Symlink should be created automatically upon install.
@Eloston, please, close this issue.

**Closed** 2021-04-03 22:30 UTC
Labels: need info
