### ISSUE TITLE
Missing profile switcher button

### ISSUE THREAD

**Issue by japostoles** [Eloston/ungoogled-chromium#131] opened 2016-12-01 23:25 UTC
Clean builds of Chromium usually have a button in the top right for switching profiles.  Right now, the only way to access profiles is to use the hot key (Command/Shift/M on a Mac).  

I know various bits as related to Google are disabled, but without the button or avatar image to let you know which profile you are in, it makes it really hard to use profiles.

**Comment by Eloston** [comment] 2016-12-02 02:40
Duplicate of #45 

If you want, you can download [a build of ungoogled-chromium 54 here](https://github.com/Eloston/ungoogled-chromium/issues/129#issuecomment-264066296). It should be practically the same as what I will publish to GitHub later on.

**Closed by Eloston** 2016-12-02 02:40 UTC

**Comment by japostoles** [comment] 2016-12-02 02:59
Ugh, sorry for not searching well enough to uncover that duplicate!

thanks for the link to 54!

**Comment by Eloston** [comment] 2016-12-02 03:00
No worries. It happens to everyone.
