### ISSUE TITLE
Should I be afraid of non-official build of Ungooled-Chromium?

### ISSUE THREAD

**Issue by farinelli123** [Eloston/ungoogled-chromium#1325] opened 2021-01-12 17:11 UTC
I know there is a small posibility to download a harmful or tampered release because if you don´t build by your own you have to download someone else`s exe. But, is this well moderated? Really I don´t know how to inspect this kind of code.

**Comment by solonovamax** [comment] 2021-01-13 00:01
For downloading binaries, use the site linked in the github README, [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/). Those *should* be trustworthy enough.

**Comment by farinelli123** [comment] 2021-01-13 00:14
> For downloading binaries, use the site linked in the github README, [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/). Those _should_ be trustworthy enough.

Hi mate! I´m new into this browser. Do you recommend installing it via Chocolatey? I read something about this could help me to keep updated ungoogled-chromium without reinstalling

**Comment by zespire** [comment] 2021-01-13 05:57
This is the easiest way to install with auto updates: https://github.com/iklevente/ChromiumForWindows
It uses files from https://github.com/macchrome/winchrome

**Comment by blackbeardth** [comment] 2021-01-16 17:36
@farinelli123 chocolatey uses the same binaries as listed here. so you can install from chocolatey.

**Comment by j-james** [comment] 2021-01-20 03:30
To somewhat hijack this thread, it'd be fantastic to get official releases from a build server or similar through GitHub. Ungoogled Chromium binary packages are constantly removed from the AUR because there aren't any official builds.

**Comment by ahtaarra** [comment] 2021-01-20 13:22
Builds are only as trustworthy as the builder and the build tools. But unless people from ungoogled-chromium project trusted them to a certain extent, they would not be linking to those.

I built my own binary fairly recently (this being the first and only time I built it so far) and I think the shift to reproducible build systems would combat this trust issue.

**Comment by engineeror** [comment] 2021-11-16 21:30
> To somewhat hijack this thread, it'd be fantastic to get official releases from a build server or similar through GitHub. Ungoogled Chromium binary packages are constantly removed from the AUR because there aren't any official builds.

this would be "official" enough for me personally https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium#manualArch

**Comment by PF4Public** [comment] 2021-11-29 14:54
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.

**Closed by PF4Public** 2021-11-29 14:54 UTC
