### ISSUE TITLE
OBS installation of ungoogled-chromium doesn't load pages

### ISSUE THREAD

**Issue by robertalks** [Eloston/ungoogled-chromium#1765] opened 2021-12-08 17:43 UTC
I've installed on my Ubuntu machine ungoogled-chromium using the OBS repos, all is fine, but when trying to open a page, any page, nothing load. Just sits there all fancy and judgemental.

Normal google chrome or firefox work perfectly fine.

**Comment by networkException** [comment] 2021-12-08 22:05
Duplicate of #1698

**Closed** 2021-12-08 22:12 UTC
Labels: duplicate
