### ISSUE TITLE
URL shortening not working

### ISSUE THREAD

**Issue by AdisonCavani** [Eloston/ungoogled-chromium#1669] opened 2021-09-26 17:28 UTC
There is a option to shorten URL - right click and enable ``Always show all URL adresses``, but it's not working.

Ungoogled:
![full](https://user-images.githubusercontent.com/76855180/134817794-140540ba-0401-413c-977f-323defb9fc6b.png)

Chrome:
![shorten](https://user-images.githubusercontent.com/76855180/134817789-e555a39c-61cd-4292-97b1-8f64d48e6db0.png)

**Comment by wchen342** [comment] 2021-09-26 18:34
It is disabled on purpose: https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/disable-formatting-in-omnibox.patch.

Maybe add a flag?

**Comment by networkException** [comment] 2021-09-27 12:16
This is a duplicate of #1438

**Closed by networkException** 2021-09-27 12:16 UTC
