### ISSUE TITLE
Google services available?

### ISSUE THREAD

**Issue by Chexier** [Eloston/ungoogled-chromium#973] opened 2020-03-24 14:54 UTC
I have built ungoogled-chromium 80.0.3987.149 from the AUR, and I see that (at least) 3 google services can be enabled (with the GUI), although disabled by default. What happened? In previous releases this didn't occur, and google ~botnet~ services couldn't be enabled at all.

**Comment by PF4Public** [comment] 2020-03-24 17:43
>3 google services can be enabled

Which exactly?

**Comment by Eloston** [comment] 2020-03-24 20:09
Also, what specifically in the GUI are you referring to? `chrome://settings`?

**Comment by Chexier** [comment] 2020-03-24 20:51
> Also, what specifically in the GUI are you referring to? `chrome://settings`?

Yes.

>Which exactly?

![google](https://user-images.githubusercontent.com/59852609/77475607-d79d9580-6df7-11ea-99be-722881be796d.png)

Plus, the "Allow Chromium sign-in" option can be enabled.

**Comment by Eloston** [comment] 2020-03-24 23:19
I don't remember off the top of my head if we removed them at some point, but doing so would only benefit us cosmetically. All the underlying code is either patched out or broken by domain substitution.

Do you find that these services contact Google when you enable them?

**Comment by Chexier** [comment] 2020-03-25 00:06
> Do you find that these services contact Google when you enable them?

Enabling google services didn't make a difference here, so no, they don't contact Google. I have tested it with mitmproxy.
It's just weird to see these options being available.

**Comment by Eloston** [comment] 2020-03-25 01:35
Actually this is a duplicate of #369. Closing as such.

**Closed by Eloston** 2020-03-25 01:35 UTC
Labels: need info
