### ISSUE TITLE
Provide x86 support

### ISSUE THREAD

**Issue by guest271314** [Eloston/ungoogled-chromium#1015] opened 2020-04-25 21:36 UTC
**Is your feature request related to a problem? Please describe.**
Running Chromium team PPA https://launchpad.net/~chromium-team/+archive/ubuntu/dev. 

Several recent version have unresolved issues at 32-bit

- Certain tabs crashing https://bugs.chromium.org/p/chromium/issues/detail?id=1071071
- DevTools not opening https://bugs.chromium.org/p/chromium/issues/detail?id=1072187
- Removed support for setting search engine other than google . com https://bugs.chromium.org/p/chromium/issues/detail?id=1074658

**Describe the solution you'd like**
x86 support for ungoogled-chromium. Particularly for 

> - Add Omnibox search provider "No Search" to allow disabling of searching

**Describe alternatives you've considered**

Using a version of Chromium team PPA that is not most recent dev channel release.

Currently x86 is not supported per https://launchpad.net/~braewoods/+archive/ubuntu/ungoogled-chromium

> Currently this PPA publishes packages for armhf, arm64, and amd64.

**Additional context**
The removal of support for setting search engine to a value other than google . com is particularly an intention step down a slippery slope due to https://bugs.chromium.org/p/chromium/issues/detail?id=1072248 (essentially disabling ability to not search: send google . com anything typed in address bar "Omnibox").

**Comment by Eloston** [comment] 2020-04-25 22:36
Technically a duplicate of #64. Moving discussion there.

**Closed by Eloston** 2020-04-25 22:36 UTC
