### ISSUE TITLE
Use opensuse build service

### ISSUE THREAD

**Issue by Arjoni** [Eloston/ungoogled-chromium#59] opened 2016-09-27 20:14 UTC
Please use opensuse build service to automatically create binaries and repos for all linux distros. https://build.opensuse.org/

**Comment by Eloston** [comment] 2016-09-27 20:17
Why use openSUSE Build Service as opposed to builders for the individual distributions like Launchpad for Ubuntu?

This is a duplicate of #17. Please respond in that issue report. Thanks

**Closed by Eloston** 2016-09-27 20:17 UTC

**Comment by Arjoni** [comment] 2016-09-27 20:26
Because opensuse build service will create them all see this example: https://software.opensuse.org/download.html?project=home%3AHorst3180&package=arc-theme

**Comment by Eloston** [comment] 2016-09-27 20:29
That may be convenient, but there may be other advantages and disadvantages we need to consider.

Plese do not continue to post in this issue report. Use #17.
