### ISSUE TITLE
Remove references to Google and its services in settings and other places

### ISSUE THREAD

**Issue by dietofworms** [Eloston/ungoogled-chromium#1094] opened 2020-07-03 03:07 UTC
It would be great if the application did not even reference Google. Rather than having `You and Google` just have it say `You`. I would also think it would be wise to remove the `Sync and Google Services` section. If one would like to use Google services, they probably wouldn't be using Ungoogled Chromium.

Other Chromium browsers like Brave have removed references to Google so I think it would be feasible in this project.

![chromium_google_references](https://user-images.githubusercontent.com/28944297/86427512-b2d98800-bd2d-11ea-8d21-aa1d49a404fd.jpg)

**Comment by PF4Public** [comment] 2020-07-03 10:36
What are the benefits apart from cosmetic changes?

**Comment by dietofworms** [comment] 2020-07-03 23:13
It is only a cosmetic change but it is in-line with the **Ungoogled** ethos of the application.

**Comment by wchen342** [comment] 2020-07-08 22:30
Yeah this I agree. It is beneficial to let users know we are apart from Google. This shouldn't be hard, probably just substituting texts in `.grd` files, but tedious since you need to go through A LOT of texts.

**Comment by Eloston** [comment] 2020-07-17 18:39
Technically a duplicate of #369. Marking as duplicate.

**Closed by Eloston** 2020-07-17 18:39 UTC
